### PR TITLE
Win fixes

### PR DESCRIPTION
**Pull request by ananace**
So that it works on windows, the edits to the find script shouldn't be able to break on other systems.

### CODE REVIEW

**Comment by zinnschlag** [comment]
Does not build for me: https://gist.github.com/2214206

**Comment by ananace** [comment]
I'm assuming it builds without these changes, and that's strange because it's an error in openengine/gui/manager, complaining about MyGUI's OgrePlatform. My changes shouldn't have touched either of them.

Unless the FindMyGUI script doesn't find the Ogre platform library on your system...
What's the value of MYGUI_PLATFORM_LIBRARIES for you?

**Comment by zinnschlag** [comment]
MYGUI_PLATFORM_LIBRARIES:STRING=

**Comment by ananace** [comment]
I looked through the cmake script and it seems to be missing finding the platform library, which can be seen as a problem.
Seeing as it compiles without the changes I think it shouldn't be too hard to fix.

Can you try replacing it with this modified one and see how it goes?
https://gist.github.com/2216527

**Comment by zinnschlag** [comment]
yeah, that did it.

**Pull request merged**
