### PR TITLE
Bug #1185 fix - always cleanup

### PR DESCRIPTION
**Pull request by cc9cii**
Cleanup the environment for all situations - new game, loading a save game or after failing a save game load.

### CODE REVIEW

**Comment by zinnschlag** [comment]
That looks wrong. If there is no game, then no cleanup should be required. If cleaning up in no game state fixes something (not accounting for failed loads), then we may have a problem elsewhere. Will have to take a closer look at the situation.

**Comment by cc9cii** [comment]
If we can have another state - e.g. State_Error - then we can put that check for State_NoGame back into cleanup().  Doing this will take care of the situation where we get an exception during save game load, i.e. exception thrown before we get to State_Running.

Alternatively mState can be set to State_Running in the catch block before calling cleanup() if we don't want to create State_Error.

Or, if we want to keep the 'force' parameter we can repoen pull request #1282 and close this one.

**Comment by ghost** [comment]
Zini, read the last few comments of bug 1185, that should explain the situation.

**Comment by zinnschlag** [comment]
@cc9cii: We do not need an error state. Exceptions during loading are already taken care of (see the try catch block).

@scrawl: That is not what I see in the code. We do a cleanup before loading a new game. This should remove any state, including all physics. The cleanup code is only bypassed, if there is no state to begin with. If that is not the case, then we have a flaw in the logic somewhere.

**Comment by cc9cii** [comment]
Ok, I'll close this one and reopen the other.

**Comment by ghost** [comment]
@Zini: But "no state" currently means that cell (0,0) is loaded. And overwriting the references of that cell with refs from the savegame then causes it to not unload properly. There is the flaw.

**Comment by zinnschlag** [comment]
No state should not mean that the cell (0, 0) is loaded. That happens only on starting a new game. Loading will do a clear first, which includes moving the player to void and deleting all cells. If that does not work, that means we have a bug somewhere and the solutions proposed here will only mask it.

**Comment by ghost** [comment]
Loading does not do a clear if starting without --skip-menu, but (0,0) was still loaded.

**Comment by zini** [comment]
yoyo, i got this notification, but i'm zinibugs... not zini...

On Wed, Mar 12, 2014 at 8:47 AM, scrawl notifications@github.com wrote:

> Loading does not do a clear if starting without --skip-menu, but (0,0) was
> still loaded.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/zinnschlag/openmw/pull/1283#issuecomment-37382675
> .

## 

Philipp Conrad
curator/artist liason
ramen music dot com
mooch off my subscription: http://ramenmusic.com/issue-09/6be8afca6a

**Comment by zinnschlag** [comment]
Lol. That was funny.

> Loading does not do a clear if starting without --skip-menu, but (0,0) was still loaded.

Well, that is a problem. Will try to have another go at the code over the next few days (a bit busy here right now).

**Pull request closed without merging**
