### PR TITLE
Removed "Unloading Cell..." text

### PR DESCRIPTION
**Pull request by ghost**
OpenMW unloads the cell so fast, it's hardly noticable. This commit gets rid of
the "flicker" every time a cell loads.

Please ignore the other pull request. I messed it up somehow.

### CODE REVIEW

**Comment by zinnschlag** [comment]
Why is everybody throwing outcommented code at me today? Please don't do that. If a piece of code is not needed anymore, it should be removed, not commented out. We have a VCS to keep track of previous versions.

The change itself looks reasonable. I am not sure what you mean with "flicker" though. This is not related to https://bugs.openmw.org/issues/580, right?

**Comment by ghost** [comment]
Ok. I will add a commit to remove the commented lines.

You can see "unloading cells" for a very short moment (1-2 frames) every
time you change the cell. In my opinion this is not necessary.

I guess it fixes bug 580 as well. 

EDIT: Yes, it does

2013/2/28 Marc Zinnschlag notifications@github.com

**Comment by zinnschlag** [comment]
> I guess it fixes bug 580 as well.

Meaning you can not confirm it? You don't get this bug?

**Comment by ghost** [comment]
Not anymore. I am sure the bug is fixed for good.

**Pull request merged**
