### PR TITLE
Ai combat

### PR DESCRIPTION
**Pull request by gugus**
-getLineOfSight script instruction works
-AiCombat works, but there is no sound, and combat initialization conditions are not all filled (basicaly, any condition related to crime is not implemented), and the check to start combat is in aisequence.cpp, probably not the best place (any suggestion?). Also, the time between two slash was set by hand, and we might have to change it later.

### CODE REVIEW

**Comment by zinnschlag** [comment]
Issues:
- The code for starting combat works only for NPCs, not for creatures.
- The AISequence is indeed the wrong place for starting combat. MWMechanics::Actors maybe?
- Combat related script instructions are still missing.

We can handle the script instructions in a 2nd pull request (and the time between attacks and other methods of combat initialisation), but the other two issues should be addressed before the merge.

Crime related triggers (with the exception of a direct attack on an actor) will be handled in a separate issue (Crime & Punishment). You don't need to bother with them for now.

And a general code quality hint:

This construct:

>   if(mCombatPackage)
>    {
>        delete mCombatPackage;
>        mCombatPackage = 0;
>    }

is unnecessary. Just write:

delete mCombatPackage;
mCombatPackage = 0;

and be done with it.

**Comment by gugus** [comment]
Mhhh this needs more work than I thought. Creatures are not ready for combat it seems.  You cannot equip weapons and such as there is no InventoryStore

according to KittyCat:
<KittyCat> I think it may work to just give creatures an InventoryStore instead of a ContainerStore, but I don't know what repercussions that will have
MWRender::CreatureAnimation will also need to be extended to handle equipped items on Biped creatures

**Comment by zinnschlag** [comment]
Do we need to bother with this at this point? Most creatures can not use weapons. I would expect it being relatively easy to use do the implementation of creature combat now and just skip weapon wielding creatures for now.

**Comment by gugus** [comment]
creatures combat animations are not implemented, and I don't know exactly how they work. I'm going to ask Chris for advices

**Comment by zinnschlag** [comment]
If that will take longer, we can make it a separate issue too (don't wanna carry around a branch for ages just to end up with massive merge conflicts). But the 2nd issue in my list needs to be addressed first before we can have a merge.

**Comment by gugus** [comment]
Sure. I'm sorry I don't have much time these days :( but issue 2) should be easy.

**Comment by zinnschlag** [comment]
Okay. Please do not forget to add new issues to the tracker for those functionalities that were left out.

**Comment by gugus** [comment]
done

**Comment by gugus** [comment]
mhh I feel like the code that add the AiCombat Package should be in the creatureState.setHostile function, so that whenever a part of openmw tags a creature as hostile, it create an AI package. What do you think?

**Comment by zinnschlag** [comment]
The setHostile function can't stay the way it is anyway, since it only supports hostility towards the player. But NPCs can fight each other too. Since we either have to remove or completely change this function, let's not move other stuff into it for now. We can move code around later once we have figured out how to do things properly.

Overall this pull request looks good. I noticed two problems:
- NPCs with ranged weapon run towards you and stand right in front of you when fighting (this can be fixed separately)
- Many NPCs are hostile now. That is correct, but it makes testing of anything but combat very hard. I think there is a script instruction that disables AI. This instruction should be implemented before the merge, so we don't make testing a pain in the arse for everyone else.

**Comment by ghost** [comment]
There's a ToggleAI function (is that per NPC or global?)
Personally, I think that AI on by default is not a big issue. Annoying for caves like beshara obviously, but i'm starting in toddtest anyway which is more useful for testing. And towns/houses etc are also fine. Seems like enough places to test non-combat features.

**Comment by zinnschlag** [comment]
"NPC or global" is a good question. I always thought this was global (like all the toggles), but the documentation is not clear on this. If it is per NPC then we have a problem, because OpenCS will provide a feature to launch OpenMW as a tool for testing content. There are enough scenarios where you will not want to deal with hostile NPCs. I guess if it is per NPC, we can add a new command line switch that disables AI instead.

**Comment by gugus** [comment]
done (it's global, I tested on vanilla)

**Pull request merged**
