### PR TITLE
Opening doors

### PR DESCRIPTION
**Pull request by ghost**
I'm open (no pun intended) to suggestions where to put mDoorStates. Maybe CellStore?

### CODE REVIEW

**Comment by zinnschlag** [comment]
Door state needs to go into a CustomData object (with suitable MWWorld::Class function to access the state.

Can we factor out the door code in doPhysics into a private function please? Functions that give you time to grab a cup of tea while scrolling from the top to the bottom are not helpful for maintainability. 

Also, have you considered what happens when a door is deleted or moves to a different cell or the door's cell becoming inactive, while the door is opening/closing?

**Comment by ghost** [comment]
> Door state needs to go into a CustomData object (with suitable MWWorld::Class function to access the state.

I wanted to avoid that. I would have to iterate through all door objects in the cell and check if they are currently opening/closing. With the map approach, there's convenient access to only the relevant (currently moving) doors.

> Also, have you considered what happens when a door is deleted or moves to a different cell or the door's cell becoming inactive, while the door is opening/closing?

That is handled. It skips deleted doors and doors that aren't in the player cell (although the latter is probably too agressive, probably should check if the cell is active instead).

**Comment by zinnschlag** [comment]
> I wanted to avoid that. I would have to iterate through all door objects in the cell and check if they are currently opening/closing. With the map approach, there's convenient access to only the relevant (currently moving) doors.

We are talking about two different things here. Is the door currently in the process of opening/closing (a state only relevant to the active cells) and is the door open or closed (a persistent state). The former can go into its current place, but the later needs to go into a CustomData object.

> That is handled. It skips deleted doors and doors that aren't in the player cell (although the latter is probably too agressive, probably should check if the cell is active instead).

I see. That is indeed to aggressive. It can fail in under several circumstances. Checking if the cell is active is the correct way to go.

However there is a bug in the code:

> ```
>     for (std::map<MWWorld::Ptr, int>::iterator it = mDoorStates.begin(); it != mDoorStates.end(); ++it)
>    {
>        if (!it->first.getRefData().getCount())
>            mDoorStates.erase(it); 
> ```

You are erasing the object your iterator is pointing to. That is like cutting off the branch you are sitting on.

Also, you seem to assume that the local rotation is only used for the door rotation. That is not the case. Therefore you can't just check it to see, if the rotation has finished.

**Comment by zinnschlag** [comment]
Also, your check for deleted objects won't work (took me a moment to figure that out myself). Once we have object garbage collection, Ptrs to objects in inactive cells are not guaranteed to persist across frames.

**Comment by ghost** [comment]
> Also, you seem to assume that the local rotation is only used for the door rotation. That is not the case. Therefore you can't just check it to see, if the rotation has finished.

Tests in vanilla have shown that the local Z rotation integrates with the door open/closed state. If I locally rotate a _closed_ door in the +Z direction, then activate it, it actually closes and reverts to a Z rotation of 0. The only explanation for that is that a local Z rotation > 0 represents to the game that the door is opened, which is what my code currently does.

For the same reason, the "second" door state you are talking about here

> Is the door currently in the process of opening/closing (a state only relevant to the active cells) and is the door open or closed (a persistent state). The former can go into its current place, but the later needs to go into a CustomData object.

is in fact not needed.

**Comment by ghost** [comment]
Better?

**Comment by zinnschlag** [comment]
Crap. I would consider that a bug and if it where not implemented already, I would suggest to not to duplicate it. MW rotations are a pain in the arse.

**Comment by ghost** [comment]
It seems fine to me. It simplifies the implementation and I don't see a reason to apply any local rotations to doors other than the door controller rotation.

**Comment by zinnschlag** [comment]
The loop is still broken. You are skipping a door now, if the door is deleted. There is no way to get this kind of loop working with a for. You need a while loop. However you also need to take my comment about Ptrs becoming invalid into consideration. I think the best solution would be to purge the door list on every cell change.

**Comment by zinnschlag** [comment]
> It seems fine to me. It simplifies the implementation and I don't see a reason to apply any local rotations to doors other than the door controller rotation.

Since the local rotation is the only type of rotation we can control properly via scripts, this is anything but fine. A mod might decide to rotate a whole room including the doors. That is not possible with the current approach.

**Comment by zinnschlag** [comment]
> I think the best solution would be to purge the door list on every cell change.

if that I mean remove doors in inactive cells.

**Comment by ghost** [comment]
I think that should be it.

**Comment by zinnschlag** [comment]
Yeah, that fixes the loop. Only the cell change problem left.

**Comment by ghost** [comment]
What cell change problem are you talking about? The door animation being left in an unfinished state when it is moved to an inactive cell?

**Comment by zinnschlag** [comment]
A frame starts. Door animations are running. A cell change happens. A door in the process of closing is now in an inactive cell. But it is still listed. The frame ends here.
Then object garbage collection kicks in. Objects in inactive cells are deleted properly. Some or all Ptr to objects in inactive cells become invalid. But we still have such a Ptr in the door list in World.

I see that you only access the cell member and not anything that is actually pointing to the object. That should work with the current implementation, but it is very unclean and may cause unexpected problems if we ever change the underlying implementation of the cell storage/Ptr class.

Noted another problem: When a door is moved to a different (active) cell while opening/closing the opening/closing process is interrupted. But since manipulating non-loading doors seems partially broken in MW anyway (rotation), we can go along with it for now, I guess (unless we are breaking someone's mod). But after 1.0 we have to take another look at the whole situation.

...

Okay, thought it through once more. Since we will need to have another go at it anyway (and probably replace the specialisted door code with a more generic method for handling of objects that change continuously across multiple frames), we can as well go along with the working but somewhat fragile implementation for now. No point in investing time into functionality that we may never need.

Incoming merge ...

**Pull request merged**
