### PR TITLE
Marcin Hulist

### PR DESCRIPTION
**Pull request by Gohan1989**
I try my best to make it fast and good :) I think this time I make good upload to git hub :)

### CODE REVIEW

**Comment by zinnschlag** [comment]
These are the problems I am seeing:
1. You are missing the Activate package.
2. You have a superfluous file at openmw/apps/openmw/CMakeLists.txt.
3. The filename of the follow package is misspelled.
4. Please use initialiser lists in the constructors.
5. String arguments should be passed via const references.
6. In the clone function please just return the newly created package without any intermediate variables (they are unnecessary and also may harm optimization).
7. As I wrote before reset is probably not part of the package.
8. Please remove redundant forward declarations and includes from the headers (for example in aiescort.hpp the Ptr declaration is not needed and neither are the iostream and the vector includes).
9. Please adjust the header/include guards. The current names do not match what we use elsewhere (have a look at some files in the vicinity of your files, for example aipackage.hpp) 
10. The cout messages have spelling errors.

**Comment by Gohan1989** [comment]
Maybe this time I fixed all bugs. If you find any pleas let me know. I think there will be some errors in AIActivate class.

**Comment by zinnschlag** [comment]
1. Still some problems with the naming conventions. Variable names should start with lower case (check the constructors).
2. Some packages missing a public.
3. The index range check in AiWander::getIdle is redundant. std::vector::at already does a range check.
4. AiActivate should store the ID of the object to activate, not a Ptr to it. The Ptr will be determined at execution time.

Please note, that you should never store a pointer or reference to a Ptr. This class is intended to be used by value only. Your construct in AiActivate would have result in a pointer to a local variable, that once out of scope would have broken the entire program. This is a very dangerous construct.

**Comment by zinnschlag** [comment]
I should amend my last comment. Passing a Ptr by const reference is okay. But storing it, is not.

**Comment by Gohan1989** [comment]
Maybe this time :)

**Comment by zinnschlag** [comment]
Almost. I will merge your branch later and then do the remaining fixes myself. Please have a look at it afterwards.

**Comment by zinnschlag** [comment]
Will push in a moment. I have removed the get functions, because they were applied inconsistently (some where missing) and some were also lacking consts. Since we don't really need them, it was easier to remove them than to fix them. Also, in the future please make sure to name your branches appropriately (see branching policy on the wiki).

**Pull request merged**
