### PR TITLE
Rotate, RotateWorld script instructions, and local rotations layer.

### PR DESCRIPTION
**Pull request by Glorf**
Re-pulled

### CODE REVIEW

**Comment by zinnschlag** [comment]
Sorry, but we have another problem here. Your code is modifying the RefData object directly and is then calling a function in World, that passes on the changes to render system. That is not how it works. The world function must do both the changes to the data and the rendering update.

**Comment by zinnschlag** [comment]
Also, the changes to OpGetAngle look weird. It seems like you are adding the regular rotation and the local one. I can't see how that could possibly work.

**Comment by Glorf** [comment]
I now that getAngle looks strange, but it's exactly the way how Morrowind handles local rotations in this function. This strange behaviour was one of the problems that prevented me from translating local to world rotation - we should keep it working exactly as it's already working, even if it seems to be stupid.

EDIT: Anyway, I made a mistake: local rotation is added to cellref's rotation, no refdata's one (so rotateworld does not change getangle values at all!), thanks I'll fix it as well as world rotation function.

**Comment by Glorf** [comment]
Done

**Comment by zinnschlag** [comment]
This is getting even weirder now. If the getAngle function uses the cellref rotation values, setAngle would never affect the value returned by getAngle.

**Comment by Glorf** [comment]
You're right. It's because value set by setangle is nothing but local rotation! Thanks. Fix incoming.

**Pull request closed without merging**
