### PR TITLE
MSVC compile flag for 64bit debug build

### PR DESCRIPTION
**Pull request by cc9cii**
MSVC will fail to build debug openmw without /bigobj flag set.  Also added an entry in .gitignore for windows developers.

### CODE REVIEW

**Comment by nikolaykasyanov** [comment]
I'm not sure about OpenMW's policy about that, but it's a common good practice to ignore things like *.bak, Thumbs.db, .DS_Store and other trash like this in one global gitignore file.

**Comment by cc9cii** [comment]
I see, you mean add that to my local config only?  I'll try that.

**Comment by nikolaykasyanov** [comment]
http://stackoverflow.com/a/7335487/164834

**Comment by cc9cii** [comment]
Great, thanks.  A note: following the instructions in that stackoverflow page in msys shell does not work (I'm using Tortoisegit).  A windows cmd window should be used instead.

**Pull request closed without merging**
