### PR TITLE
Special Variables

### PR DESCRIPTION
**Pull request by wheybags**
Implemented the first of the special scripting variables (onpcequip), and fixed a small but very irritating bug from my previous patch making scripts in containers execute correctly.

### CODE REVIEW

**Comment by zinnschlag** [comment]
Can we have a bit of additional error handling in case the variable isn't a short? You can either assume the local variable does not exist, if it is not of type short (and do nothing in this case) or just ignore the type and use it anyway. I would prefer the 2nd option, since it is more robust and more in line with what the rest of MW does. If you go down this route, you may want to add a new function to MWScript::Locals:

getIntegerValue (int index, char type) const;

Or something like this. Might come in handy when you add other special local variables.

Also, I would prefer to merge all special variables code at the same time. Putting out pull requests for the purpose of code review is okay though.

**Comment by wheybags** [comment]
@chris,oh, I thought the script was responsible for resetting it.

@zinnschlag, I'm planning on adding the other variables to this request. I'll add checks to make sure it's a short when I get home.

**Comment by wheybags** [comment]
@Chris I investigated, and it seems that is not quite the case in vanilla morrowind.
It seems that if the script doesn't reset it, it is reset until the player changes cell, then it is set back to 1 again...
Given that this is clearly buggy behaviour, I think we can choose what to do in this instance.
What do people want?

**Comment by wheybags** [comment]
I think that's all that can be done for now, without enchanting and repairing being implemented (they aren't, are they?)

**Comment by zinnschlag** [comment]
Please factor out the local variable access like I proposed in my first comment. Repeating the same piece of code over and over again is not a good idea.

As for the remaining special variables, I was planning to check the list on the tracker, but that seems to be down at the moment, so I won't be getting to that today.

**Comment by wheybags** [comment]
So is this ok to merge now?

**Comment by zinnschlag** [comment]
Merging into next instead of master. Don't want to add new features that close to the release.

**Pull request closed without merging**
