### PR TITLE
Animation2

### PR DESCRIPTION
**Pull request by kcat**
Patches to enable character animations, and more vanilla-accurate physics as related to them.

### CODE REVIEW

**Comment by zinnschlag** [comment]
Does not work for me. The player character is totally immovable. None of the movement keys have any effects.

**Comment by kcat** [comment]
Hmm, odd. It works for me. Could you try doing a full rebuild? I've had issues where cmake doesn't rebuild some sources even when a dependency is changed, which leads to all sorts of fun issues. Or, do you have other patches not in the repo here?

**Comment by sergey-shambir** [comment]
JFIY: works for me too.

**Comment by kcat** [comment]
Well, crap. A recent change broke the Prison Ship model. This is a bit problematic, actually; I was initially employing a trick to avoid creating unnecessary bones for NiTriShape nodes, by attaching the corresponding mesh to the NiTriShape's parent and specifying the NiTriShape's offset as the TagPoint offset

But this broke the Akulakhan model since the NiTriShape parents didn't have unique names, which caused the meshes to attach to the wrong bone. I undid that so the uniquely named NiTriShape nodes would become bones, so the meshes would attach correctly.

However, that broke the Prison Ship model. For whatever reason, Bethesda seems to think it's okay for a single model to have over 100 individual NiTriShapes. Combined with the rest of the NiNodes, this blows past the 256 bone limit Ogre has for Skeletons.

Luckily the Prison Ship model does not need a skeleton. But it will be tricky to determine when a model like this can skip building its skeleton and just hard-code the transformations into the mesh.

**Comment by kcat** [comment]
That should fix it. I don't really like it, but between Bethesda's insanity with in_prison_ship.nif and Ogre's arbitrary 256-bone limit, it's just something I have to do. Things seem to check out, though. Something better can always be found later.

**Comment by ghost** [comment]
@zinnschlag , maybe your input configuration is now invalid or something? Does it change anything to delete input.xml in ~/.config/openmw ?

**Comment by zinnschlag** [comment]
Tried a full rebuild. Does not fix anything. Same with deleting input.xml. I am getting a lot of spam on the console though: https://gist.github.com/zinnschlag/5028595

**Comment by kcat** [comment]
Can you switch to third person and see if the movement keys at least make the character animate? Or does he remain idle? And is the idle animation itself playing?

**Comment by zinnschlag** [comment]
No animation in 3rd person at all. Neither idle nor movement animations.

**Comment by zinnschlag** [comment]
However if I enable physics the player character drops into the water and makes swimming movements (still nothing beyond that).

**Comment by ghost** [comment]
Check the return value of Npc::getSpeed. If it's 0, then you should debug why it's 0. Maybe not found GMSTs?

**Comment by zinnschlag** [comment]
Yeah, the speed is the problem. Always 0 for the player.

**Comment by zinnschlag** [comment]
Okay, now we can all have a laugh. Apparently I was over encumbered. My startup script was adding tons of stuff to the inventory and that went over the limit of the player character in its default state. Going to merge now ...

**Pull request merged**
