### PR TITLE
Bugfix #691: Auto equipping ignores equipment conditions - re-pull

### PR DESCRIPTION
**Pull request by Glorf**
Re-pulled https://github.com/zinnschlag/openmw/pull/766

I think it's good enough now.

### CODE REVIEW

**Comment by zinnschlag** [comment]
Why is the call to canBeEquipped in ActionEquip::executeImp located in the slot loop? Also, your switch construct is weird. If you used fall through on purpose, you should at least document it in the code.

**Comment by Glorf** [comment]
Fixed

**Comment by zinnschlag** [comment]
The argument order of the canBeEquipped function is still wrong. And I see no fall through comments.

**Comment by Glorf** [comment]
I've removed fall-throughs, moved switch once again.
And I am praying it's good now... :smile:

**Comment by zinnschlag** [comment]
> The argument order of the canBeEquipped function is still wrong.

To elaborate more on this: The Class hierarchy is a mechanism to introduce polymorphic behaviour into the plain record structs. We are kinda switching (without ugly switch constructs) on a Ptr. This Ptr is always the first argument in a MWWorld::Class function. Only in your function it is not (it is the second).

**Comment by Glorf** [comment]
Ok, now I understand what you mean. Oh dear, one bugfix and so many problems.

**Comment by Glorf** [comment]
Fixed

**Comment by Greendogo** [comment]
Hmmm, nevermind, it seems that script is non-functional, so it must be hardwired into the engine.  Why did Bethesda do it that way?  That makes it a pain for TCs when they do stuff like that.  Ah well.

**Comment by zinnschlag** [comment]
I presume they couldn't make it work properly, so they went for a quick and dirty solution. That is an ongoing topic throughout all of MW and Morrowind.esm.

**Pull request merged**
