### PR TITLE
UI

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by zinnschlag** [comment]
That crashes on startup for me:

marc:~/OpenMW/build$ ./openmw --master data/Morrowind.esm
Loading config file: /home/marc/.config/openmw/openmw.cfg... done.
Loading config file: ./openmw.cfg... done.
Using default (English) font encoding.
Data dir ./data
Data dir /home/marc/.config/openmw/data
Adding BSA archive ./data/Morrowind.bsa
Adding BSA archive ./data/Tribunal.bsa
Adding BSA archive ./data/Bloodmoon.bsa
X Error of failed request:  BadDrawable (invalid Pixmap or Window parameter)
  Major opcode of failed request:  137 (DRI2)
  Minor opcode of failed request:  12 (DRI2SwapInterval     )
  Resource id in failed request:  0x3800002
  Serial number of failed request:  29
  Current serial number in output stream:  32

**Comment by ghost** [comment]
I can't imagine anything I changed that could possibly cause this. It's probably a random crash that has been in for some time?
I've never seen this before, though it's been a while since I tried OpenMW on my laptop (which also has Mesa). Are you using an experimental driver by any chance?

**Comment by zinnschlag** [comment]
No that is just the standard driver. I get this crash on a regular basis when OGRE initialization is interrupted at a certain point. And you are right. There was a misconfiguration (leftover from the content file type change). Works now. Reminds me, that I need to write about that on the forum.

**Comment by ghost** [comment]
Interrupted at which point exactly?

**Comment by zinnschlag** [comment]
Sometimes between before creating the first window, I think. I never got around to pin that down.

**Pull request merged**
