### PR TITLE
Bugfix #795: Sound playing with drawn weapon and crossing cell-border

### PR DESCRIPTION
**Pull request by Glorf**

### CODE REVIEW

**Comment by kcat** [comment]
I don't think this is the right way to do it. The problem extends beyond the weapon sound because what happens is that the player gets removed from the scene when leaving a cell, destroying the old CharacterController and Animation object, then re-added in the new cell with a new CharacterController and Animation.

Not only does this mean the player plays the weapon sound when crossing cells, it also causes the player's state to reset, the Nif to be reloaded, and the animations to restart. What needs to be fixed is for the player to not be removed from the scene, to use the methods to update the Ptr that NPCs use.

**Comment by Glorf** [comment]
hmm, ok, I haven' t realised that a problem is so extended. Is there any reason why character controller is treated this way now? Deleting it and loading again seems to be very ugly way.

**Comment by kcat** [comment]
It's not really the character controller's fault. The player is special-cased when changing cells, such that it's removed from the mechanics and render sub-systems, the cells are updated (new ones loaded, old ones unloaded), and then the player is added back.

NPC handling has been changed such that when they cross into a new cell, the render and mechanics subsystems can just update the Ptr without removing and re-adding it (as long as it's moving between loaded cells, anyway). But because of the special way the player is handled for cell transitions, it wasn't so easy to remove the special-casing and simply update the Ptr like NPCs can be.

It would be nice to get rid of that special case if at all possible (or if not handle the player like any other NPCs, at least make it update the Ptr like NPCs), but I haven't had time to look at the code handling player cell transitions that deeply. If someone else can do it, though, that would be great.

**Comment by Glorf** [comment]
Of course, I meant player. 
I'll try to investigate this problem but not sure if I'll fix it. I go to offline zone in a week and I'll stay there for a month.
Just to inform.

**Comment by zinnschlag** [comment]
I'll accept this pull request as a temporary workaround. Having a better implementation for the player moving across cell borders would be good, but I do not see it as urgent.

The special treatment for the player reference is justified, because having the player reference stored alongside other references in a cell would just be a mess. But we don't necessarily need to remove and than add the player back if we can implement a simple move instead. I haven't looked into this part of the code for a long while, but essentially we should be able to treat the player in the same way as NPCs when crossing cell borders with the exception that the NPC references are actually deleted (in the old cell) and recreated (in the new cell), while the player reference stays stored in the same place.

**Pull request merged**
