### PR TITLE
Levelup

### PR DESCRIPTION
**Pull request by ghost**
For now, it can be activated at any time by pressing T.

I believe it is feature complete, maybe some things are not in the right place, I am open to suggestions for moving stuff around.

### CODE REVIEW

**Comment by ghost** [comment]
And here is skill gain from books. Note I had to use const_cast to remove the skill from the book after reading it. This will probably have to be changed when savegames are implemented.

**Comment by zinnschlag** [comment]
I see the following problems:
- AFAIK dynamic stats are integers. You can't have 1.5 health.
- implementing the skill level up tracking in useSkill will not work. Actually skill level up tracking does not work at all. You need to store the skill levels at the beginning and at each level up and compare with these. Skill level changes though set functions for skills can't be handled any other way.
- The enableLevelupMenu still has only a placeholder implementation.

> Note I had to use const_cast to remove the skill from the book after reading it.

You can not change ESM records. The const cast is wrong. I suggest you revert this commit.

**Comment by ghost** [comment]
> AFAIK dynamic stats are integers. You can't have 1.5 health.

See my post on the forum.

> implementing the skill level up tracking in useSkill will not work. Actually skill level up tracking does not work at all. You need to store the skill levels at the beginning and at each level up and compare with these. Skill level changes though set functions for skills can't be handled any other way.

Are you sure that changing skills through the console actually also increases level progress? I mean, these are only for testing, so they don't need to change level progress?

> You can not change ESM records. The const cast is wrong. I suggest you revert this commit.

Well , actually I can. Otherwise it wouldn't work. I know its wrong modelling of course. But at the moment there is no other way, until dynamic esmstore is implemented.

**Comment by zinnschlag** [comment]
> See my post on the forum.

Okay. Lousy idea though. Thumbs down for Bethesda.

> Are you sure that changing skills through the console actually also increases level progress?

Yes, I am sure.

> Well , actually I can. Otherwise it wouldn't work. I know its wrong modelling of course. But at the moment there is no other way, until dynamic esmstore is implemented.

No. The dynamic esm store is only for records created during runtime and for the player record. The later will result in an ugly hack, of which we definitely do not need even more. Records from the ESX files will not be changed (with the exception of the player). Ever!. Additional object data goes into CustomData objects as we have been doing it all along (for. Npcs, Creatures and Containers).

**Comment by ghost** [comment]
> implementing the skill level up tracking in useSkill will not work. Actually skill level up tracking does not work at all. You need to store the skill levels at the beginning and at each level up and compare with these. Skill level changes though set functions for skills can't be handled any other way.

I have just tested it out in Morrowind, and using "player->modSkill" or "player->setSkill" did not have any effect on the level progress.

**Comment by zinnschlag** [comment]
Strange. I am 99% sure that it did, when I tested it the last time. Maybe I am getting old.

About the skills from books: I just noticed that a CustomData object would provide a per-object instead of a per-ID flag. That is obviously not what we want. Well, we need to implement additional per-ID data storage for things like kill counts anyway. That is not something we should rush though.

**Comment by ghost** [comment]
Maybe just store a list of book IDs in the MWWorld::player object?

**Comment by zinnschlag** [comment]
That will fail, if we ever decide to also allow NPCs to learn skills from books. Really, that needs to be thought through properly. Just revert the book skill gain. We will implement it properly, when the backend is ready for it.

**Comment by ghost** [comment]
Ready to merge then?

**Comment by zinnschlag** [comment]
Nope. Want to finish the discussion on the forum first. Also, we already have a mechanism for enabling/disabling GUI elements. Should it be re-used for the level up dialogue?

**Comment by ghost** [comment]
That was for the parts of the right-click menu.

**Pull request merged**
