### PR TITLE
Portability

### PR DESCRIPTION
**Pull request by dougmencken**
To review and to merge.

### CODE REVIEW

**Comment by ghost** [comment]
Using Ogre::Real all over the place, especially in the read only NIF structs, is probably not a good idea, as it will waste precision and memory when building Ogre on x86/x64 in double precision mode. We should leave this mode enabled for the future, as it could be potentially useful (combined with camera relative rendering) for solving precision issues with big coordinates (Which are, in a certain extent, already present in MW).

> struct Lockpick : Tool

This has nothing to do with portability improvements and zini already rejected it. Why is this contained in the pull request?

I suggest you open a new pull request with only the first few commits (that solve the LE/BE issues) included.

**Comment by dougmencken** [comment]
scrawl, why don't you like these commits (they are about general portability):
https://github.com/dougmencken/openmw/commit/6b629b13f3cd060713ec2a13c1c622a898889370
https://github.com/dougmencken/openmw/commit/a2fceb809a93e7e2882e643bbef32f155cf927db
https://github.com/dougmencken/openmw/commit/890835d29b1184e30bc02e6fa2797b6904205491

and this one which is just very useful for debugging esm i/o:
https://github.com/dougmencken/openmw/commit/53a2b25562b0acd235dfb5eb013fbdf299647b88

UPD: you cannot build openmw without Ogre::Real patch when you will use "Ogre on x32^W80x86/x64^W????80x86 64-bit AMD64/Intel EM64T in double precision mode". Just try it.

**Comment by zinnschlag** [comment]
Just a heads-up: Reviewing this pull request will take me a bit longer than expected (probably later today). Sorry for that.

**Comment by zinnschlag** [comment]
I merged your char fix via cherry-pick. The inappropriate char use is gone now. And good riddance to it. Makes me cringe inside every time I see someone using a plain char for a non-character variable.

For the rest of this pull request things don't look so good. There are several problems:
1. You have at least one commit in there, that is not supposed to be merged into master/next. The OGRE 1.9 change would probably have broken the build for some configurations. Please be more careful with what you merge in the future. Also, this is another example of a "here is some useful stuff" branch (I seem to get them a lot at the moment). Mixing different things in the same branch is not helpful.
2. As mentioned before the Tools change is a no go.
3. Same for Ogre::Real. Scrawl already explained why.
4. Your save code corrupts the record store. You are switching endianess and then you write the record to a file. But the original record is not discarded afterwards, so it has the wrong endianess now.
5. I could be wrong about that, but I don't think Windows has endian.h. If that is true, your portability branch would have broken the portability. Kinda funny.
6. Your code does not follow our coding guidelines (on the wiki). In particular you have too many defines and too many obscure names.
7. The endianness fixing code is rather bloated. I think this feature could be implemented with about half the code.

Sorry, but a merge is out of question here. Too many problems. If you want to do a rewrite, please consider the following comments and ideas:

a) We usual do not use defines for anything but conditional compilation. I am okay with making an exception for your FOURCHAR macro, because I can't think of any reasonable way to do it without a macro. But at least you should prefix the macro name with OPENMW_.

b) As I see it the endianness fixing requires only the inverting of the byte order (since we only have big and little). So on the lowest level (for basic types) a single function would be enough to do the job (a for loop running through half the byte size of the type and swapping bytes). You can even make it a template and determine the size with the sizeof operator.
Inside this function you can do a bit of conditional compilation, namely do nothing if the endianess of the host machine and the ESM format match; otherwise do as described above.

c) Calling this function twice should restore the original endianness, which means it can be used both for converting from little to big and from big to little.

d) Each record struct should implement a single adjustEndianness function, that can be used both for saving and for loading.

e) Doing endianness correction for basic types in the esm reader is convenient, but inconsistent. Since we are doing most of the fixing inside the record structures, we should consider doing all of it there.

**Comment by dougmencken** [comment]
First question: why if you picked the first commit, you didn't it also for https://github.com/dougmencken/openmw/commit/a2fceb809a93e7e2882e643bbef32f155cf927db ? 
Is it a must to deal with these three fields unlike others? And to use weird  if ((int)idx >= 0 && (int)(idx) <= 26) and like? Why are there three fields so special, so they shall use (signed in my first caught-by-build-error commit) char instead of int? Or is it just "don't change unless you must" (in this case, I wouldn't comment this "position", okay)?

Also, why don't you like this commit: https://github.com/dougmencken/openmw/commit/6b629b13f3cd060713ec2a13c1c622a898889370 (is it better to get "length of file less than 12 bytes" instead of "file does not exist" in cases when it does not actually exist?).
And this: https://github.com/dougmencken/openmw/commit/890835d29b1184e30bc02e6fa2797b6904205491 (including "internal-for-package-must-never-use-directly" header does result in broken build for Arch GNU/Linux, for example). 

About sizeof — great idea! Another problem is how to distinct 32-bit from 32-bit float... But this can easily be done with unions. And yes, I know about write/save counterparts. I planned to add them further.

As for endian.h and Windows, I asked on IRC if some guy with compiler on Windows can test does it exist or not.
If not, we can always do #ifndef le32toh #define le32toh...

**Comment by zinnschlag** [comment]
> First question: why if you picked the first commit, you didn't it also for dougmencken@a2fceb8 

Because there was so much stuff of various nature in the commit list, that I simply missed it. This commit literally drowned in the noise. Will fix that tomorrow.

> Also, why don't you like this commit: dougmencken@6b629b1

Well, it is kinda redundant. If the file does not exist, fsize should be 0, which is less than 12. "File too small" also is kinda an acceptable description for a non-existing file. To be honest, I wouldn't mind a better error description, but it is such a tiny improvement, that I did not find it worth bothering with picking it out of that mess.

> And this: dougmencken@890835d (including "internal-for-package-must-never-use-directly" header does result in broken build for Arch GNU/Linux, for example). 

I was not aware, that this actually causes problems. Would have been nice to have that in the commit message or in the pull request description. Will fix that tomorrow.

> If not, we can always do #ifndef le32toh #define le32toh...

Um, stop it please. We do not use defines in that way in OpenMW.

**Pull request closed without merging**
