### PR TITLE
making CPack usable for creating debian package

### PR DESCRIPTION
**Pull request by ghost**
changes boost required versions to 1.49.0 since it is the first accessible which match the >1.46 constraint.
It means that debian testing at least is needed to install openmw

### CODE REVIEW

**Comment by zinnschlag** [comment]
Are we sure that does not break anything? Because at least on Mint (and I assume on Ubuntu) 1.46 is still the default that OpenMW should be build against. I am not sure if the current Ubuntu packages even use this part of the cmake script, but I would like to have a clarification from our Ubuntu maintainers first before I merge.

**Comment by ghost** [comment]
I just looked on Ubuntu search service, and it seems that last stable Ubuntu does not have this version of boost [1]. But, as debian stable, it does not have ogre 1.8 too [2].

I tried to search for mint, but the search tool on their website is quite strange: I was able to find linux, but not ogre or boost, so I have not idea about which version their users have.
But as classic Mint is based on Ubuntu, I guess the problem is the same. For Mint LMDE, it is based on Debian testing, so I think this is okay with 1.49.

But confirmation should of course be useful

[1] http://packages.ubuntu.com/search?suite=all&arch=any&searchon=names&keywords=libboost-all-dev
[2] http://packages.ubuntu.com/search?suite=all&section=all&arch=any&searchon=names&keywords=libogre-1.8

**Comment by psi29a** [comment]
We support Ubuntu >= 10.04 (Lucid) which uses 1.40.0.1... however, our Ubuntu build process doesn't use cmake. We use debuild/buildbot from Launchpad. Launchpad also has support for Debian, but we just haven't gotten around to setting it up.

Honestly, I think the patch should be reworked for the various Debian based distributions. If we make it Debian centric then we lose support for Ubuntu and Mint. 

@zinnschlag: what do you think and how should we handle this?  We do not use cpack for ubuntu and in the future are our launchpad builds also for debian. What is the point of cpack for deb that then just for legacy?

Another solution, drop libboost depends (like we did for libbullet and ogre) which is fine by us in Ubuntu because we compile statically anyway. :)

**Comment by zinnschlag** [comment]
I honestly don't know how to deal with this situation. Packaging really isn't my area of expertise. This discussion should come to a conclusion soon though, since I want to start the release in the first half of this week. I am okay with a temporary solution that works for now.

**Comment by psi29a** [comment]
Temp solution is approve the commit for 'next' branch, Ubuntu doesn't use cmake so it is OK for now. Eventually we should drop libboost dependencies and just statically compile because 'who knows' what bugs will creep in/out from boost revisions, it is good to nail just a specific revision of our libraries.

**Comment by zinnschlag** [comment]
> Temp solution is approve the commit for 'next' branch.

Don't we need it for master? At least for 0.18.0 we still need a deb package for Debian, right?

**Comment by psi29a** [comment]
Have we ever made packages for Debian?

**Comment by zinnschlag** [comment]
Well, there are some older deb files on our download site. Not sure, if that was for Debian specially and there is nothing more recent.

**Comment by psi29a** [comment]
I just checked with launchpad: 
https://bugs.launchpad.net/launchpad/+bug/188564
They will not provided PPA space for debian only packages.

If bmorel wants to be the active maintainer of the debian builds, he is more than welcome to. However I recommend doing it via debuild (chroots for both i386 and amd64 statically) and not just relying cpack which currently only handles dynamic.

**Comment by ghost** [comment]
It is okay for me to maintain debian builds, but it sounds like I'll need to learn how to use debuild, if cpack is not ok.
But it is not a problem to learn.

If Cpack should not be used, maybe it would be wise to remove the mechanism with it in cmakefiles?

**Comment by zinnschlag** [comment]
Sounds like this is indeed not relevant for 0.18.0. I leave the discussion open, but go ahead with the release. What ever the outcome is can be merged for 0.19.0.

**Comment by psi29a** [comment]
Sounds good!

@bmorel: lets talk a bit more about this here... http://forum.openmw.org/viewtopic.php?f=6&t=1099
That way we can have distro-specific cmake/cpack rules.

**Comment by lgromanowski** [comment]
ok, I will remove cpack for deb files.

**Comment by ghost** [comment]
So I'll try to build debian packages with debuild.

@psi29a : since you recommended to use debuild, I am not really sure that talking about packages in a thread concerning cpack is very coherent?

[edit]
I forgot to ask... I did not see any package building related file in the master. Is it normal? I think debuild need at least some informations?

**Comment by psi29a** [comment]
@bmorel: it goes to very heart of of this pull request you sent Zini. cpack's ability to make deb packages is now being removed, then this patch is no longer relevant. 

 lets close this thread of discussion and move it back to the forums. feel free to create a new thread about creating debs for various distributions and we'll work out a how-to for the wiki. OK?

**Comment by ghost** [comment]
sounds fine for me

**Pull request closed without merging**
