### PR TITLE
Scripting things

### PR DESCRIPTION
**Pull request by wheybags**
Made items in containers (including npcs, creatures and the player) with scripts attached to them have the script run, like in vanilla morrowind.
This was mostly a prelude to my original goal, which was implementing these special variables: https://wiki.openmw.org/index.php?title=Scripting_(status)#Set_by_game

So far, I only implemented OnPCEquip, but I'll do the others too.

Oh, and I also added vim swap files to .gitignore, because it was annoying me :P

### CODE REVIEW

**Comment by zinnschlag** [comment]
Need a bit more time to review this.

**Comment by zinnschlag** [comment]
There are plenty of problems, unfortunately:
- Moving an object that contains objects with scripts from one cell to another is not supported.
- You set the cell field of Ptrs for objects not in the player's inventory (ContainerStore::add). That is wrong. Objects in containers do not have a cell.
- I might be wrong about that, but AFAIK most of these special variables don't just get state into the script. They can also be used from the script to modify things. Again, I am working from memory here, but I think MW isn't working with the state of the variable, but changes to it. If that is true, your approach will fall flat. That definitely needs to be looked into (feel free to use the forum to request help with research). An example for what I mean would be a cursed item that you can neither drop nor unequip. I am almost 100% sure that I have seen (and written) something like this once.
- Filtering out deleted objects in containers isn't handled, when listing local scripts.
- ScriptManager::run is not a good place to set local variables, because it is not guaranteed that all scripts will be run through this function. It is also not a good place, because this does not cover access to local variables from other scripts.

Overall a better approach would have been to do it in two separate steps (each with separate pull request and testing):
1. support for scripts of objects in containers
2. support for special local variables

These are two separate issues (I think we miss an entry for 1. on the tracker) and considering their complexity they should have been handled separately.

**Comment by wheybags** [comment]
Setting the cell field allows the object to be removed when changing cell by the current existing mechanism, which finds all object in that cell and removes them.
Since there is no other reference to that Ptr object I figured it doesn't matter.

The special variables are never read by the game, only set. Th flag variables are maybe different, but I haven't started them yet.

Where else are scripts run from?
I thought they all went through ScriptManager::run

I'll try fix things up and make a new pull request, one at a time.

**Comment by zinnschlag** [comment]
> Since there is no other reference to that Ptr object I figured it doesn't matter.

The basic assumption here has always been that a Ptr object is either in a cell or in a container (probably should have documented that more clearly, but have a look at Ptr::isInCell). I don't know if there is any code that is depending on this assumption, but I wouldn't want to risk random breakage.

> The special variables are never read by the game, only set. Th flag variables are maybe different, but I haven't started them yet.

Okay. I did a bit more research myself and it seems you are correct.

> Where else are scripts run from?
> I thought they all went through ScriptManager::run

Nope. This is not correct. Not every script has a name, so the run function would be unsuitable for these (think of commands entered on the console or dialogue scripts).

**Comment by wheybags** [comment]
Commands from the console isn't a problem, because you can't declare
variables in them, and I don't think you can use any of the special
variables in dialogue scripts. I'll look into it.

The Ptr object stored in localscripts are only ever used to access their
localvariables, so that's why I figured using the cell field would be a
cheap way to make sure they were removed on cell change.

**Comment by wheybags** [comment]
I dunno, I just can't think of any other way to remove them on cell change
that wouldn't feel like a hack.

**Comment by zinnschlag** [comment]
> Commands from the console isn't a problem, because you can't declare variables in them, and I don't think you can use any of the special variables in dialogue scripts. I'll look into it.

You can access local variables from the console (either via the x.y syntax or via implicit references). Special variables should not be forbidden in scripts. Even if that doesn't work in MW, we should make it work. Otherwise we would have to fix it later.

**Comment by wheybags** [comment]
That would work, because once the value is changed in the ref's
localvariables the value is persistent until overwritten by the script.

**Pull request closed without merging**
