### PR TITLE
Testbranch

### PR DESCRIPTION
**Pull request by ghost**
Submitting the DrawState task.

### CODE REVIEW

**Comment by zinnschlag** [comment]
Almost. Some parts of our naming schemes are a bit inconsistent and confusing (I blame Bethesda for this particular case). The player is actually a NPC too. Therefore adding a draw state to MWWorld::Player is redundant. Please remove it and use the state in the matching MW-reference instead (the one in the NpcState which is part of the ref data via the custom data struct).

**Comment by ghost** [comment]
I removed mDrawState from player,but can't find a way how to access NpcStats.
I found MWClass::getNpcStats but player has ESM::Class.
What should I do?

**Comment by zinnschlag** [comment]
There is a lot of documentation about this on the wiki (including a link to doxygen generated code documentation). The classes that are of interest to you are MWWorld::Ptr and as you already found out MWWorld::Class. If you look at the interface of class, you should see how you can access it via a Ptr (there are also plenty of examples how to do that in the code). And the Ptr instance you can get from MWWorld::Player.

**Comment by ghost** [comment]
I feel tired from sitting by the PC whole day.I will look at that and item stacking tomorrow.

**Pull request merged**
