### PR TITLE
Fixing Issue 840, fixing compile issues on Windows/Visual Studio 2012

### PR DESCRIPTION
**Pull request by Tatrabbit**
I hope this is good! If something's wrong with it, tell me what it is and I'll fix it up.

In addition to Issue 840, there are commits allowing it to compile on my machine, some of which were done when I was just setting up my environment. As all but one weren't described in detail on the forum or discussed with anyone there, I'll go into what I did and why, in detail, to make your job easier.

I'm a little bit unsure of adjusterwidget.cpp, please make sure I did the right thing there before you pull. However, what I believe was happening was this: native() returns a string native to the machine, which on mine was a L"unicode" string. It wouldn't concatenate with the regular multibyte string. Also, I believe that fromUtf8 expects only a  multibyte string.

I had to add a WinMain to the launcher. It simply refused to build with main() by compiling it for SubSystem:Console, Qt disagreed with that (I don't know why it would though) and this seemed like the best way to avoid the problem in the future.

In worldimp.cpp, movePlayerRecord was being called before setUp(). setUp() will populate shared records from the existing static records, and movePlayerRecord will delete the player's shared record. This would cause a runtime failure on my machine the moment movePlayerRecord tried to look for a shared record where none existed. It was a choice between swapping them here or adding a check deeper in. I swapped them.

### CODE REVIEW

**Comment by greye** [comment]
Haven't you tried /ENTRY flag to use main() by default in VS?

**Comment by Tatrabbit** [comment]
Well, to be honest, I didn't. I probably should have tried that. Do you want me to try again to get it to work with main()? I'd have to do that tomorrow, I'm getting tired and it's already past my bedtime. I'm just too persistent with these things :P

**Comment by greye** [comment]
I'm not going to force you to do that now or later, it just don't make sense for me to write code when things are about ide setup.

**Comment by Tatrabbit** [comment]
To be perfectly frank, it makes no sense to me either. It's a workaround and I know it. I got my OpenMW environment set up when I was a bit tired, and that's just one of those "hacky compilation fixes". I decided I shouldn't clean it up along with the blatant no-no's, because I thought it might be useful to the project, to avoid setting up the IDE in the future. If I manage to use the /ENTRY flag without any effort, I'll gleefully remove it. I don't like conditional compiling, and I'm not a huge fan of WinMain, either. It's just putting the whole program one stack frame deeper.

**Comment by zinnschlag** [comment]
I'll put the merge on hold, until the conditional compilation issue is resolved. This kind of stuff really should be addressed on the build system level.

**Comment by Tatrabbit** [comment]
Alright, sure. This was exactly why I was waiting for you before starting another. And welcome back, Zini, pleased to meet you!

**Comment by Tatrabbit** [comment]
I've removed the conditional compilation stuff. mwlauncher still refuses to build properly on my system without main being declared as __dllimport. SDL seems to #define main SDL_main, so /ENTRY main doesn't work of course. /ENTRY SDL_main works as you'd expect, except that argc and argv are undefined in the call, likely due to the way silly Windows handles things. WinMain worked the way it does because of the macros __argc and __argv I think they're called. But, that doesn't affect this bug. That can always go in another bug if it's a problem. OpenMW itself builds for me, and that's enough to get me started.

And, Zini, I'd like to apologize if I've done so much wrong. I'll make sure things are cleaner next time, I honestly want to help your project thrive.

**Comment by zinnschlag** [comment]
> I've removed the conditional compilation stuff. mwlauncher still refuses to build properly on my system without main being declared as __dllimport. SDL seems to #define main SDL_main, so /ENTRY main doesn't work of course.

SDL is also used in OpenMW itself, so I do not see why you would experience a different outcome there.

> And, Zini, I'd like to apologize if I've done so much wrong. I'll make sure things are cleaner next time, I honestly want to help your project thrive.

No problem. Except for putting two separate issues into the same pull request, nothing major went wrong. That pull requests are needing a few revisions is quite normal.

**Pull request merged**
