### PR TITLE
Ogre plugin search fix

### PR DESCRIPTION
**Pull request by mike-sc**
If debug version of openmw can't find OGRE debug version it will try to use release version.

### CODE REVIEW

**Comment by zinnschlag** [comment]
Is that really a good idea? At least on some platforms you can't mix debug and release.

**Comment by mike-sc** [comment]
Witch ones? There are oplatforms with different abi for debug and release? Or is there other problem?

I added it because seting up developement enviroment using openmw wiki gave release version of ogre3d on kubuntu 12.04 64bit. And by default kdevelop compiles debug version. I couldn't start openmw and now it works. I didn't want to debug ogre but i wanted to put traps in openmw code.

**Comment by ghost** [comment]
I don't see any problems mixing release ogre libraries/plugins with a debug executable. If that's a problem on a different platform, why should we remove the possibility to do so? It's a neat feature because building Ogre takes some time; also Ogre renders much slower in Debug mode.

**Comment by zinnschlag** [comment]
Windows? Mixing debug and release builds is usually a cause of trouble there. Or at least it was when I had last worked on Windows (several years ago now). Do we have any information if there are problems on Windows? If yes, we could still use the mix option on other systems, but the cmake script should disable it for Windows.

**Comment by nikolaykasyanov** [comment]
As far as I remember using main Ogre library with debug plugins (or vice-versa) caused problems earlier, but that's not the case here.

**Comment by zinnschlag** [comment]
You are talking for OS X, right?

**Comment by nikolaykasyanov** [comment]
Nope, I'm talking about some scrawl's fix to this problem, AFAIK he's encountered it on Linux

**Comment by mike-sc** [comment]
So what is the outcome?

I found some posts about mixing debug and release under windows. Basicly if you are using MFC you will be screwed. Debug and release use different runtime library and if you alocate memmory in one build and release in other you can have troubles. Is this our case?

**Comment by zinnschlag** [comment]
I don't know. I am not a Windows developer anymore. Needs to be verified by one. If you can't do it yourself, you could try to get help on our forum.

**Pull request closed without merging**
