### PR TITLE
MwGui Cleanup mostly done

### PR DESCRIPTION
**Pull request by thespacepanda**
Renamed files in MwGui to comply with naming conventions
Changed all calls to mWindowManager to use MwBase::Environment::get().getWindowManager() instead of MwBase::WindowManager

I've done everything except taking care of the imports and the using namespace problems. I just wanted you all to see what I have done so far, I should have the rest done either tomorrow or by the end of the week.

### CODE REVIEW

**Comment by zinnschlag** [comment]
The window manager is still passed into the constructors of the GUI classes.

**Comment by thespacepanda** [comment]
Okay thank you Zinni. I will get to work on that. Are there any other issues with it so far (such as formatting)?

**Comment by zinnschlag** [comment]
From what I see you did not renamed the incorrectly named files, but instead added files with the correct name. That means the old files still exist. The rest looks okay.

**Comment by thespacepanda** [comment]
I'm pretty sure these commits fixed the WindowManager call issue and I've started working on the include statement cleanup. I removed everything I possibly could from all the header files, and I plan on doing the same with the source files tomorrow. Is there any easy way to tell if an include could be substituted by a forward declaration? I know you can only do this if only a reference to an object is used.

**Comment by zinnschlag** [comment]
Currently sorting out a few merge issues. If no further problems show up, your branch will be merged in a bit.

> I removed everything I possibly could from all the header files, and I plan on doing the same with the source files tomorrow.

Not quite. I still see a few redundant includes in headers. Please go over them again.

> Is there any easy way to tell if an include could be substituted by a forward declaration? I know you can only do this if only a reference to an object is used.

You could go for a brute force approach (try remove the include, add forward declarations as needed and see if it compiles). However that isn't entirely reliable. I guess you have no other option than actually reading the code.

**Pull request merged**
