### PR TITLE
Fixed build using CMake > 2.8.9 on OS X

### PR DESCRIPTION
**Pull request by nikolaykasyanov**

### CODE REVIEW

**Comment by zinnschlag** [comment]
Do we need that for the current release? If not, I would prefer to not having last minute changes to the release branch.

**Comment by nikolaykasyanov** [comment]
I can of course fallback to 2.8.9 on my build machine.
But this change is very local and would only affect OS X anyway.

**Comment by zinnschlag** [comment]
Okay then. Will merge in a bit.

**Comment by nikolaykasyanov** [comment]
Thanks!

**Pull request merged**
