### PR TITLE
Nif loader: workaround for missed textures in BB/BH

### PR DESCRIPTION
**Pull request by sergey-shambir**
Works for Better Bodies / Better Heads addons.

https://bugs.openmw.org/issues/572

### CODE REVIEW

**Comment by sergey-shambir** [comment]
If needed, i'll recreate pull request after "Nif parse cleanup" will be merged.

**Comment by kcat** [comment]
This looks like a really messy way to go about it. It would be better to simply check if the texture exists, and if not, check if the path starts with "textures\" (in a case-insensitive manner) and remove it if so.

Ideally, I think we should be making a separate Textures resource group, which is using the "textures\" path from the base resource locations. Then we'd simply not prepend "textures\" to the filename, and it'll be found in either the Textures group (if there's no starting "textures\"), or the General group (if there is).

**Comment by sergey-shambir** [comment]
Yes, this approach will fix BB - but not Better Heads. For BH, st->filename can be "textures\BH\BH_DON_DE_M_head02.dds", where actual texture is "textures\BH_DON_DE_M_head02.dds"

**Comment by zinnschlag** [comment]
That is bad. A texture specific fix will not serve here, since this potentially can also happen with other types of resources (I presume). We probably will have to make do with a messy solution. But considering that in the past file finding has been a major performance bottleneck, we should pay special attention here. I would like at least one performance test (once without this change and once with it), to see if we have a problem here.

**Comment by sergey-shambir** [comment]
Engine::prepareEngine perfomance measurement results: http://paste.ubuntu.com/5565704/
Marked Engine::prepareEngine method (look for "timer.mark("): http://paste.ubuntu.com/5565671/

I see no perfomance regression. Although, we can speedup code a bit: as Chris said, add "textures\" prefix only if it doesn't exists.

**Pull request merged**
