### PR TITLE
Replaced FindOGRE.cmake, this one looks for debug libraries too

### PR DESCRIPTION
**Pull request by pvdk**
This seems to work so I suggest we use it. The files are from the Ogre repository.

### CODE REVIEW

**Comment by zinnschlag** [comment]
Makes OpenMW crash at runtime:

ERROR: OGRE EXCEPTION(7:InternalErrorException): Could not load dynamic library ./RenderSystem_GL.  System Error: ./RenderSystem_GL.so: cannot open shared object file: No such file or directory in DynLib::load at /home/marc/Tools/ogre-1-7-1/OgreMain/src/OgreDynLib.cpp (line 91)

**Comment by pvdk** [comment]
Yeah I had that problem too at the first run, running CMake a second time
seems to fix it. It's ${OGRE_PLUGIN_DIR} not being set.

On 1 February 2012 10:29, Marc Zinnschlag <
reply@reply.github.com

**Comment by zinnschlag** [comment]
Strange. Can you please check it again on a clean directory (one where cmake hasn't run before)?

**Comment by pvdk** [comment]
Works in a clean directory, strange indeed.

On 2 February 2012 09:26, Marc Zinnschlag <
reply@reply.github.com

**Comment by zinnschlag** [comment]
Running cmake a second time does not fix the problem for me. Less than enthusiastic about it. Any idea how to avoid this problem?

**Comment by pvdk** [comment]
Finally got around looking into this problem. Seems the new macro uses the variables OGRE_PLUGIN_DIR_REL and OGRE_PLUGIN_DIR_DBG. I changed some things, it should be working now.

**Comment by zinnschlag** [comment]
Okay. Will test as soon as possible. Which unfortunately might take as long as up to Friday (really busy right now).

**Comment by zinnschlag** [comment]
Works nicely.

Merged into next instead of master.

**Pull request closed without merging**
