### PR TITLE
Doxygen cleanup

### PR DESCRIPTION
**Pull request by bhoessen**
https://bugs.openmw.org/issues/164

I've made some corrections with the namespaces that were different between the declaration and implementation, added empty documentation for the missing parameters and corrected some typing mistake

### CODE REVIEW

**Comment by zinnschlag** [comment]
Looks mostly good. But do we really have to pollute the source with empty param lines? Have you search the Doxygen documentation for ways to simply disable this type of warnings?

**Comment by bhoessen** [comment]
I've found this:

> If WARN_IF_DOC_ERROR is set to YES, doxygen will generate warnings for potential errors in the documentation, such as not documenting some parameters in a documented function, or documenting parameters that don't exist or using markup commands wrongly. 

The problem is, if we set it to false, we won't have other warnings (wrong documentation).
If we don't want warning and still have proper documentation what could be done is to modify WARN_IF_DOC_ERROR to generate all warnings, take care of those we are interested in, then set WARN_IF_DOC_ERROR back to NO.

**Comment by zinnschlag** [comment]
Well, that sucks. I do not see the point of temporarily disabling warnings, if it does not help to distinguish between actual problems and spam. I suggest you remove the spam (the empty param lines) and then I merge. We will just have to live with those warnings.

**Comment by zinnschlag** [comment]
cleaning up old unfinished pull requests.

**Pull request closed without merging**
