### PR TITLE
Unity build option

### PR DESCRIPTION
**Pull request by ghost**
Adds a unity build option (disabled by default). If enabled, each component and each MW-subsystem only use a single compilation unit.

Build time test (single core, only openmw was built, no launcher/opencs/esmtool...)
Default - 17:29
Unity - 5:15

I didn't touch launcher or OpenCS, but it could be enabled there too.

### CODE REVIEW

**Comment by zinnschlag** [comment]
That doesn't build for me (https://gist.github.com/zinnschlag/9595569) and apparently not for Travis either. Does sound like a bad idea anyway. From what I see you are merging cpp files into a single translation unit via includes. That can break things (think of anonymous namespaces).

**Comment by nikolaykasyanov** [comment]
How would that affect line numbers in stack traces?

**Comment by ghost** [comment]
Fixed.

Don't feel like starting a discussion on pros and cons of unity builds. You can already find plenty of resources on the internet for that.

Note that I am not advocating using this option for normal development (that makes no sense anyway). But it's undoubtedly useful for getting a quick build of a completely different branch, eg for fast bisecting.

> How would that affect line numbers in stack traces?

It won't.

Yeah, I had to change some anonymous namespaces (see the diff). Nothing too bad actually. Most of these were actually indicators of code quality issues (duplicated functions), so that is kinda a good thing. It also found missing include guards, ambiguous namespaces and some functions polluting the global namespace.

**Comment by nikolaykasyanov** [comment]
@scrawl :thumbsup:

**Comment by zinnschlag** [comment]
Okay, I merge it. Don't feel like getting into a discussion either. However if there happened to be a valid change to the code base that breaks unity builds (not like duplicated function in anonymous namespaces or something like that), then it is broken. We will not put in place additional rules regarding C++ usage to keep unity builds functional.

**Comment by nikolaykasyanov** [comment]
I'm having compile & link errors on OS X with unity build enabled:

compile error (OpenMW):

```
[ 21%] Building CXX object apps/openmw/CMakeFiles/openmw.dir/ub_mwsound.cpp.o
In file included from /Users/corristo/src/OpenMW/debug/apps/openmw/ub_mwrender.cpp:21:
/Users/corristo/src/OpenMW/openmw/apps/openmw/mwrender/terrainstorage.cpp:400:13: error:
      no type named 'AVPixelFormat' in namespace 'Ogre'; did you mean simply
      'AVPixelFormat'?
            Ogre::PixelFormat format = pack ? Ogre::PF_A8B8G8R8 : Ogre::PF_A8;
            ^~~~~~~~~~~~~~~~~
            AVPixelFormat
```

linker error (both OpenCS & Launcher):

```
Linking CXX executable ../../OpenCS.app/Contents/MacOS/OpenCS
Undefined symbols for architecture x86_64:
  "sh::LinkedValue::LinkedValue(std::string const&)", referenced from:
      sh::makeProperty(std::string const&) in libcomponents.a(ub_nifogre.cpp.o)
      sh::makeProperty(std::string const&) in libcomponents.a(ub_nifoverrides.cpp.o)
...
```

Any thoughts?

**Comment by ghost** [comment]
This fixes the link errors for me: http://pastebin.com/64E0Xq8p

But I don't understand why. Launcher and OpenCS do not use shiny at all (on master branch, anyway). Some of the components do use it, but none of these are used by launcher/OpenCS. 

I don't get the PixelFormat error, you'll need to investigate that on your own.

**Pull request merged**
