### PR TITLE
Fix for missing dependency in usersettingsdialog.hpp

### PR DESCRIPTION
**Pull request by joelgraff**
Added missing #include.

### CODE REVIEW

**Comment by zinnschlag** [comment]
Something is not right here, because the file you are fixing doesn't even exist anymore.

**Comment by joelgraff** [comment]
I just checked your master branch and it's there under view/settings/usersettingsdialog.hpp.  I see a few days ago, Glorf made a fix to it...

**Comment by zinnschlag** [comment]
I'll just fix that manually. But there is definitely something broken in your master branch.

**Comment by joelgraff** [comment]
Yeah, I'm not sure what's happened.  My local user settings branch has no
usersettingsdialog.hpp, but my local master does.  On github, it's just the
reverse.  Don't know what I did.

**Pull request closed without merging**
