### PR TITLE
Bug#1276

### PR DESCRIPTION
**Pull request by sirherrbatka**
i hope that this works this way

### CODE REVIEW

**Comment by zinnschlag** [comment]
Too much signals again. You are still using signals in the downward direction while basic function calls would do the job much better.
Also, you seem to be shadowing the createFilterRequest here. Unless there is some MOC-magic going on here that I am not aware of (and certainly not happy about), this looks wrong.
To be honest, I don't understand this fix. Why do the types cell and region require a special case implementation?

**Comment by sirherrbatka** [comment]
it is not region/cell that needs special treatment, but the scene widget.

Currently, we take string column for the filter from the table. Hovewer, scene 
widget lacks table, so it needs to tell that it is !string(id, whatever) other 
way.

At the moment i have other idea for more general solution so hang on…

**Comment by zinnschlag** [comment]
But this bug does not involve the scene widget. Its about the cell table and the region table. We will deal with the scene filter separately once the scene implementation is a bit more advanced.

**Comment by sirherrbatka** [comment]
oh God. I don't know what to say: i simply missreaded the description. Sorry… 
:(

**Comment by zinnschlag** [comment]
NP. The wording was probably a bit ambiguous.

**Pull request closed without merging**
