### PR TITLE
Update weapon icon in HUD when save is loaded.

### PR DESCRIPTION
**Pull request by rohit-n**
Currently the weapon icon is "Unarmed" no matter what weapon is equipped at save load.

### CODE REVIEW

**Comment by ghost** [comment]
Good catch. But there is a problem with that code: if the player doesn't have anything in that slot, it will dereference the end() iterator.

Add a check like:
if (it == invStore.end())
  setSelectedWeapon(MWWorld::Ptr());

Also, don't we need to do the same for selected spell/enchanted item? Although bought spells aren't saved yet.

**Comment by rohit-n** [comment]
I'll look in to both of those issues.

**Comment by rohit-n** [comment]
Setting the weapon to MWWorld::Ptr() crashed the game if the player was unarmed, so I merely had it set only when not unarmed. I will work on setting spell icons. Should that be in a separate commit?

**Comment by ghost** [comment]
Ah, my bad. I see why that crashes. You need to use the unset variants instead (ie unsetSelectedWeapon).

> Should that be in a separate commit?

It doesn't matter.

**Comment by rohit-n** [comment]
Whoops, I meant pull request in my last question.

I think I would be better off putting spell icon loading in a separate pull request, since it appears the player's selected spell isn't saved like their equipped weapon is, so I can't just look it up. Indeed, pure "spells" (not from a scroll or power) don't appear to be saved at all.

For now, I think I'll leave this pull request as it is, unless there are more problems found with these commits.

**Pull request merged**
