### PR TITLE
Add checkbox into open file dialog.

### PR DESCRIPTION
**Pull request by mike-sc**

### CODE REVIEW

**Comment by zinnschlag** [comment]
Sorry, I do not understand the purpose of this change.

**Comment by mike-sc** [comment]
Hmm It was baset on startup branch. Was it scraped? This pull adds checked items into opendialog.
screen

**Comment by zinnschlag** [comment]
Two points:
1. Your branch changes the UI rather substantially (have a look at what we have in master). I am not sure how you got to that.
2. The original question stands. What is that good for? We don't need an UI to select a file.

**Comment by mike-sc** [comment]
1. It's baset on stuff from here https://github.com/zinnschlag/openmw/pull/544. That went into branch startup. I can't find it now.
2. It's for editor. To edit file you have to open it. Probably selecting other files to have "base" content. Clicking "save" should store changes done in editor in opened file.

**Comment by zinnschlag** [comment]
1. That pull request was merged. But your code still has a notably different UI (namely no separate section for ESM files). I do not know where this is coming from, but it is not a change we want (at least not in this way).
2. Still not entirely sure, if I understand you correctly. But under the assumption that what I think you mean is what you actually mean: The open file dialogue is the same dialogue we use ESX selection in the launcher. There is no need to select a specific file for editing, because the edited ESX file will always be the last in the list of selected ESX files.

**Comment by mike-sc** [comment]
1. I was thinking that "new UI" was in https://github.com/zinnschlag/openmw/pull/544 but it's not. My mistake. IMO this is better.
2. Open file dialogue uses the same widget as launcher. https://github.com/zinnschlag/openmw/pull/544 moved this widget to components. This pull:
   - merges two lists into one
   - adds "selected file" combobox

**Comment by zinnschlag** [comment]
> ```
> merges two lists into one
> adds "selected file" combobox
> ```

We need neither of that.

**Pull request closed without merging**
