### PR TITLE
throw an exception if default value for a setting is not found

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by zinnschlag** [comment]
I am not convinced that this is a good idea. We normally don't quit, if an exception is thrown (except during initialization), so throwing an exception here would leave some functions unnecessarily in a half executed state. Maybe just write an error message to std::cout for now? And maybe do a sanity check on the values you are getting from the settings manager and correct them if needed?

**Comment by ghost** [comment]
I have a feeling that only a cout message wouldn't bring enough attention. How about cout message and abort() ?

> And maybe do a sanity check on the values you are getting from the settings manager and correct them if needed?

That would mean using hardcoded default settings (or at least hardcoded alternatives) for each setting, which defeats the purpose of the settings-default file.

**Comment by zinnschlag** [comment]
Difficult. Should we really make a missing setting a reason for terminating OpenMW? Sounds harsh. If you really want to do that, you should make sure all settings are checked during startup. A crash in the middle of playing would be bad.

> How about cout message and abort() ?

If you really want to do it that way, use an assert please.

**Comment by ghost** [comment]
> Difficult. Should we really make a missing setting a reason for terminating OpenMW

"missing setting" means that there is no reasonable value to use. Which can lead to unexpected behaviour. For example not being able to move the mouse (as it happened here: http://forum.openmw.org/viewtopic.php?f=6&t=1021 ). So yes, I think that terminating would be a better solution. 

> A crash in the middle of playing would be bad.

Converting the settings from strings can be costly, so I read all of them during startup (or when they changed). If something is missing, it will crash at startup.

I don't want to use assert because I know of developers that always build in release mode.

**Comment by zinnschlag** [comment]
> "missing setting" means that there is no reasonable value to use. Which can lead to unexpected behaviour

That is why I asked for a sanity check.

> I don't want to use assert because I know of developers that always build in release mode.

Depends on your definition of release mode. Does anyone really thinks that it is a good idea to disable asserts for release builds these days? Anyway, I will just merge the original request. If all settings are read during startup, we can get away with throwing an exception. Still don't like it, but not worth wasting more time on it.

**Pull request merged**
