### PR TITLE
Add more detail to ESMTool record dumping.

### PR DESCRIPTION
**Pull request by cfcohen**
This is my first time using GIT hub, and my first attempt to commit to OpenMW.  If these changes are acceptable, I have more edits in apps/esmtool.

### CODE REVIEW

**Comment by zinnschlag** [comment]
Looks mostly okay. But you have mixed tabs and spaces, which we don't want (see our developer documentation on the wiki). Breaks code layout on github and on some editors (definitely on mine). Please remove the tabs. Also, I suggest you enhance the --help documentation for the type switch slightly. It isn't entirely obvious what kind of identifier is expected here. Adding something like "(4 character identifier)" should fix that problem for now (in the long run we probably should provide a more extensive help function; maybe even a separate help mode like in git).
Once these issues have been addressed your branch can be merged (please add another comment to this pull request, so that it shows up in my news feed again).

For future improvements, I suggest you consider splitting up esmtool.cpp (move mode functions into serparate files). Its getting a little bit bulky. Also, the switches should be improved. Your type switch might be useful for other modes than dump and if it is not, the --help documentation should state in which modes it works.

**Comment by cfcohen** [comment]
Hello Zini,

Sorry about the tabs.   I knew about that rule, and assumed that emacs had done the right thing.  I guess not.

I'm leaving for Puerto Rico for 10 days on Friday, so if I disappear in the middle of a conversation, I'm not ignoring you.  I'll try to address your issues and add more of my code before I go.  

## Cory

**Comment by cfcohen** [comment]
If I'm not using GIT properly, please let me know.  I'm just winging it. :-) I did not attempt to split esmtool.cpp.  Perhaps you meant to suggest splitting record.cpp, which is more than twice as large (although conceptually simpler)?  Do you have rules of thumb for when you like to see file splits? 

My next intended commit is a bunch of functions for converting numeric type values and flag bits into human-readable strings.   These are also quite sizable (more than 1000 lines of simple code) which I currently have in a new file in my out-of-sync copy.  A file split by record-type like in the ESM component may be warranted, but some of the functions might not be horribly out-of-place back in the ESM component.  May I suggest just getting them into a commit in ESMTool, and letting you comment on them there before trying to decide the correct file divisions?

The flag bit functions should bring me closer to some real contributions, since I've determined the meanings of some bits not previously documented, found some incorrect bits, etc.  Those will eventually need to get merged back into the ESM component.

In this commit, I frequently have to cast chars as ints for some fields.  If they were declared as uint8_t back in ESM component, that would probably be cleaner.  Also testing for (type==0xFF) would provide double the future expansion capability of testing (type==-1) where type code is currently signed and used as an index into an array of values.  I have no intention of acting on this one until someone weighs in on it.

My private copy has switched to a model in which multiple files are loaded in their entirety before dumping any of the records.  This allows better display, especially when trying to dump INFOs for specific dialogs, magic effect names, etc. How should I coordinate with you or Greye on an architectural change like that?

This change is also required for another issue I would like guidance on.  It's my position that GMSTs provide internationalization of strings like skill names, and that hard-coding the English versions in ESMTool is wrong, but without a complete load (and possibly some basic merging) before dumping records, it's not really convenient to use them.  Is there a recommended architecture for doing this?  Another problem is that Morrowind is not consistent in this regard. By my count, nine of the type fields have appropriate GMSTs while ten more do not.  Long term, I believe that OpenMW should use a consistent internationalization method, and GMSTs seem to be one choice.  Any opinions?

**Comment by zinnschlag** [comment]
> If I'm not using GIT properly, please let me know. I'm just winging it.

Okay-ish. You are supposed to use feature branches instead of main, but that is not that important at this point. I still advice you to read up on git branches, because they are an extremly useful feature. You will probably smack yourself later for not having started to use them earlier.

> I did not attempt to split esmtool.cpp. Perhaps you meant to suggest splitting record.cpp, which is more than twice as large (although conceptually simpler)? Do you have rules of thumb for when you like to see file splits? 

I meant esmtool.cpp. And you explained yourself already, why I did not meant record.cpp ("conceptually simpler"). record.cpp does one thing, namely implementing a record wrapper. esmtool.cpp on the other hand does many things (and that is probably going to get worse in the future). Anyway, no hurry.

> My next intended commit is a bunch of functions for converting numeric type values and flag bits into human-readable strings. These are also quite sizable (more than 1000 lines of simple code) which I currently have in a new file in my out-of-sync copy. A file split by record-type like in the ESM component may be warranted, but some of the functions might not be horribly out-of-place back in the ESM component. May I suggest just getting them into a commit in ESMTool, and letting you comment on them there before trying to decide the correct file divisions?

Still somewhat skeptical on this, but go ahead.

> The flag bit functions should bring me closer to some real contributions, since I've determined the meanings of some bits not previously documented, found some incorrect bits, etc. Those will eventually need to get merged back into the ESM component.

These things should be discussed with our research team on the forum.

> In this commit, I frequently have to cast chars as ints for some fields. If they were declared as uint8_t back in ESM component, that would probably be cleaner. Also testing for (type==0xFF) would provide double the future expansion capability of testing (type==-1) where type code is currently signed and used as an index into an array of values. I have no intention of acting on this one until someone weighs in on it.

Not entirely sure, if changing the type would help with avoiding the casting. Doesn't the overloaded version of << for unsigned char works the same as for signed char and char? Would have to look that up.
There are some suboptimal types in the ESM record structs, however I do not agree with changing anything to unsigned types, when we have negative out of band values. Doesn't really improve anything and makes the out of band value less explicit.

> My private copy has switched to a model in which multiple files are loaded in their entirety before dumping any of the records. This allows better display, especially when trying to dump INFOs for specific dialogs, magic effect names, etc. How should I coordinate with you or Greye on an architectural change like that?

As I wrote before multiple ESX loading is full of special cases. Trying to handle them at this point is probably not a good idea. This feature should be implemented properly in OpenMW first, before we bother with it in the ESMTool or the editor. This will make sure we know that we have it implemented correctly.

> This change is also required for another issue I would like guidance on. It's my position that GMSTs provide internationalization of strings like skill names, and that hard-coding the English versions in ESMTool is wrong, but without a complete load (and possibly some basic merging) before dumping records, it's not really convenient to use them. Is there a recommended architecture for doing this? Another problem is that Morrowind is not consistent in this regard. By my count, nine of the type fields have appropriate GMSTs while ten more do not. Long term, I believe that OpenMW should use a consistent internationalization method, and GMSTs seem to be one choice. Any opinions?

I do not agree that the ESMTool should be localized at all. This is an developer tool after all; not meant for the end user. Consider this scenario. An English-speaking developer is inspecting a localised plugin. If everything is localised, he won't be able to do so.
In general we should keep up a strict separation between the internal name (usually in English) and the user visible name (localised). Unfortunately MW fails in this regard in several places. Needs to be fixed, but that is a post-1.0 task and we shouldn't waste any resources on it now.

btw. I saw you increased the ESMTool version number. This version number doesn't make a lot of sense. It is inconsistent with everything else. I suggest that the ESMTool version number should always be the same as the OpenMW version number, since these two applications need to be developed in sync as the ESX format evolves. The cmake script already defines appropriate version constants that you can use (see apps/openmw/main.cpp).

**Pull request merged**
