### PR TITLE
Crash catcher

### PR DESCRIPTION
**Pull request by ghost**
I've had it happen for too often that OpenMW crashed randomly and I wasn't able to reproduce it after re-running in a debugger.
This catches fatal signals on unix and then logs diagnostic information by attaching gdb.

### CODE REVIEW

**Comment by ghost** [comment]
Travis build revealed some missing include, i'll fix this soon.

**Comment by zinnschlag** [comment]
Okay, waiting for the fix.

**Comment by ghost** [comment]
Right, looks like that did it.

**Comment by zinnschlag** [comment]
That change turns the OpenMW process into a zombie on my system (after a regular shutdown).

**Comment by ghost** [comment]
That was working before... looks like the gdb detection hack caused it. Replaced it with a different one. Should be fixed.

**Pull request merged**
