### PR TITLE
Issue #284: Book's text misalignment

### PR DESCRIPTION
**Pull request by lgromanowski**
Changed size of book widget (it looks more or less like MW one),
corrected text placement. Book pictures are placed on new pages.

Signed-off-by: Lukasz Gromanowski lgromanowski@gmail.com

### CODE REVIEW

**Comment by ghost** [comment]
There's a problem with the firnament book in census office. I get:
Error in framelistener: BookTextParser Error: Tag is not terminated
And it only renders up to the first image.

**Comment by lgromanowski** [comment]
Hmm, strange, because it works for me. I think it could be related with different MW language version. I will investigate it and try to fix.

**Comment by lgromanowski** [comment]
Would you change throws in formatting.cpp to:

``` c++
                    {
                        throw std::runtime_error(
                            std::string("BookTextParser ")
                            + std::string(__FUNCTION__)
                            + std::string(" Error: Tag is not terminated! Text: ") + text);
                    }
```

and send me an output of it, please?

**Comment by zinnschlag** [comment]
Did we ever get this resolved?

**Comment by lgromanowski** [comment]
Yes. I don't have internet access right now, so it won't be solved in this week. I will try do it as soon as possible.

**Comment by zinnschlag** [comment]
cleaning up old unfinished pull requests.

**Pull request closed without merging**
