### PR TITLE
Bunch of Mac fixes

### PR DESCRIPTION
**Pull request by nikolaykasyanov**
Fixes https://bugs.openmw.org/issues/1045 & https://bugs.openmw.org/issues/1041

@kcat could you please review this commit https://github.com/corristo/openmw/commit/fc21dd1f3afc44ba13a3c868690964b6b636daf9 ?

### CODE REVIEW

**Comment by nikolaykasyanov** [comment]
I'll look into it in a week. Currently on the go. Happy new year!

**Comment by nikolaykasyanov** [comment]
@zinnschlag I'll be able to complete this pull request at 10-11th January, still on the go without laptop, sorry about that.

**Comment by nikolaykasyanov** [comment]
@zinnschlag please merge this in 0.28 branch

**Comment by zinnschlag** [comment]
Merged.

**Pull request closed without merging**
