### PR TITLE
Bug422

### PR DESCRIPTION
**Pull request by Pi03k**

### CODE REVIEW

**Comment by zinnschlag** [comment]
Neither approach is good enough. We really need two separate data structures. A Probe struct and a Repair struct. Don't get hung up on the fact that they are identical, except for one swapped field. That is true now, but there is no guarantee that this will still be true in the future.

**Comment by zinnschlag** [comment]
Just noticed that I proposed the use of templates myself in the issue description. While it was certainly not meant that way, this comment is misleading and not well thought out. Sorry for that.

**Comment by dougmencken** [comment]
> A Probe struct and a Repair struct.

And how about Lockpick? You even made it the top-level one!!!

Also see https://github.com/dougmencken/openmw/commit/3d8a94d3ceba5675c891066b44b3738b8063ca28

**Comment by zinnschlag** [comment]
Right. Forgot about the lockpicks. If we want to go for a clean solution, these all should be separated structs in separated files. No common base struct. That was pretty much a quick and dirty workaround anyway (for a design that was even worse).

**Comment by dougmencken** [comment]
> No common base struct.

Why? Think about abstraction.

They're all pretty happy within loadtools now :)

**Comment by zinnschlag** [comment]
That these 3 data types are currently mostly identical is pure randomness. If you have two unrelated classes, that happen to have the same data structures, you don't factor out a common base class. On top of that we have opted (admittedly mostly by accident) for a flat representation without any inheritance structure. The current Tool implementation is inconsistent with everything else.

**Comment by dougmencken** [comment]
Well, I see that they share absolutely common data. So it is obvious to work with them using a common class. It looks like just occasional mistake from original developers to exchange order of two fields for REPA. Also, unions are very powerful :)

UPD: If you do need, you can always use inherited Lockpic, Probe and Repair classes (structs) as well. That's why OOP is cool. Order of records in ESM file doesn't have anything with the need to handle identical data spearately.

Record: LOCK 'pick_journeyman_01'
  Name: Journeyman's Lockpick
  Model: m\Pick_Journeyman_01.NIF
  Icon: m\Tx_pick_J_01.tga
  Type: 0
  Weight: 0.25
  Value: 50
  Quality: 1.1
  Uses: 25

Record: PROB 'probe_apprentice_01'
  Name: Apprentice's Probe
  Model: m\Probe_Apprentice_01.NIF
  Icon: m\Tx_probe_A_01.tga
  Type: 1
  Weight: 1
  Value: 10
  Quality: 0.5
  Uses: 25

Record: REPA 'repair_journeyman_01'
  Name: Journeyman's Armorer's Hammer
  Model: m\Repair_Journeyman_01.NIF
  Icon: m\Tx_repair_J_01.tga
  Type: 2
  Weight: 3
  Value: 20
  Quality: 1
  Uses: 20

By the way, I fixed some mistakes I made in my commit. Here's my updated commit.
https://github.com/dougmencken/openmw/commit/7fd665d1e3bdaeff97239a90a23228be6652c7d3

**Comment by zinnschlag** [comment]
The esm record part is a low level implementation that works with dumb structs. That is not necessarily the best design, but that's what we inherited from the original OpenMW developer and completely replacing it now wouldn't be worth the effort. To be consistent we should avoid inheritance complete. It does not serve any purpose here anyway, except saving a bit of typing. btw. the Type enum also neesd to go.

**Comment by dougmencken** [comment]
Okay. Then my branch is my branch :)
I don't know any "original OpenMW developer" and his thoughts, but I have freedom one to modify the code as I want and freedom three to share the modified code.
See you ;)
UPD: I do really think about forking OpenMW and name it PlayMW. PlayMW will work on any hardware (not only x86).

**Comment by wheybags** [comment]
Ah don't be like that.
It is more beneficial to everyone if we have one project.
Besides, zinnschlag has a point, it might be nice to use inheritance etc for the low level ems classes, but to do it for just a few would be inconsistent, and to change all of them now would be a lot of work, to little gain.
Basically, a decision was made at some point in the past, and we're kinda stuck with it.

**Comment by nikolaykasyanov** [comment]
OpenMW not preventing anyone to build for non-x86 arch. You should ensure that all dependencies will build & work for desired architecture ;)

Anyway, making common superclass for two distinct entities only because they have slight similarity makes no sense if they wouldn't be used polymorphically (and I don't see any place where probes & repair items can be used like this). Oh wait, of course you can use them polimorphically in one place, in invernotry/container item hint to display remaining uses, but an adapter or common interface (not common superclass!) will do just fine.

**Comment by wheybags** [comment]
It is currently actually, because of endian-ness, but doug has fixed that in his branch.

**Pull request closed without merging**
