### PR TITLE
Feature #1173: Saved Game: include weather state

### PR DESCRIPTION
**Pull request by slothlife**
Removed some unused state in and changed Ogre::String to std::string in
WeatherManager.

### CODE REVIEW

**Comment by zinnschlag** [comment]
Please do not use #define except for conditional compilation (see the coding guidelines on our wiki).

Also, you shouldn't operate directly on the ESMWriter/Reader. Instead you should copy your data into a record struct (plenty examples of that available) and then read/write there. The serialisation code must be located outside of apps/openmw, so we can re-use it in other applications within in the OpenMW project (the saved game importer is an obvious example, but there may be more eventually).

**Comment by slothlife** [comment]
Well, I'd rather not directly use the strings because it's too easy to make a typo and find out only at runtime.

The coding guidelines don't permit the use of globals, so I can't just change them to that. That really only leaves initializing the values as class members, and that felt like overkill. Static class members are the best I could do, with those restrictions, but it clutters the class definition for an implementation detail.

I'd still argue that the preprocessor definitions are local to only that translation unit, and the usage of them in this case is acceptable (since they aren't doing anything tricky). That being said, this is largely a matter of consistency with the rest of the code base, so I won't fight it.

With respect to the serialization into a record struct, I just hadn't noticed that. I'll make the modification soon.

**Comment by zinnschlag** [comment]
You don't need global variables. You need constants. And they don't need to be global either since you can have them in file scope. Just create a anonymous namespace and put const char *s into it.

**Comment by slothlife** [comment]
Good point. I so rarely use anonymous namespaces, I'd forgotten about them.

**Comment by zinnschlag** [comment]
For future reference: If you add commits to an already opened pull request, please add a comment after you are done. Otherwise the changes will not show up in my github news feed. I only found your most recent commits by accident.

Testing now. btw. the handling of failed loads in ESM::WeatherState is unnecessary. Broken records will be discarded (one way or another) and the WeatherState struct is only a temporary storage anyway. It will never be used in a context where existing state can be overwritten.

**Pull request merged**
