### PR TITLE
Armor rating

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by zinnschlag** [comment]
I am not entirely sure, if this is a good idea. What about creatures? Can they have armor rating too? There is at least one magic effects that contributes to armor rating, right? In this case your code would require us to manually check if a Ptr is pointing to a NPC or a creature each time we do something with armor rating. We have MWWorld::Class to avoid that. Maybe the function to calculate armor rating should be moved there (and the respective subclasses).

**Comment by ghost** [comment]
The research page does not mention anything like that, which lead me to the assumption creatures do not have armor rating.

However I found in the MCP changelog [1]:

> - Creature armor rating. Creatures now gain AR and therefore damage reduction from shield spells. The GMST damage reduction cap does not limit creature AR.  

Should we implement that too, then?

[1] http://www.fliggerty.com/phpBB3/viewtopic.php?t=1008

**Comment by zinnschlag** [comment]
This indicates that in vanilla MW creatures do not gain AR from spells. Therefore we should not implement it. But we should be prepared to implement it after 1.0 (toggled via an additional GMST that defaults to false if not present and is set to true for newly created projects). Therefore my original comments about the implementation are still valid.

**Comment by ghost** [comment]
Ready to merge.

**Pull request merged**
