### PR TITLE
Build fixes for gentoo linux

### PR DESCRIPTION
**Pull request by edmondo**
Added some missed includes

Thanks
edmondo

### CODE REVIEW

**Comment by kcat** [comment]
Including "components/esm/loadland.hpp" in nif_file.hpp seems out of place. I can't see anything in nif_file.hpp that relies on loadland.hpp, and nif loading shouldn't rely on esm stuff anyway.

**Comment by zinnschlag** [comment]
And the same seems to be true for stdexcept and components/esm/esm_reader.hpp. 

Please revert these two changes and if there are still problems with compiling add the includes (or forward declarations) where they are actually needed.

**Comment by edmondo** [comment]
Ok, thanks for your comments.

I reverted the two changes and fixed the problems in a better way, moving the include <stdexcept> locally into esm_reader.cpp and including stdint.h into nif_file.hpp to avoid "‘uint8_t’ does not name a type" errors.

The reverts maybe pollute your history. If you don't like it, you could just cherry-pick the 3 changes or I will drop this pull request and send a new one with a clean history. Please let me know.

**Comment by ghost** [comment]
shouldn't it be cstdint, not stdint.h?

**Comment by edmondo** [comment]
Yes, I agree, cstdint seems to be more appropriate for C++ code following an actual iso standard. But...

With gcc 4.5 I get following error:

In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/4.5.4/include/g++-v4/cstdint:35:0,
                 from /var/tmp/portage/games-rpg/openmw-9999/work/openmw-9999/components/nif/nif_file.hpp:39,
                 from /var/tmp/portage/games-rpg/openmw-9999/work/openmw-9999/components/nif/nif_file.cpp:24:
/usr/lib/gcc/x86_64-pc-linux-gnu/4.5.4/include/g++-v4/bits/c++0x_warning.h:31:2: error: #error This file requires compiler and library support for the upcoming ISO C++ standard, C++0x. This support is currently experimental, and must be enabled with the -std=c++0x or -std=gnu++0x compiler options.

I would prefer to let it stdint.h. Or do you see a better option?

**Comment by zinnschlag** [comment]
There is no cstdint, at least not in C++98 or C++03. stdint.h isn't generally available in C++ either, because it is a C99 header. We have a workaround for this problem in libs/platform/stdint.h.

Will fix it. Merging now.

**Pull request merged**
