### PR TITLE
Save on close feature #473 added

### PR DESCRIPTION
**Pull request by joelgraff**
Added two message boxes to handle the discard/save and abort/wait features.  Also added an "Exit" menu item to the "File" menu.  Tested and all appears to work as it should.

### CODE REVIEW

**Comment by zinnschlag** [comment]
Shouldn't exit end the program instead of just closing one window?

Also, this line:

> setAttribute (Qt::WA_DeleteOnClose, true);

looks wrong. I haven't found any problems with it, but unless I am completely mistaken this could potentially mess things up. At least it is redundant.

The confirmation dialogue does not pop up on closing the last view of a document, but on any view.

And finally, please do not leave outcommented code in the source. If a piece of code is not needed anymore, then delete it.

**Comment by joelgraff** [comment]
FWIW, I did go through and clean up commented-out code - I obviously missed something, however - either that or the change was lost - I had a slight problem with github in my last round of commits.

Good point on the confirm dialog in multiple views - I obviously hadn't considered that.  It'll be a quick fix.

As for the Exit item, agreed that "Close" should be the view-specific option.  So should there be a "Close View" and "Exit Program" in the file menu?

As for the DeleteOnClose attribute, the reasoning for it is this:
1.  Closing a QMainWindow is not the same as deleting it.
2.  No parent is assigned to the View instance, so there is no guarantee that it would be part of a delete cascade when the parent is deleted.

Since I could not guarantee the view was ever deleted and implementing the latest feature required me to trigger the "close" event from more than one point in the code, I decided it's best to let Qt do the dirty work for me and not worry about it.  If you'd rather I removed the attribute and restored the delete code, I will.

**Comment by zinnschlag** [comment]
> As for the Exit item, agreed that "Close" should be the view-specific option. So should there be a "Close View" and "Exit Program" in the file menu?

Actually, I think "Close" should be file/document specific (assuming we mean file->close). I would call "Exit Program" "Quit" instead. Much clearer.

About the DeleteOnClose: Something about that does not sit well with me, but I can't pin it down right now. Need to have a closer look (and do a bit more testing). I'll get back to you about that as soon as possible.

**Comment by zinnschlag** [comment]
Found the hole I was looking for. Took quite a bit of poking though:

In CSVDoc::ViewManager::closeRequest you are removing the view from the view manager (mViews.erase), even if the view is not actually removed at this point. This breaks the UI, if (for example) you click on cancel. That's why the DeleteOnClose is problematic. Deleting and removing the View from the ViewManager should always happen together.

Furthermore if the user does not click on any button in the dialogue before the saving is completed, the dialogue (and the view) should close.

Unrelated to that, I dislike the wording on the buttons in the dialogue. It is a bit confusing. I blame the "No" and "Yes" mostly. I know that in most modern style guides the use of these on buttons is not discouraged. But I think that is wrong. The label on a button should say what the button does. How about this:

"The document is currently being saved. Closing it now will result in the document not being saved.

Do you want to wait until the saving is completed?"

"Cancel" "Close Now" "Wait"

Or at least something like this.

**Comment by joelgraff** [comment]
On the close request bug - I did code that correctly, but had to re-work the logic in closeRequest() and must have forgotten about it.  Whoops.  I'll fix that.

I prefer the positive wording as well on the dialogs.  Will take care of that.

As for the dialog auto-closing if the save operation ends, I did think of auto-closing once the save operation ended, but opted instead to wait for the user to make a decision, first.  My thinking was, once the user's offered the chance to make a decision, then they should make a decision, even if the condition that triggered the dialog clears before they've decided.  Thus, if they choose to "wait" or "abort" after the operation ends, the view closes immediately, but if they "cancel", they abort the closing, even though the save has completed.  If you'd rather have the view auto-close once the save is complete, I will make the changes.

So far as deleting views go, do we leave the attribute setting in?  Or get rid of it and specifically delete the view? (I think I'll have only two places where delete code needs to be added in the latter case).

**Comment by zinnschlag** [comment]
> I did think of auto-closing once the save operation ended, but opted instead to wait for the user to make a decision, first. My thinking was, once the user's offered the chance to make a decision, then they should make a decision, even if the condition that triggered the dialog clears before they've decided.

I do not agree with this statement. If a decision becomes meaningless, we shouldn't force the user to make one. By issuing the close command the user has committed to closing the document and there is not need to get a confirmation for it, if the closing can be done without data-loss (which is the case after a successful save).

> So far as deleting views go, do we leave the attribute setting in? Or get rid of it and specifically delete the view? (I think I'll have only two places where delete code needs to be added in the latter case).

Unsure. The problem is, as I mentioned before, that the view must be deleted at the same time it is removed from the view manager. Otherwise something breaks. I do not see how the DeleteOnClose can do that cleanly.

**Comment by joelgraff** [comment]
There are two conditions where immediately deleting a Qt object may
potentially cause a crash:
1.  Deleting an object from code within it's own event handlers
2.  Deleting an object from a slot or method directly or indirectly called
   by the object to be deleted (which is the case we have here -
   ViewManager::closeRequest is called by View::close() ).

deleteOnClose() or widget->deleteLater() mitigates that.  I can see your
point about deleteOnClose, so I will make explicit calls to deleteLater()
as appropriate.

**Comment by joelgraff** [comment]
Ok.  I think this fixes everything.  I got into the signals and slots a bit and had reorganize some code that was creating some confusion - took me much longer than I'd anticipated. :)  No worries, though - it was a good learning experience.

I tested both single and multiple views for both conditions (save before close and abort save on close).  Seems to work fine - no seg faults / unexpected finishes.

The only thought I had was, when closing with multiple views open, all views but one are closed before the message box pops up (for either condition).  Seems to me if the user cancels, they might prefer the other windows had been left open.

So - leave all windows open until the application officially closes?

**Comment by zinnschlag** [comment]
> The only thought I had was, when closing with multiple views open, all views but one are closed before the message box pops up (for either condition). Seems to me if the user cancels, they might prefer the other windows had been left open.

I assume you mean via file -> close?

> So - leave all windows open until the application officially closes?

Yes, absolutely.

**Comment by joelgraff** [comment]
As I was preparing to commit and push the final changes, I merged the master into my local branch and noticed a few changes that broke closing the application.

Specifically, clicking the close button on the main window now only closes the last tabbed document view, rather than the entire application.  Don't know who changed the views from floating windows to tabbed docks, but I can't seem to figure out how to fix the close button issue...  Was that all pvdk's work?

**Comment by zinnschlag** [comment]
I can not find such changes in pvdk's recent pull request. I suggest to find out who is responsible via git blame.

**Comment by joelgraff** [comment]
Right, I went over everything and I've missed it...

Just to confirm:  Are the editor views supposed to stack themselves in one
window with corresponding tabs at the top?  Or are they supposed to float
like they always have?

**Comment by zinnschlag** [comment]
We are talking sub-views here, right? The views are the top level windows. This doesn't happen to me by default, but when I undock a subview and re-dock it, I end up with a tab interface. That is definitely not what should happen.

**Comment by zinnschlag** [comment]
And another problem: When having multiple views of the same document open, closing one view closes the whole document. Lots of stuff going wrong here at the moment ...

**Comment by joelgraff** [comment]
Yeah, I'm at a loss.

I was talking about class View()::pubic QMainWindow instances.  Spawning a
new one from View->New View doesn't create a new floating view of the
document, it stacks it on the current view and adds a tab at the top.

I didn't test any of the Globals / Game Settings subviews.

Anyway, I don't see any code changes that would cause the behavior, but I
noticed in pvdk's latest commits, his work was based off the launcher.ui -
I realize he used it for the file dialog, but I'm wondering if something
from that is messing with the general application UI?

**Comment by zinnschlag** [comment]
> I was talking about class View()::pubic QMainWindow instances. Spawning a new one from View->New View doesn't create a new floating view of the document, it stacks it on the current view and adds a tab at the top.

That does not happen here.

**Comment by joelgraff** [comment]
Dammit.  Nevermind.  It was a KDE window manager setting that I must have inadvertently clicked.

As for undocking / redocking the subviews, Tabs to appear at the bottom, but only if I move the re-docked widget too far back into the origina window...  If I moved it slightly into the original window, the remaining docked widget would resize slightly and the re-docked widget would take up position next to the first, though it's greatly undersized..  I assume you want to avoid the stacking behavior in all cases?

Also, will look at that closing view / closing document issue you mentioned.

**Comment by zinnschlag** [comment]
> As for undocking / redocking the subviews, Tabs to appear at the bottom, but only if I move the re-docked widget too far back into the origina window... If I moved it slightly into the original window, the remaining docked widget would resize slightly and the re-docked widget would take up position next to the first, though it's greatly undersized.. I assume you want to avoid the stacking behavior in all cases?

Yeah. Ideally I would like a blender-like interface, where you can dock a sub-view anywhere.

> Also, will look at that closing view / closing document issue you mentioned.

Actually, I am not sure if that is still relevant. I have tested on master, not on your branch. I think you have done a lot of changes in this area, that might or might not have eliminated this problem.

**Comment by joelgraff** [comment]
Ok, try this.  Tabbed docks are disabled, application shuts down completely on exit and closing one window doesn't kill everything...

**Comment by zinnschlag** [comment]
The close check when multiple views of the same document are open still does not work (confirmation dialogue pops up after closing any view, not just the last one). The tab problems seems to be fixed though.

**Comment by joelgraff** [comment]
Heh.  Of course.  Broke one thing in order to solve another...

**Comment by joelgraff** [comment]
Here ya go.  I can't make it fail, and I think I'm finally testing for every condition...

**Comment by zinnschlag** [comment]
Merging into next instead of master.

**Pull request closed without merging**
