### PR TITLE
Include headers necessary for compilation under VS2010

### PR DESCRIPTION
**Pull request by JordanMilne**

### CODE REVIEW

**Comment by blunted2night** [comment]
That curious, I have done all my development and testing of these patches against the VS2010 compiler. Must have been a difference in Ogre. I am using 1.8.1.

**Comment by zinnschlag** [comment]
What is that supposed to fix anyway?

btw. that is a C header. If it is really needed, then please include the respective C++ header instead.

**Comment by blunted2night** [comment]
I ran across the same problem trying to build against Visual Studio 2012. Usage of the uint8_t type needs "cstdint" to compile correctly. The existing code was depending on an external library including it, which depending on what versions are being used, may or may not be present.

**Comment by JordanMilne** [comment]
It fixes uint8_t being undefined under VS2010

**Pull request merged**
