### PR TITLE
hit recoils/knockdowns + death animations handling cleanup

### PR DESCRIPTION
**Pull request by mrcheko**
All code realted to Group_All weapon animations is removed.
Also appropriate damage falling handling is added.

### CODE REVIEW

**Comment by ghost** [comment]
It looks like the death animation changes caused another issue. I killed Ajira in the mages guild, and I got:
Failed to find animation death4 for ajira
and the NPC froze in place instead of dying.

**Comment by ghost** [comment]
Nevermind the last two comments. Looks like I hadn't actually pulled your latest changes yet. Sorry.
The khajiit death issue however still exists.

**Comment by mrcheko** [comment]
Yes, I've already thought of unequal number of hits recoils for 3rd- & 1st-person views, deaths for creatures/npcs and now beast races, also it seems that creatures have only hit1 and death1 etc. So maybe we should make smth like a global std::map<"model", animParams>, where struct animparams: {numDeaths, numHits, numAttacks and so on};

**Comment by ghost** [comment]
I guess we can just retrieve the number of animations whenever we want to randomly choose one. It's not like death/hit would occur so often that it'd be a performance issue.

**Comment by ghost** [comment]
https://github.com/scrawl/openmw/commit/fec26342cd57269bc0801e5d901e00419fbc7cec should fix those issues once and for all.

**Pull request merged**
