### PR TITLE
Stop merchants from autoequipping items sold to them

### PR DESCRIPTION
**Pull request by ghost**
Making a separate pull request because I'm not 100% sure this won't cause any side effects.

Items added via console (additem) will still be equipped since the add-by-id function sets the owner of the item to the NPC it's added to.
Items sold to an NPC currently do not get the owner set to the NPC they are sold to, meaning they won't be equipped.
Afaik we do not need to set the owner in that case. It would only really be relevant when stealing back items you previously sold to the NPC, then being able to sell them back. If that happens, we could set the owner upon taking an item from the pickpocket window?

### CODE REVIEW

**Comment by zinnschlag** [comment]
Sounds reasonable.

**Comment by kido5217** [comment]
I wonder if it really should be done?..
As far as I remember, in vanilla morrowind if merchant had appropriate skill he immediately equipped the item you've sold him. At least it worked for armor.

**Comment by zinnschlag** [comment]
That is also a good point. Though this behavior is hideous. Ideally (for compatibilities sake) the way to do it would be to add a new GMST in OpenMW 1.1 that defaults to 0 and when set to 1 enables the behavior introduces in this pull request.
I am not sure if we should revert (or better out-comment) for now.

**Comment by kido5217** [comment]
They had companion in vanilla Tribunal too and yes, you could give him armor and weapons.

**Comment by ghost** [comment]
Indeed. Well, we can add a check for that ;)

**Pull request merged**
