### PR TITLE
fixes #128 Configuration cleanup.

### PR DESCRIPTION
**Pull request by lgromanowski**
Hi,
it's rebased and squashed commit for issue #128 - configuration cleanup.

### CODE REVIEW

**Comment by zinnschlag** [comment]
Does not compile here:

> /home/marc/OpenMW/openmw/components/files/linuxpath.cpp: In member function ‘boost::filesystem::path Files::LinuxPath::getGlobalConfigPath() const’:
> /home/marc/OpenMW/openmw/components/files/linuxpath.cpp:81: error: ‘strtok’ was not declared in this scope
> /home/marc/OpenMW/openmw/components/files/linuxpath.cpp: In member function ‘boost::filesystem::path Files::LinuxPath::getGlobalDataPath() const’:

Also, since we are apparently not done yet with fixing 0.11.0, features for 0.12.0 will go into the next branch again (just recreated it).

**Comment by lgromanowski** [comment]
Hmm, It's strange on g++ (GCC) 4.6.1 it compiles without problems, but there is missing cstring header (probably it's included somewhere). I will add it in next commit.

**Comment by zinnschlag** [comment]
Merged into next.

**Comment by lgromanowski** [comment]
OK, thanks!

**Pull request closed without merging**
