### PR TITLE
Update OS X info

### PR DESCRIPTION
**Pull request by MaddTheSane**

### CODE REVIEW

**Comment by nikolaykasyanov** [comment]
Wow, thanks for update!

BTW, mpg123 is not required since we started using FFMpeg for video, it could also play mp3s.

But I don't see the point in ignoring .DS_Store, any sane OS X developer has this entry in his global .gitignore IMHO

**Comment by nikolaykasyanov** [comment]
I think we could delay this merge a bit, I would be able to make major changes to documentation and describe my current (slightly simpler) build workflow this weekend.

**Comment by zinnschlag** [comment]
Fine with me.

**Comment by MaddTheSane** [comment]
@corristo There's a global .gitignore file? Also, yes, please update this, I discovered, when running CMake, that OpenMW uses libraries not mentioned here.

**Comment by jeaye** [comment]
>    [1]@corristo There's a global .gitignore file?

Yes, it's in your home directory. See ~/.gitignore

**Comment by nikolaykasyanov** [comment]
@jeaye @MaddTheSane it should be set explicitly in ~/.gitconfig like this:

```
[core]
excludesfile = /Users/corristo/.gitignore_global
```

**Comment by nikolaykasyanov** [comment]
@MaddTheSane this is the work-in-progress document, please take a look: https://gist.github.com/corristo/7112971

**Comment by zinnschlag** [comment]
Have we made any progress here?

**Comment by nikolaykasyanov** [comment]
Yep, I have work-in-progress version, I want to put it into wiki eventually. I think that dedicated read me in repo is redundant, I'll remove it in separate pull request.

**Pull request closed without merging**
