### PR TITLE
A few fixes to build on Windows

### PR DESCRIPTION
**Pull request by ananace**
Yes, I know it's not a nice solution. But a solution it is nonetheless, and I think having everything building on Windows is a good idea.

### CODE REVIEW

**Comment by jbo-85** [comment]
The libunshield problem should be fixed by removing the duplicate lines for unshieldthread.hpp in 
apps/launcher/CMakeLists.txt

**Comment by zinnschlag** [comment]
Please do not outcomment soruce that is not used anymore. Just delete it. Also, maybe you should add a short comment about these being workarounds for MSVC bugs. Otherwise these changes might be undone by someone else working on the code, who is not aware what they are for.

**Comment by ananace** [comment]
There, does this look better maybe?

**Comment by psi29a** [comment]
Does this also 'fix' installer support for windows or just so that openmw building works again on windows?

**Comment by ananace** [comment]
What's wrong with the installer?
The fixes are for linking errors on OpenMW and OpenCS as well as compiler errors on the Launcher.

**Pull request merged**
