### PR TITLE
Launchernext

### PR DESCRIPTION
**Pull request by pvdk**
This branch is ready for merging I believe, it has some changes by mike76 I needed for the datafilespage. I will have a look at the file selection dialog in the editor once this is merged, there is some old datafilespage.cpp code there that shouldn't have been there in the first place.

This branch features the first run dialog and my new settings manager. It also fixes the non-latin strings bug.

### CODE REVIEW

**Comment by zinnschlag** [comment]
Does not build for me: https://gist.github.com/zinnschlag/5033120

**Comment by pvdk** [comment]
How stupid, forgot to build after those changes to the order of includes, it seems they do matter :)

**Comment by zinnschlag** [comment]
I am getting a completely different UI for the open dialogue in the CS now. Both master and plugins folded into one list. That won't work.

**Comment by zinnschlag** [comment]
Hm, it seems you showed that same window in the discussion thread once. Apparently it somehow escaped me, that master and plugins had been merged. Sorry for that. We kinda do need to do away with the old master list, but not by merging. I am not sure if we are on the same page here. Maybe this discussion should be moved to the forum.

**Comment by pvdk** [comment]
Did I? I don't remember that. mike-sc did show you a screenshot in his pull request, or do you mean the mockup I made? I'm going to have a look at the open dialog as soon as this is merged as I was aware of issue. The model has been changed to hold both *.esp and *.esms but as you can see in the launcher there are still two views, one for the plugins and one for the masters. I do that by using a proxy model to filter the model contents. We'll need to do the same for the open file dialog.

It's more efficient this way as we don't need to instantiate two separate models. I was intending to do this myself but I lost the commit, so I'm glad mike-sc managed to do it.

**Comment by zinnschlag** [comment]
So the launcher UI is finished, but the editor UI is in a half finished state (I meant the editor UI, when I mentioned the merge)? Not happy about that, since I am still actively working on the editor. But see my posting on the forum please.

**Pull request closed without merging**
