### PR TITLE
resource loading performance v2

### PR DESCRIPTION
**Pull request by blunted2night**
change ConstrainedDataStream to use the lowest level file API available on the platform, change ESMReader to use a ConstrainedDataStream instead of ogres file stream implementation.

recreated commits to include fixes from feedback, and have a cleaner history

### CODE REVIEW

**Comment by Thoronador** [comment]
Just out of curiosity:
How much performance improvements did you get with these changes in your tests? And on what systems have you tested these changes?

The reason I am asking is that I pretty much doubt a change to a low(er)-level API will result in any _noticeable_ difference. In general, you should be able to stay high-level in C++ most (or all) of the time without any performance drops compared to a low-level API. (Compiler optimizations also do their part in this, so a programmer can probably stay high-level more often than he/she thinks. The generated executable code might be very similar anyway, no matter what API is used. However, high-level code is easier to maintain than the low-level code.)

**Comment by blunted2night** [comment]
I started a forum thread discussing it here https://forum.openmw.org/viewtopic.php?f=6&t=1266#p12614

This particular change produces a considerable speedup on windows. My theory on why it is significant is that C++ iostreams suffer from "jack of all trades" syndrome. It can do anything, but none of it well (particularly Microsoft's implementation)

**Comment by zinnschlag** [comment]
Does not build: https://gist.github.com/4451331

**Comment by blunted2night** [comment]
I created a new branch with  627afa0 merged into 823f59d

https://github.com/blunted2night/openmw/tree/readperf_v3

**Pull request closed without merging**
