### PR TITLE
Light INI-import (fallback settings), rewritten fallback system.

### PR DESCRIPTION
**Pull request by Glorf**
Third part of fallback settings imports.
Also, removed some old, unused fallback functions and traps.

### CODE REVIEW

**Comment by zinnschlag** [comment]
You are now duplicating methods for accessing fallback values all over the place. That is not a good idea. Maybe it would be a good idea to create a proper fallback class instead. Also, the ability to access fallback values should definitely not be removed from World.

**Comment by Glorf** [comment]
Fallback values are still in World. Take a look, I've just removed duplicated getfallback,and unused setfallback.
You're right, maybe I'll create separated file with fallback class in mwbase?
The worst thing with fallbacks is that some classes (eg, WeatherManager) use them in constructors. That's why I'm sometimes unable to get them from Environment and I've got to add fallbackmap nearly everywhere.

**Comment by zinnschlag** [comment]
> Fallback values are still in World. Take a look, I've just removed duplicated getfallback,and unused setfallback. You removed a function for accessing fallbacks, namely:
> 
> virtual std::string getFallback (const std::string& key, const std::string& def) const = 0;

This one is not necessarily redundant. In fact it might be a good idea to generally change fallback access functions to something like this (defaulting to an empty string for text and a somewhat reasonable value for float and int). This would make sure that OpenMW still runs in case of an import failure, even if it looks a bit weird. I think that was the general idea anyway and the reason for this function to exist.

> You're right, maybe I'll create separated file with fallback class in mwbase?

That can safely go into mwworld.

> The worst thing with fallbacks is that some classes (eg, WeatherManager) use them in constructors. That's why I'm sometimes unable to get them from Environment and I've got to add fallbackmap nearly everywhere.

Handing a reference to the fallback instance down to instances of classes managed by the World class shouldn't be a problem. Nothing wrong with that.

**Comment by Glorf** [comment]
I removed that import trap, because openmw is unable to run without fallback values anyway.
EDIT: ok, you're right but openmw will look really crazy without this values :D
I'll update this pull tommorow. And I'll finally get rid of fallbacks in the World.

**Comment by zinnschlag** [comment]
> And I'll finally get rid of fallbacks in the World.

You mean the map, right? The instance of the new fallback class should still be managed by World.

**Comment by Glorf** [comment]
I wanted to put it on lower-level, to gain access to fallbacks durning world-dependent classes constructors but after some studies, I think that I'll just put it inside World, as you said.

**Comment by Glorf** [comment]
Done.

**Comment by zinnschlag** [comment]
Missing consts again (in your fallback class). Also, why does world still directly has a map of fallback values? These are supposed to be handled by the fallback class. Finally, there is no point in allocating the fallback instance via new.

**Comment by Glorf** [comment]
OK, fixed, I forgot about that fallbackmap in world.
I keep using new to instantiate class. What difference at all? (As I remember "new" class is only a bit slower that automatic class) I added delete in world destructor, the same place where automatic destruction would happen.
Also, openmw now runs without fallback values.

**Comment by zinnschlag** [comment]
> I keep using new to instantiate class. What difference at all? (As I remember "new" class is only a bit slower that automatic class)

When you create something with new you are responsible for deleting it (which is only the tip of an iceberg; there are a lot more issues to consider: exception-safety, rule of the three and so on). In general new should be avoided unless you need the additional flexibility it provides. In its current state the World constructor is partially broken (although in a very minor way). It would be a bad idea to break it even more by allocating the Fallback instance via new.

**Comment by Glorf** [comment]
Fixed

**Comment by Glorf** [comment]
Also, I think that the most serious problem of World is that too many things are made in constructors.
There should be additional functions that load values, constructors are too important to do that there.

EDIT: I think about MWWorld at all.
EDIT2: Can I try to rewrite it a bit? :)

**Comment by zinnschlag** [comment]
Still not exactly right. There is no reason for the setFallbackMap function. Using the constructor as you have done before was the right thing to do.

> Also, I think that the most serious problem of World is that too many things are made in constructors.

Not really. The constructor is doing exactly what it is supposed to do (minus the exception-safefy). It constructs the world. At most the body of the for loop could be factored out into a private function.

**Comment by Glorf** [comment]
Ok, it should be good now...
Thanks for your help. 

EDIT: I added this function because I prefered to avoid constructors in my own projects. They make code less clear for me.
EDIT2: I think that body of "for" functions could be implemented into ESM::ESMReader without problem.

**Comment by zinnschlag** [comment]
I am getting plenty of merge conflicts. Among others you are using tabs in some places for indenting, which throws git off. Please don't do that.

We can merge once these issues have been resolved. I suggest you get rid of all tabs, then merge my next branch into your branch and then send a new pull request against my next branch.

**Comment by Glorf** [comment]
I've been using my master branch too much. I have to re-create my repo. Is it safe for my commits that you've already merged?

**Pull request closed without merging**
