### PR TITLE
Stats should never go below 0

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by zinnschlag** [comment]
That would be undefined behaviour.

**Comment by ghost** [comment]
Please elaborate more, what is undefined behaviour?
My point with this pull request is, that if you (for example) drink lots of -attribute potions, the final attribute value shouldn't go below zero. That's what vanilla does (Same with skills).

**Comment by zinnschlag** [comment]
You are returning a reference to a local temporary variable. That is not allowed in C++.

**Comment by ghost** [comment]
Ah, of course. I just didn't pay attention to the method signature. And for some reason didn't see the compiler warning. Fixed

**Pull request merged**
