### PR TITLE
Issue #225: Fix for memleak when loading terrain.

### PR DESCRIPTION
**Pull request by lgromanowski**
Hi,
here is fix for memleak when loading terrain data.

best regards,
Lukasz

### CODE REVIEW

**Comment by zinnschlag** [comment]
Need to think about it more. Your fix is at least incomplete, since copying and assignments will cause problems. But the whole land record code looks incorrect in the first place.

**Comment by lgromanowski** [comment]
You're right, I will prepare another patch today.

**Comment by lgromanowski** [comment]
Hi,
is patch 0e5c90d good, or should be changed?

**Comment by zinnschlag** [comment]
The problem with this approach is that it increases the memory consumption a lot. If my calculations are right easily in the order of magnitude of 100MB. And most of this memory will probably never be used during a playing session.
Actually, the land data should not be part of this record at all, because you are not supposed to modify the ESM store after the loading is complete (it is only possible because some other code breaks constness rules). But that is something we really need think through better and this is not the time for it. As a quick fix, I suggest to return to the pointer approach and disable copy constructor and assignment operator (declare them privately and don't implement them). This will break the code once we start optimising the ESM store containers, but at least it won't do so silently and produces an error message during the build process isntead.

**Comment by lgromanowski** [comment]
Copy constructor and assignment operator are now disabled for Land structure.

**Pull request merged**
