### PR TITLE
Script functions

### PR DESCRIPTION
**Pull request by kcat**
Just noting that ShowVars is a method in vanilla MW: http://uesp.net/wiki/Tes3Mod:ShowVars . I doubt it's implemented using the same formatting, but it serves the function regardless (this would've helped me in tracking down the Hircine's Ring bug, but I can't seem to get a reference name for it while it's in the inventory).

### CODE REVIEW

**Comment by zinnschlag** [comment]
I don't think the lines 704-705 in miscextensions.cpp are a good idea. The else case would only happen on a corrupted/uninitialised data structure. In this case accessing the data structure is the last thing we want to do.

Also, I do not understand why we need two classes for ShowVars. The global variable case would only happen if there is neither an explicit nor an implicit reference, so there should be no problem with integrating OpShowVarsImplicit into OpShowVarsExplicit.

About not being able to get a Ptr to an object in an inventory: I think I know where the problem is. Will attempt a fix (not sure if I can get it done today).

**Comment by zinnschlag** [comment]
Okay, definitely not today. Maybe not even tomorrow (but I definitely want to get it out by the day after that). It looks more complicated than I thought. If I do it wrong, I will totally kill the performance.

**Comment by kcat** [comment]
> I don't think the lines 704-705 in miscextensions.cpp are a good idea. The else case would only happen on a corrupted/uninitialised data structure. In this case accessing the data structure is the last thing we want to do.

Okay. I was thinking in case we ever add other variable types since there would otherwise be no warning that they're not printed, but I've removed the case.

> Also, I do not understand why we need two classes for ShowVars. The global variable case would only happen if there is neither an explicit nor an implicit reference, so there should be no problem with integrating OpShowVarsImplicit into OpShowVarsExplicit.

I did that while I was trying to figure out how to get it to run while no implicit or explicit reference was set. I've recombined them now, though.

> About not being able to get a Ptr to an object in an inventory: I think I know where the problem is. Will attempt a fix (not sure if I can get it done today).

It's not really that I can't get a Ptr in the code, it's that I have no way to reference it in the console. There's no name I can type and nothing I can click on for the interpreter to know I want the one in my inventory. All I have is the base object name, but nothing to signify which instance of the object I want since there can be more than one.

I'm also adding a fix for GetEffect. It's supposed to be able to accept effect strings like "sEffectRecall", in addition to the numeric IDs.

**Comment by zinnschlag** [comment]
> It's not really that I can't get a Ptr in the code, it's that I have no way to reference it in the console. There's no name I can type and nothing I can click on for the interpreter to know I want the one in my inventory. All I have is the base object name, but nothing to signify which instance of the object I want since there can be more than one.

Yes, but objects in active cells take precedence over objects in inactive cells when accessing something via ->. So, unless you have another copy of that ring lying around you should be able to access it (that is, you could do it if the code for that were not bugged).

**Comment by zinnschlag** [comment]
> Okay. I was thinking in case we ever add other variable types since there would otherwise be no warning that they're not printed, but I've removed the case.

Feel free to throw an exception or print an error message to the console. But accessing the data in case of a missing variable type is really not a good idea.

**Pull request merged**
