### PR TITLE
Cs load option

### PR DESCRIPTION
**Pull request by mike-sc**
It's still raw.

Open prints list of file paths on stderr instead of opening them.
DataItemList should be in seperate qtcomponents.
There is no way (and never was) to specify loading order. IMO two list boxes could be merged.
There is no way to select edited esp.

I want to know if this is good way to go or not.

### CODE REVIEW

**Comment by zinnschlag** [comment]
Does not build:

> CMake Error at apps/opencs/CMakeLists.txt:65 (add_executable):
>  Cannot find source file:
> 
>    view/tools/opendialog.cpp

I guess you forgot to commit a file.

Other things, I noticed:
- The code does not follow out naming conventions (file names).
- Qt has been kept optional, i.e. if you don't want to build the CS and the launcher you don't need Qt. We should keep it at that.
- The open dialogue file should go into view/doc instead of view/tools
- The feature probably should be called Open instead of Load.
- Your comments in the actual load function are wrong. Our editor is multi-document capable. When you open a new document, you don't close the old one.

I will review the code again, when these issues have been fixed (just add another comment to this pull request).

Regarding merging the list: There is currently a discussion coming to an end on the forum regarding the file formats. This will change things. Most likely we will end with something ComboBox-like and a multi-selection list. But we can look into that later.

**Comment by mike-sc** [comment]
> The code does not follow out naming conventions (file names).

With files? Is it about "file_order_list" folder?

> Qt has been kept optional

I will create "qtcomponents" and move files there.

**Comment by zinnschlag** [comment]
> With files? Is it about "file_order_list" folder?

Yeah.

> I will create "qtcomponents" and move files there.

No new category of subsystems, please. We need to figure out a way to handle it in cmake with the current layout. Maybe put the qt using components in an if clause, that checks if Qt is available?

**Comment by zinnschlag** [comment]
I just added a provisional startup dialogue (in my startup branch), which also provides a place to hook up the ESX picker dialogue. I suggest you merge in this branch and make the necessary changes.

**Comment by zinnschlag** [comment]
For future reference, if you add commits to an existing pull request, please also add a comment afterwards. Else it will not show up in my news feed. Noticed your commits from four days ago only now.

**Comment by zinnschlag** [comment]
Merged into startup instead of master.

**Pull request closed without merging**
