### PR TITLE
Ref record type delegate

### PR DESCRIPTION
**Pull request by joelgraff**
Here's the delegate implemented for text only.  I noticed there are icons - did you want those indicated as well?

If so, I can work on that.  However, perhaps you want to check and see if the ID column is blank as it is for me...

### CODE REVIEW

**Comment by zinnschlag** [comment]
Works for me. But I don't think we can do it that way. The overall approach is not correct. You are working with the SIdArg list. That is more than the list of just the referenceable IDs, i.e. there are many ID types in there that are not referenceble. That is at least very unclean. I don't think it is a good idea to modify UniversalID at all. The list of referenceable ID types should be handled by the delegate (you can still get the matching name from the UniversalID class).

And yes, we need the icons. icon mode, text mode icon+text mode. Same as with the modification state.

Some unrelated issues:
- Please do not use all-uppercase names for constants. We don't do that here (see wiki).
- Why are there VerTypeDelegate and VarTypeDelegateFactory classes in refrecordtypedelegate?
- To keep an at least somewhat consistent naming scheme, can we call the delegate RefIdTypeDelegate instead please?
- One of your commits removed an include from datafilesmodel.cpp. That breaks compilation for me.

Edit:
- I am still getting a lot of debugging output on the console. That needs to be removed.

**Comment by joelgraff** [comment]
I had the other qdebug references deleted, but for some reason I never committed them...  As for the commented out code in the new delegate - it was a reference for me.  Didn't worry about cleaning up because I was worried about determining whether the ID column in the referenceables table was still populated on your end.  Really, may as well delete the pull request if we can establish that I've not broken the Id column...

Commit with removed reference in datafilesmodel.cpp was deleted.  I was looking for qDebug(), not realizing qWarning() also used that library...  Whoops.  Should compile, now.  Can't prove it though.  For some reason, my repo is now screwed up.  Might take me a bit to get back up to speed.

So far as the universal ID thing goes, how do you get the type name from a given enum?  If I'm not allowed to access sIdArg[], then I have to have the specific UniversalId instance in-hand to get the name string.  The problem is, I need to load the enum string when the delegate is created in ViewManager, which is before a refIdCollection instance is created - that is, sIdArg[] has everything I need, but there are no UniversalId instances at that point...  Of course, I could just code the name strings directly in the factory.  It's technically higher maintenance, but I get the impression the list is not likely to change, so maybe it doesn't matter.

The only other solution I can think of is to wait until the referenceables table is created and, when the delegate is assigned to the Type column, provide the enum strings to the delegate then.  At that point, the RefIdAdapter instances have been created and I could iterate the mAdapter list, assuming I can somehow pull the string from each adapter instance... ?  I'm thinking at this point I'll just hard-code the name strings in the factory and be done with it.

On another note, I may go back and rewrite the EnumDelegate class so that it'd handle icons as well - more or less incorporate much of the code from RecordStatusDelegate into it, then base RecordStatusDelegate and this new delegate on that.  That way, VarTypeDelegate and the other two delegates will be derived from the same class.  Maybe rename EnumDelegate to DataDisplayDelegate or something? It should be easy enough to manage icon / text user pref switching in the derived delegate classes so the VarTypeDelegate isn't affected.

Finally, does the user pref for the Record Status delegate also affect the id type column?   I am assuming that was the intention, rather than creating a separate preference...

**Comment by zinnschlag** [comment]
> I had the other qdebug references deleted, but for some reason I never committed them...

Git status. It helps a lot. Really.

> As for the commented out code in the new delegate

IIRC it was not commented out. Still puzzled that the whole thing even compiled.

> So far as the universal ID thing goes, how do you get the type name from a given enum?

You need a list of the types in the factory class. No way around it, since the UniversalId class does not have this list (it has a superset of it). As for getting the name you could just create an UniversalId instance for each type (with an empty ID string) and then call getTypeName on it.

> The only other solution I can think of is to wait until the referenceables table is created and, when the delegate is assigned to the Type column, provide the enum strings to the delegate then. At that point, the RefIdAdapter instances have been created and I could iterate the mAdapter list, assuming I can somehow pull the string from each adapter instance... ? 

I don't think that would work, but I am not done yet with the referenceable table (very slow progress).

> I'm thinking at this point I'll just hard-code the name strings in the factory and be done with it.

Please don't do that. We don't want to get the names duplicated.

> On another note, I may go back and rewrite the EnumDelegate class so that it'd handle icons as well.

Not a good idea, since the EnumDelegate is used in many cases where we do not have icons. You could however make a subclass of EnumDelegate for that purpose.

> Finally, does the user pref for the Record Status delegate also affect the id type column? I am assuming that was the intention, rather than creating a separate preference...

Separate one please. It's not as if we didn't have the space for it in the settings UI and some users may prefer to set the display mode independently.

**Comment by joelgraff** [comment]
Git status - been trying to use it.  I do see the value of it - just not quite second nature yet. :)

I'll give the UniversalId suggestion you made a go.  Sounds like a good idea.

With the EnumDelegate class, I'll just subclass it.  I don't think modifying it would have any effect on the other classes (adding features shouldn't break existing code, IMO), but it seems to make good sense to subclass it to add the features, anyway.

Once I figure out why I've been denied access to half of my repo directories, I'll get on it. :)

**Comment by joelgraff** [comment]
Latest commit with working delegates and user preferences.  Not yet ready for pull.  Renamed editorpage and refrecordtypedelegate class files, but git could not commit deletes.  May need to manually delete on your end... ?

**Comment by joelgraff** [comment]
This should about do it.  No extraneous QDebugs, no commented out code, and dynamic_casts are fixed.  RecordStatus and IdType delegates operate independently.  Missing item-leveled icon located and added.

Let me know on anything I've missed.  Otherwise, I'll starting monkeying with the aesthetics for the ESX Selector...

**Comment by zinnschlag** [comment]
Sorry, this pull request (and the branch related to it) is totally messed up. I don't think we can use it (look at the Files Changed tab).

**Comment by joelgraff** [comment]
Hmmm... Ok.  I'll take a look...

**Comment by joelgraff** [comment]
Ok.  I have no idea how to fix this.  I see the problem - it was the file permissions commit I made.  I don't know what happened, but it was obviously related to me changing the ownership / group / permissions on a bunch of files that I couldn't write.  That said, wouldn't an "empty file" simply apply no changes?  I can try to fix it, but it seems to me it shouldn't create any problem... ?

Otherwise, my only thought would be to create a new branch, pull from upstream, then go back and apply the commits in order - either by cherry-picking all but the one commit or copying and pasting changes by hand...

**Comment by zinnschlag** [comment]
I doubt we have any empty files here. There have been changes made to this files. I don't know exactly what they are. The branch is so messed up, that I can't even review it on github and I certainly will not pull it into my local repository. Sorry, but starting with a new branch is really the only option here.

**Comment by zinnschlag** [comment]
Well, actually you could reset the HEAD to the point before this happened and then continue from there, if that is any help.

**Pull request closed without merging**
