### PR TITLE
Weather

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by zinnschlag** [comment]
Please do not use the preprocessor for constants! The rest looks okay though.

**Comment by ghost** [comment]
can you specify?

**Comment by zinnschlag** [comment]
CLOUD_SPEED. Don't use preprocessor defines for constants (it's stated in the wiki). The preprocessor should be limited to includes, include guards, asserts and conditional compilation (if unavoidable).

**Comment by zinnschlag** [comment]
Okay, that is one way of doing it (the other would have been to put C++ constants into an anonymous namespace). Will merge in a moment.

**Pull request merged**
