### PR TITLE
Branch 0 29

### PR DESCRIPTION
**Pull request by cc9cii**
Win32 fixes for openmw-29.  Tested with x64 Debug & Release as well as x32 Debug and Release builds.

### CODE REVIEW

**Comment by zinnschlag** [comment]
If these fixes go into master, they won't be available for the upcoming release. Is that what you are intending? If not, then we have a problem, because your branch contains unrelated changes from master, which can not go into release.

**Comment by cc9cii** [comment]
These are intended for openmw-29.  I thought I had compared the correct branches when I made the pull request (triple checked to ensure that there would be no merge issues with the openmw-29 branch) but of course I could still have made an error :-(

I just had another look and it does look like I've compare against your master instead of openmw-29.  Let me try this again.

**Comment by zinnschlag** [comment]
Please note, that merge conflicts are not the issue I mentioned (though they should be avoided too). The issue here is that you pulled in changes from master that are not intended for this release, because they are too fresh and could potentially break stuff.

**Comment by cc9cii** [comment]
Yes, I believe I get it now.  Please close this one, I'll create a new request shortly (no issues this time, I promise!)

**Pull request closed without merging**
