### PR TITLE
fix exceptions that cause the game to quit not being printed

### PR DESCRIPTION
**Pull request by ghost**
Since the switch to environment singleton, there is an issue that exceptions causing the game to quit are not printed anymore, making it impossible to say what the problem is. The problem is that Engine is declared inside the try-catch block in main.cpp. Thus, when an exception is raised, the Engine destructor will be called _before_ the exception is printed - and because the singleton assertions in the Engine destructor can fail if it wasn't initialised completely, this will cause the exception not to be printed at all.

To fix this, I've simply moved the engine declaration outside of the try-catch block.

### CODE REVIEW

**Comment by ghost** [comment]
I'm not sure, but maybe a better fix would be to remove that try-catch block completely. An exception will cause an exit anyway (and the exception is always printed with a message like "terminate called after raising an exception of ..."), so catch-print-return doesn't remotely make sense?

**Comment by ghost** [comment]
Nevermind my previous comment, this is not defined behaviour, see http://stackoverflow.com/questions/368184/does-it-make-sense-to-catch-exceptions-in-the-main

**Comment by zinnschlag** [comment]
I do not see this issue. Exceptions are still reported properly for me. You probably have run into some edge case that should be easily fixable by moving mEnvironemt to the top in engine.hpp (so that it is always constructed first). No need to rewrite the main function.

**Comment by ghost** [comment]
Tried your suggested fix but it doesn't work. Not surprising, because the engine creates the subsystems one after one and then assigns them to MWBase::Environment. Thus, if during the creation of one subsystem an exception is raised, other subsystems may not be created yet.

**Comment by zinnschlag** [comment]
Can you please give me an example that reproduces the problem?

**Comment by ghost** [comment]
As simple as adding     throw std::runtime_error("oops");   to engine.cpp:376 (immediately before Setup up input system)

**Comment by zinnschlag** [comment]
Right. Completely forgot that we have an assert there too. The clean up code is not written too well. Will have a go at it.

**Pull request closed without merging**
