### PR TITLE
Linux file paths and deb packaging

### PR DESCRIPTION
**Pull request by jpn**
Changes locations of configuration files on Linux.
plugins.cfg:
If available in the current directory that one will be used, otherwise /etc/openmw/plugins.cfg will be used.

openmw.cfg:
Both /etc/openmw/openmw.cfg and ~/.openmw/openmw.cfg used, values in the latter one will override the first. The location of the latter one may be temporary changed using the OPENMW_HOME environment variable.

Resources and data locations:
Configurable from openmw.cfg

DEB Packaging with cpack:
Binary will be installed in /usr/games/, resources in /usr/share/games/openmw/resources/ and data will by default be expected in /usr/share/games/openmw/data/.

Version and maintainer will be based on the latest tag/git configuration if building form a git clone.

### CODE REVIEW

**Comment by zinnschlag** [comment]
Doesn't work for me. Error:

ERROR: OGRE EXCEPTION(7:InternalErrorException): Could not load dynamic library /usr/local/lib/RenderSystem_GL.  System Error: /usr/local/lib/RenderSystem_GL.so: cannot open shared object file: No such file or directory in DynLib::load at /home/marc/Tools/ogre-1-7-1/OgreMain/src/OgreDynLib.cpp (line 91)

I use a self-compiled version of OGRE and by default it installs its plugins into /usr/local/lib/OGRE.

Ubuntu 10.04, 64bit

**Comment by jpn** [comment]
Sounds like a problem with the population of plugins.cfg.
What does cmake put in plugins.cfg in the build directory and what do you usually use?

**Comment by zinnschlag** [comment]
In my plugins.cfg I have PluginFolder=/usr/local/lib. But it should be PluginFolder=/usr/local/lib/OGRE/.

**Comment by jpn** [comment]
What is the OGRE_ values looking like in CMakeCache.txt?

**Comment by zinnschlag** [comment]
OGRE_CFLAGS:INTERNAL=-pthread;-I/usr/local/include;-I/usr/local/include/OGRE
OGRE_CFLAGS_I:INTERNAL=
OGRE_CFLAGS_OTHER:INTERNAL=-pthread
OGRE_FOUND:INTERNAL=1
OGRE_INCLUDEDIR:INTERNAL=/usr/local/include
OGRE_INCLUDE_DIRS:INTERNAL=/usr/local/include;/usr/local/include/OGRE
OGRE_LDFLAGS:INTERNAL=-L/usr/local/lib;-lOgreMain;-lpthread
OGRE_LDFLAGS_OTHER:INTERNAL=
OGRE_LIBDIR:INTERNAL=/usr/local/lib
OGRE_LIBRARIES:INTERNAL=OgreMain;pthread
OGRE_LIBRARY_DIRS:INTERNAL=/usr/local/lib
OGRE_LIBS:INTERNAL=
OGRE_LIBS_L:INTERNAL=
OGRE_LIBS_OTHER:INTERNAL=
OGRE_LIBS_PATHS:INTERNAL=
OGRE_OGRE_INCLUDEDIR:INTERNAL=
OGRE_OGRE_LIBDIR:INTERNAL=
OGRE_OGRE_PREFIX:INTERNAL=
OGRE_OGRE_VERSION:INTERNAL=
OGRE_PREFIX:INTERNAL=/usr/local
OGRE_STATIC_CFLAGS:INTERNAL=-pthread;-I/usr/local/include;-I/usr/local/include/OGRE
OGRE_STATIC_CFLAGS_I:INTERNAL=
OGRE_STATIC_CFLAGS_OTHER:INTERNAL=-pthread
OGRE_STATIC_INCLUDE_DIRS:INTERNAL=/usr/local/include;/usr/local/include/OGRE
OGRE_STATIC_LDFLAGS:INTERNAL=-L/usr/local/lib;-lOgreMain;-lpthread
OGRE_STATIC_LDFLAGS_OTHER:INTERNAL=
OGRE_STATIC_LIBDIR:INTERNAL=
OGRE_STATIC_LIBRARIES:INTERNAL=OgreMain;pthread
OGRE_STATIC_LIBRARY_DIRS:INTERNAL=/usr/local/lib
OGRE_STATIC_LIBS:INTERNAL=
OGRE_STATIC_LIBS_L:INTERNAL=
OGRE_STATIC_LIBS_OTHER:INTERNAL=
OGRE_STATIC_LIBS_PATHS:INTERNAL=
OGRE_VERSION:INTERNAL=1.7.1

**Comment by jpn** [comment]
Ok, the problem is me not thinking enough.
If just pointing at an ogre build directory (which I do) plugins will be in the same dir as the libraries you link against, when installing they will not. I want to handle both ways so I can't just assume they will be in a sub directory, so the solution seems to be to glob a bit.

Does this work better?

**Comment by zinnschlag** [comment]
yeah, that did it.

**Pull request merged**
