### PR TITLE
Nif parse cleanup

### PR DESCRIPTION
**Pull request by blunted2night**
These two commits cleanup the NIF parsing code by breaking the NIFFile into two classes, one to represent an already parsed file, and another to represent a stream of NIF data to be parsed. The other change turns the large if/else block in the main parse function into a table of node name to factory function entries. These commits have no functional or relevant performance changes, they are merely a cleanup of the structure. I have a set of performance improvements that depend on these changes.

### CODE REVIEW

**Comment by zinnschlag** [comment]
Looks good, but doesn't fully match our naming guidelines:

a) no _ in filenames
b) Please no names that start with an underscore followed by an uppercase letter (in the include guard). Formally you are not allowed to use these in C++.

**Comment by blunted2night** [comment]
would you like me to fix the naming violations in existing files too?

**Comment by zinnschlag** [comment]
Not very important. But if you are volunteering, then yes please!

**Comment by blunted2night** [comment]
these two commits bring a number of nif related files into conformance with naming conventions

**Comment by zinnschlag** [comment]
Okay. Bad timing though. Chris just finished his animation rewrite that he was working on for the last two month. There are still some problems with it, but I expect a merge soon (probably within the next couple of days). I will merge in your branch afterwards, since there seems to be a lot of overlap.

**Comment by zinnschlag** [comment]
Just finished merging Chris' branch. Unfortunately the overlap seems to be even bigger than I expected. Can you have a look at that (merge in my master branch), please?

**Comment by blunted2night** [comment]
No problem, I will re-base and fix any conflicts when I get a chance.

**Comment by blunted2night** [comment]
Ok, I re-based against the latest master and fixed the conflicts

**Pull request merged**
