### PR TITLE
Staticogre

### PR DESCRIPTION
**Pull request by ghost**
Support for building with static ogre. We use this in the ubuntu ppa packages.

### CODE REVIEW

**Comment by zinnschlag** [comment]
Why do we need the ENABLE_PLUGIN stuff? Wouldn't it be easier to just use a different plugins.cfg file (depending on cmake settings)? That is what it is for and using the cfg file would also allow use to avoid littering the code with preprocessor instructions.

**Comment by ghost** [comment]
The ENABLE_PLUGIN stuff is for linking the plugins statically into the binary so it's necessary to know at compile time which plugins will be used. At the moment it's not possible to both use static and load dynamic plugins from a plugins.cfg at the same time because i think it wouldn't be worth the coding effort.

I could rewrite this to just use preprocessor instructions to check if the build is compiled with static ogre and which OS is used but that would mean it's less configurable through cmake which in my opinion is worse than having the ENABLE_PLUGIN preprocessor instructions.

**Comment by zinnschlag** [comment]
Okay. But shouldn't OGRE_STATIC be defined as a cmake option? Also, you have the BSPSceneManager listed somewhere. We don't use it.

**Comment by ghost** [comment]
I'm not sure what you mean. If you want to compile with static ogre and static plugins you add OGRE_STATIC="TRUE" as an argument for cmake.

There is code for BSPSceneManager because i've added support for all plugins but only the used ones are enabled. If you want i remove the code for BSPSceneManager.

PS: Accidently hit the close request button. Sorry :)

**Comment by zinnschlag** [comment]
http://www.cmake.org/cmake/help/cmake-2-8-docs.html#command:option

Yes, please remove the BSPSceneManager.

**Pull request merged**
