### PR TITLE
Item stacking

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by zinnschlag** [comment]
Not correct. You don't need to check the equality of enchantment or script, because these are defined by the ID (if two MW-references have the same ID, they also have the same enchantments and the same scripts). But you are missing tons of other stuff (not to mention the unstacking/restacking implementation when equipping/unequipping, which is also part of the task).  At least the equip-status, soul and charges. And the presence of a script should also block stacking.

**Comment by ghost** [comment]
Thanks for your remarks. 

> not to mention the unstacking/restacking implementation when equipping/unequipping, which is also part of the task

Ok, will do that. Belongs to the InventoryStore if I'm right.

> At least the equip-status, soul and charges.

In that case I should probably add a "getStack(const Ptr&, const Ptr&)" method to MWWorld::Class ?

**Comment by zinnschlag** [comment]
> Ok, will do that. Belongs to the InventoryStore if I'm right.

Yes. There are todo marks in the source.

> In that case I should probably add a "getStack(const Ptr&, const Ptr&)" method to MWWorld::Class ?

Nope. Soul and charge can be checked without going through the class interface. For equip-status you will have to add a virtual function to the containerstore, which is then implemented in the inventorystore (since the containerstore does not have equip-status).

**Comment by ghost** [comment]
> Nope. Soul and charge can be checked without going through the class interface.

But there is also remaining number of uses (e.g. for lockpicks) which belongs to the ESM::Tool class. I'm aware that current weapon health / remaining uses are not implemented, but if it was, the stacking code would have to be rewritten?

**Comment by zinnschlag** [comment]
> But there is also remaining number of uses (e.g. for lockpicks) which belongs to the ESM::Tool class..

No. The number of remaining uses is stored in the CellRef struct and therefore independent of the MWWorld::Class object in use. Good catch btw. Completely missed that one.

Not so sure about weapon health (which I also missed the first time). According to the loadcell.hpp documentation charges, number of uses left and weapon health are sharing the same variable (charge). But a weapon can have charges and health, so that doesn't seem to make much sense. Maybe a bit more ESM format decoding/research is required, before this task can be done properly.

I suggest having a function in ContainerStore that is used for checking the compatibility of two stacks (i.e. if they can be merged). This function can then be called from all places that do stacking/unstacking and you need to modify only a single function, if the need to modify the stacking algorithm comes up.

**Comment by ghost** [comment]
I added re-stacking (should work). But I don't know how to do the un-stacking. How can I create copies of an object?

**Comment by ghost** [comment]
Is it correct to just create a copy of the MWWorld::Ptr?

**Comment by zinnschlag** [comment]
> Is it correct to just create a copy of the MWWorld::Ptr?

That would just create a new pointer to the old object.

Use the add function. Or maybe a new protected addImp helper function, that does the same as the add function, before you started to implement stacking (you can factor out this part of add).

**Comment by ghost** [comment]
i think this should do, but i can't test it obviously.

**Comment by zinnschlag** [comment]
Yeah, annoying that we don't have a fully working inventory UI yet. Was hoping it would finish first. Been on the roadmap for ages.

I still see a few problems
- checking scripts for both stacks in the stacks() function is redundant, because if both stacks have the same ID they also have the same script
- before unstacking, you should check if the item needs to be unstacked (see the bool flag of the equipment slot function). Some items don't become unstacked when equipped.
- the stacks() function should also check, if the stack you are testing against is currently in an equipment slot (and then check the bool flag mentioned above to see if stacking is allowed at all).

**Comment by ghost** [comment]
Fixed the issues you mentioned.

**Pull request merged**
