### PR TITLE
several animation logic fixes (in game mechanics)

### PR DESCRIPTION
**Pull request by mrcheko**
1. actor could fall in knockdown several times in a row (from 1 hit);
2. this bug was observed on centurion movement: in the end of each step animation doesn't have any movement for short time, so centurion was sliding unrealistically at those moments.
   About creatures' speed: as I was comparing this to vanilla, I made a conclusion that animation speed = 1.0 give correct results. Also you can see here http://www.uesp.net/morrow/monsters/mwmonsters.shtml that atronach_frost has speed = 14 and centurion speed = 12. But in vanilla atronach_frost move slower than centurion. If you'll try speed = 1.0f for creatures, than you'll see that it acts just like in MW.
   Important note: there is some problem with "ascended_sleeper" (it moves extremely slow in MW). In openMW he moves like he has no animation accumulation and this is NOT depends of my current commit.
3. the same code for whole-body animations which I suggested some time ago. I remind you of one problem with that: when accum root of the animation system doesn't have active animation (mPlaying = true) than updatePosition isn't called. That causes bug - body pos desync - when holding lmb while attacking and sneaking/jumping. The solution I suggest is just launching infinite minAttackToMaxAttack animation play with speed = 0. The other solution I tried was adding some additional loop through all mStates in animation::runAnimation if accumRoot wasn't updated, but that gave some fps loss (e.g. 220 -> 204).

### CODE REVIEW

**Comment by ghost** [comment]
Regarding 2. no that can't be right either. In vanilla, if you change a creature's speed attribute via the console then you can actually see the creature will move faster.
Have you tried speedmult = mMovementSpeed; ?
Edit: Probably more like mMovementSpeed / (some constant)

**Comment by ghost** [comment]
The ascended sleeper issue is known already: http://bugs.openmw.org/issues/888

**Comment by mrcheko** [comment]
OK, I deleted those incorrect changes. Tried some tweaking with creature speed but didn't get satisfying result. Assumption about speedmult = 1.0 showed out to be false. Also tried mMovementSpeed / 100.0 -> it works rather good but cliff racer & netch_betty fly like mad then. We need someone to measure actual movement velocities in MW to analyse.

For now these commits: make actual movement to work in tandem with movement animation, and enable full-body attack animations for npcs.

**Comment by ghost** [comment]
Actually it looks like there is a bug with Creature::getSpeed for flying creatures:

```
    else if(mageffects.get(ESM::MagicEffect::Levitate).mMagnitude > 0 &&
            world->isLevitationEnabled())
```

It only considers levitation as flying. There is a missing check to isFlying(ptr).

If that gives good results with speedmult = mMovementSpeed/100.0, then let's use it?

**Comment by mrcheko** [comment]
I just checked, for creatures who currently move with normal speed this gives unwanted speed boost.
So the formula should depends on animation velocity

**Comment by ghost** [comment]
Yeah, only that making it depend on animation velocity makes some creatures way too slow compared to others.
So back to square one, I guess.
I'm wondering if there might be a flag somewhere that specifies if the movement velocity is animation-controlled.

**Comment by ghost** [comment]
> !mAnimation->hasAnimation("death1") identifies 1st person mode

This seems like a bad idea. Someone mod could add more animations.
It would be better to remember the return value of Animation::getVelocity that is being called earlier (when starting to play the movement animation), then use that to check for animation-controlled velocity.

> if(mMovementSpeed > 0.0f && (vel=mAnimation->getVelocity(mCurrentMovement)) > 1.0f)

**Comment by mrcheko** [comment]
1 line at https://github.com/mrcheko/openmw/commit/a6be72673c26f75b4e5ac1291263979cb4cd25d6#diff-103de9bfadb4d741a045c08adb25a557R1243

**Comment by ghost** [comment]
Looks good. Thumbs up.

**Pull request merged**
