### PR TITLE
Advanced journal, dialogue history rewrite

### PR DESCRIPTION
**Pull request by ghost**
Dialogue history was rewritten to use the new text rendering and keyword search modules. This fixes http://bugs.openmw.org/issues/537 , http://bugs.openmw.org/issues/733 and removes a lot of ugly code.

There's a couple minor journal issues left, which might be non-trivial to solve, I would add separate issues to the tracker for them if this gets merged.
- [Journal backend] Quest names are unavailable (index shows id, pages show nothing)
- [Journal backend] The name of the NPC that spoke on a particular topic is not available
- [Journal backend] Quest completion status unavailable
- Extra space in front of topic links. There is only report of this happening, not sure what causes it
- Possible performance issue for big journals, since the layout is recreated every time the journal is opened. In a quick test, 14 pages took 4ms.

### CODE REVIEW

**Comment by zinnschlag** [comment]
Can we please get rid of the "using namespace"s that are all over the place? We just cleaned up apps/mwgui and I don't want this nonsense to be reintroduced. Also, there are still remains of the I-prefix-convention. Can we get them removed, please? Bugs me to no end.

**Comment by ghost** [comment]
Done.

**Comment by ghost** [comment]
That would make it less obvious where IFont and Colour are coming from. I think thats one of the reasons why 'using namespace' was removed in the first place.

**Comment by blunted2night** [comment]
Having those declarations at the top of the file should make it relatively easy to figure out where the identifier is coming from. I think the ban on 'using namespace' was more about preventing naming collisions.

**Comment by zinnschlag** [comment]
Writing the namespaces explicitly in front of every identifier is making it even more easy to figure out where the identifier is coming from. Using declarations (e.g. using std::cout) are tolerated at function scope, but not encouraged (we actually have a wiki page about this topic: https://wiki.openmw.org/index.php?title=Other_Coding_Rules).

btw. merge incoming ...

**Comment by blunted2night** [comment]
so by that rational we should get rid of all typedefs too

**Comment by zinnschlag** [comment]
Nope. Typedefs do not primarily serve as a name shortener. Some people are using them in this function extensively, which is indeed a practise I do not agree with.
But typedefs also add an additional abstraction layer that can allow for example to switch out a compatible type without making changes to the source all over the place.

**Pull request merged**
