### PR TITLE
Proper main menu

### PR DESCRIPTION
**Pull request by ghost**
Plus some refactoring, a few minor fixes + savegame class name fix.

### CODE REVIEW

**Comment by ghost** [comment]
Updated: https://github.com/scrawl/openmw/commit/d7df9cae21dd4946901f01769a5f4f702cc01d09

While reading the Store code I noticed an issue with saving/loading of dynamic records.

ESMStore::mDynamicCount is not stored in the savegame, so if you restart OpenMW and load a savegame that already has dynamic records in it, mDynamicCount will be 0 - meaning the generated IDs of new records created will clash with the IDs of already existing records.

My first idea to fix it was to simply set mDynamicCount to countSavedGameRecords() after loading a savegame, however I just noticed that this could break in rare situtations when records are erased from the dynamic store, and as result mDynamicCount is (and must) be higher than the number of records.

So, I guess that leaves only the option of saving the mDynamicCount itself in the savegame. Any objections? 

Btw, the code that checks against duplicate insertions (eg in ESMStore::insert) has a bug and didn't catch this issue:

```
        if (store.search(x.mId) != 0) {
            std::ostringstream msg;
            msg << "Try to override existing record '" << x.mId << "'";
            throw std::runtime_error(msg.str());
        }
```

It should be checking against the generated $dynamic ID, not the ID supplied with the record to insert (which is not used anyway and most likely empty)

**Comment by zinnschlag** [comment]
Yes, we need to store mDynamicCount in the saved game file.

Good catch on the ID check.

**Comment by ghost** [comment]
Are you working on that or should I add it to issue tracker?

**Comment by zinnschlag** [comment]
If that was directed at me, please add it to the tracker. I currently do not plan to do more work on the saved game feature.

**Pull request merged**
