### PR TITLE
Videoplayback

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by zinnschlag** [comment]
Does not build for me: https://gist.github.com/4400561

Note that I am still using the MPG123 option, which disables the video playback feature. Have to look into setting up FFMPEG again (had problems with that before9, but assuming we don't want to get rid of the other sound options, OpenMW should at least compile with them.

**Comment by kcat** [comment]
Looks like I missed a couple function declarations when extending the decoders (though the definitions themselves exist). Currently rebuilding to make sure I got it right, then I'll get a pull request to scrawl.

**Comment by ghost** [comment]
Fixed 2 small problems and merged master.

**Comment by zinnschlag** [comment]
Are we ready for a merge into master now?

**Comment by ghost** [comment]
Sure.

**Pull request merged**
