### PR TITLE
bug #348 fixed

### PR DESCRIPTION
**Pull request by nikolaykasyanov**
I moved plugin loading to separate function in global namespace. I'm not sure if placing it in components is a good idea, so please correct me if I'm wrong.

Also plugin dir now always made absolute prior to loading.

### CODE REVIEW

**Comment by zinnschlag** [comment]
Fundamentally okay, but still needs a few fixes. First this can go into the files component. No need to make a new one. Also watch out for the file naming and make sure to put things into the right namespace. And while you are at it, merge in my master branch again to resolve a conflict.

**Comment by nikolaykasyanov** [comment]
hmm looks better now I think, but fails to compile because of

```
no member named 'loadAllFiles' in 'sh::Factory'
```

shiny problem?

**Comment by greye** [comment]
submodule update

**Comment by nikolaykasyanov** [comment]
no luck.
What version submodule update gives you on current master? For me it's https://github.com/scrawl/shiny/commit/5546a5bd8474ef328dfedae2df42126cdaf9515f

okay, now I see that git doesn't checkout correct commit =\

Looks like submodule commit change not merged in my branch for some reason, maybe because of origin url change.
So I hope it'd work when merged in master.

**Comment by greye** [comment]
https://github.com/scrawl/shiny/commit/164bc8d3bfe860bd16ad89c0bd1b59f465c9bb24 is active.

**Comment by nikolaykasyanov** [comment]
yep, already noticed. Check PM on forum please

**Comment by zinnschlag** [comment]
Does not build for me:

> /home/marc/OpenMW/openmw/libs/openengine/ogre/renderer.cpp: In member function ‘void OEngine::Render::OgreRenderer::configure(const std::string&, const std::string&, bool)’:
> /home/marc/OpenMW/openmw/libs/openengine/ogre/renderer.cpp:116: error: ‘absolute’ is not a member of ‘boost::filesystem’

**Comment by nikolaykasyanov** [comment]
what version of boost do you use?

**Comment by zinnschlag** [comment]
1.40. Still the standard version that comes with the latest Ubuntu LTS.

**Comment by zinnschlag** [comment]
> In file included from /home/marc/OpenMW/openmw/components/files/ogreplugin.cpp:1:
> /home/marc/OpenMW/openmw/components/files/ogreplugin.hpp:36:2: error: #error BOOST_VERSION

**Comment by nikolaykasyanov** [comment]
lol, forgot to remove this preprocessor directive =\

**Comment by zinnschlag** [comment]
Multiple problems. Adding stuff to other libraries' namespace should be avoided (and it's not working anyway; linkage problems). Also there seems to be something wrong with the submodules. I am getting:

> /home/marc/OpenMW/openmw/apps/openmw/mwrender/renderingmanager.cpp: In constructor ‘MWRender::RenderingManager::RenderingManager(OEngine::Render::OgreRenderer&, const boost::filesystem::path&, OEngine::Physic::PhysicEngine*)’:
> /home/marc/OpenMW/openmw/apps/openmw/mwrender/renderingmanager.cpp:75: error: ‘class sh::Factory’ has no member named ‘loadAllFiles’

after a submodule update.

**Comment by nikolaykasyanov** [comment]
I wrote about it above. Don't know what happened, seem submodule commit change not merged into my branch for some reason.

Regarding adding stuff to other libs' namespace — we already have couple of such places in codebase. What's the best way to solve absence of "absolute" in older boost? Add our own custom function calling "absolute" on new & "complete" on old?

We can use obsolete but existing "complete" function, but for someone boost can be compiled without deprecated functions (as for me).

**Comment by zinnschlag** [comment]
> Regarding adding stuff to other libs' namespace — we already have couple of such places in codebase.

That should not be the case. More cruft to clean up :(

> What's the best way to solve absence of "absolute" in older boost? Add our own custom function calling "absolute" on new & "complete" on old?
> We can use obsolete but existing "complete" function, but for someone boost can be compiled without deprecated functions (as for me).

I guess there is no good way to fix this problem.

Anyway, the submodule problem needs to be addressed first.

**Comment by nikolaykasyanov** [comment]
set appropriate version by hand

**Pull request merged**
