### PR TITLE
Spell buying menu

### PR DESCRIPTION
**Pull request by aehogan**

### CODE REVIEW

**Comment by zinnschlag** [comment]
Can't merge right now, because we have a regression in master (waiting for a fix). Looks good though. But please change the names. We already have SpellWindow and mSpellWindow. Going for SpellsWindow will only lead to confusion. Use SpellTradeWindow, SpellBuyingWindow or something similar.

**Comment by zinnschlag** [comment]
Regression fixed (at least on Linux). Your branch can be merged once the naming issue is taken care of.

**Comment by zinnschlag** [comment]
Oh, and don't forget to change the file names.

**Comment by aehogan** [comment]
Ok, everything should be good to merge now.

**Comment by zinnschlag** [comment]
There were a few minor and medium problems. I fixed most of them in my spellbuying branch (you might want to take a look at these commits, assuming you are planning to do more GUI work in the future). The only problem left is getting the spell list from the ESX record. I will fix that up next week.

**Pull request merged**
