### PR TITLE
Feature 122

### PR DESCRIPTION
**Pull request by ghost**
Fixes:

http://bugs.openmw.org/issues/122
http://bugs.openmw.org/issues/669

### CODE REVIEW

**Comment by zinnschlag** [comment]
Fixes 669, but not 122 (see issue description).

**Comment by ghost** [comment]
How so? I've tried coc instruction, and it works as in vanilla, i'm placed directly above the terrain. What's missing for 122?

**Comment by zinnschlag** [comment]
Water? Particularly for interior cells? I had at least one case where the player (when teleporting into a cell), was moved to a nearby location on "dry land" that did not match the location specified when teleporting).

**Comment by ghost** [comment]
Can't confirm that. If I do 

   player->positioncell 1340 3100 -250 0 "beshara"

in the Vanilla game, it places me underwater. Same result when teleporting to an exterior:

   player->position -16000 -76000 -250 0

**Comment by zinnschlag** [comment]
Odd. Do different water levels play a role in this?

**Pull request merged**
