### PR TITLE
Characterpreview

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by zinnschlag** [comment]
Having global preview objects is not a good idea. These are specific to certain GUI-elements and should be created and managed there. This will safe us from having to pollute the World interface with functions that don't belong there. Plus, eventually (post 1.0) we will need these kind of previews for other NPCs than the player (e.g. companion equipment window).

**Comment by ghost** [comment]
> This will safe us from having to pollute the World interface with functions that don't belong there

I agree about this but I need the access to scene manager etc. Which are not available from mwgui.

**Comment by ghost** [comment]
Maybe create them in RenderingManager, then pass them to the gui objects - but how?

**Comment by zinnschlag** [comment]
Crap. That is highly non-trivial. Need time to think about it.

**Comment by ghost** [comment]
Also, the race selection preview and inventory preview share the same node / entities (It would be waste to create even more of them). So they have to be created in the same place.

**Comment by ghost** [comment]
I could get the scene manager from the Ogre::Root singleton object:

SceneManager\* sceneMgr = Ogre::Root::getSingleton().getSceneManagerIterator ().begin()->second;

**Comment by zinnschlag** [comment]
The race selection preview and the inventory preview do normally not exist at the same time. In a normal gaming session the race preview will only exist for a short time or not at all. I do not see how they sharing anything can be useful.

What exactly do you need from OGRE. Only the scene manager?

**Comment by ghost** [comment]
Simply put, it's a waste of GPU memory (though not much, maybe). But you are right, race selection exists only for a short time so I can delete it completely when its hidden.
Yes I need only the scene manager.

**Comment by zinnschlag** [comment]
This calls for a more general solution, in case we need to rendering something else in the GUI in the future. Hang on, I think I have an idea.

**Comment by zinnschlag** [comment]
Have a look at my externalrendering branch. That should fix the problem once and for all. Just derive your previews from externalrendering and call World::setupExternalRendering to set them up correctly.

**Comment by ghost** [comment]
ok, ready.

**Pull request merged**
