### PR TITLE
Weather INI-import (fallback settings)

### PR DESCRIPTION
**Pull request by Glorf**
Here is the first part of fallback settings.

### CODE REVIEW

**Comment by zinnschlag** [comment]
Almost. There are still a few minor things related to your usage of C++ that should be corrected and one stylistic point:
1. When passing a string to a function you should normally do so as a const reference (as you have done in some cases, but not all)
2. Always prefer the prefix form of ++ and --, unless you need the postfix form.
3. Most of your new functions should be const.
4. Functions like atof do not belong into C++ code. You can either use a std::istringstream or boost::lexcial_cast.
5. Please avoid cryptic abbreviations like S, F, Clr (there is a section in our coding guidelines about that).

**Comment by Glorf** [comment]
Fixed. How about it now?

**Comment by zinnschlag** [comment]
Very close now. But the consts are still wrong. Returning a non-reference/non-pointer as a const is pointless most of the time. You need to make the functions const, not the return value.

**Comment by zinnschlag** [comment]
Also, you are still not passing string arguments as reference in some cases.

**Comment by Glorf** [comment]
Ok, done

**Comment by zinnschlag** [comment]
Mostly. I'll do the remaining fixes myself. Merge incoming ...

btw. please do not use tabs for indenting.

**Pull request merged**
