### PR TITLE
Fix compilation problem

### PR DESCRIPTION
**Pull request by nikolaykasyanov**
there is very big constant in ogre_nif_loader.cpp. Clang fails to automatically convert it to float.
Making constant explicitly float is ok, because f->timeStart is actually float.

### CODE REVIEW

**Comment by zinnschlag** [comment]
I don't agree with this solution (the original code was suboptimal too). Magic numbers like these should be avoided. I would try to use std::numeric_limits<float>::max() instead (from <limits>).

**Comment by nikolaykasyanov** [comment]
but max float isn't equal 10000000000000000, right?
I'm not expert in nif format, but maybe it's Morrowind-specific magic number?

**Comment by zinnschlag** [comment]
Or maybe not. I can't really make sense out of this piece of code. Is this value a part of the NIF file spec?

**Comment by zinnschlag** [comment]
Moving the discussion over to the forum (animation thread).

**Pull request merged**
