### PR TITLE
Stable CSM shadows + enhanced shadow filtering

### PR DESCRIPTION
**Pull request by mrcheko**
At some point I wanted shadows to become stable. So these commits is the result.
While exploring the problem I realized that we can't make shadows stable with constantly moving and rotating sun and player camera(also checked it in CryEngine 3.5 - they didn't achieve stability when light rotating, too). So I took idea from skyrim: shadows don't move during some short interval then they move fast to point where they should be if they would move constantly. When standing still shadows still have several pixels blinking but that can't be cured even with stable CSMs. It's now controlled from weatherManager (if u set mSunUpdateInterval to 0.0, u'll get old constant moving and shadow jittering).

Filtering: uses 16 samples instead of 4 earlier. And I can say 512 shadowmaps looks the most natural because they are the softest. Actually there is strange problem in shader results: small dots which don't calculate shadow factor for several neighbour pixels (only on terrain shadows! shadows on objects are ok). I don't know what cause it.

I also tried to set csm to 4 cascades but there aren't enough texture samplers in shader 2.0. So that 'outdoor split count' was added just for it. I would do shadow texture atlas for all 4 shadowsmaps, but don't know if it's possible in ogre system.
Also I don't know if shader will compile for glsl, though I've added 1 branching (frac() in hlsl, fract() - glsl)in it.

Any discussion is welcome.

### CODE REVIEW

**Comment by ghost** [comment]
Are you aware of this one? http://www.ogre3d.org/forums/viewtopic.php?f=11&t=71142 Looks pretty similar, maybe you can take some clues from it.

GLSL version is broken:
http://pastebin.com/4EkPr0HC

Also, there is a merge conflict (and I've had to mess with the header to get it to build with Ogre trunk)

**Comment by mrcheko** [comment]
This should work now. But I'm sure there is a trouble with terrain, some facts:
- if you remove that centroidUV's from shadow shader and just use input shadowMapPos, you'll have soft shadows on all objects without any artifacts while on terrain shadow is kind of reticulated;
- that dots with wrong shadow factor result are only presented on terrain;
- if u come close to a rock (e.g. near beshara entrance) and start to slowly looking from left to right u can see that ground near rock border slightly jumping

**Comment by ghost** [comment]
Still a build error (see travis log), and please fix the unsigned warning.

That aside, now it just freezes indefinitely when i attempt to enable split shadows. Backtrace shows its somewhere in driver (GLRenderSystem::_render). Plain shadows work. Hmm..

**Comment by mrcheko** [comment]
Check this. Also I suddenly noticed that those artifacts in GLSL are existent even on shadows on objects. Do you have any ideas how to eliminate this problem?

**Comment by ghost** [comment]
I have got around the freezing problem. It wasn't specific to your code, it also happens with the current PSSM. Seems to be an issue with Ogre 1.9 and onwards (ie trunk). Reverting to Ogre 1.8 fixed that. Will have to bisect to see what's going on. I'm guessing you used 1.8?

Anyway, now that its not freezing I just have no shadows at all (with your code), and no errors in the log either:
screenshot002

Disabling splits (or commenting out the #define STABLEPSSM) makes it work:
screenshot003

Any ideas?

**Comment by mrcheko** [comment]
Yes, I'm using Ogre 1.8. Both hlsl & glsl shaders compile and work. But the game crashes on attempt to change hlsl<->glsl at runtime. 
I have no access to code right now, but anyway I think there is a need to look how getShadowCamera() is called in Ogre::SceneManager, or maybe they changed getShadowCamera prototype (check if it actually gets in StablePSSMShadowCameraSetup::getShadowCamera) because even if u delete 'const' from it's prototype, Ogre will start to use default getShadowCamera.

Also found here: http://www.ogre3d.org/tikiwiki/tiki-index.php?page=GhadamonNotes:
- SceneManager: updateSceneGraph should happen BEFORE prepareShadowTextures. 
  also https://ogre3d.atlassian.net/browse/OGRE-105: it could be minGW problem.

**Comment by mrcheko** [comment]
I just tried Ogre 1.9 (downloaded latest source from https://bitbucket.org/sinbad/ogre/src). And it works the same way like in 1.8. All previous artifacts are presented, too :(.

**Comment by mrcheko** [comment]
I finally found the reason of those shadow artifacts - it was caused by anisotropic filtering starting from 2. You can look on those dot-artifacts (they are not so noticable though) on shadow-border on the top of pic and for anisotropic filter 0-1 everything is clear:
shadows_artif
So maybe disable anisotropic filtering for shadowmaps?

**Comment by mrcheko** [comment]
Hey scrawl, you still can't get stable pssm to work?

**Comment by ghost** [comment]
Nope.

**Comment by mrcheko** [comment]
I really believe that you have something broken with your Ogre build. Because I' ve already deployed whole system on another pc with ogre 1.9 and had it running as expected. Today I tried the latest Ogre 1.9 source (59986e4) and again it worked. Tried both with d3d and opengl.

Or it can be another thing: maybe you missed that I also modified settings-default.cfg (added "outdoor splits count = 3"), maybe you forgot to copy modified file to folder where it's used by executable? Or you can try to add that string directly into settings.cfg in documents folder in [Shadows] section.

**Comment by ghost** [comment]
Nope. Just did a clean build on my second machine. No change. As soon as I enable PSSM the shadows completely disappear.

**Comment by mrcheko** [comment]
could you please try these commits with current shadows.h (from materials) file and again with mine version? To understand if this problem arise from shader or from c++ code. 
Also also if you're using some specific configuration provide please yours *.cfg files.
And do you have original ogre pssm shadows working witn 1.9?

**Comment by ghost** [comment]
> could you please try these commits with current shadows.h (from materials) file and again with mine version?

No difference

> Also also if you're using some specific configuration provide please yours *.cfg files.

It happens with a clean config too.

> And do you have original ogre pssm shadows working witn 1.9?

Yes.

**Comment by mrcheko** [comment]
this potentially can make everything to work for you

**Comment by ghost** [comment]
Nope, that didn't do it :/ still the same result, enabled PSSM makes 
shadows disappear and no errors or exceptions whatsoever.

**Comment by mrcheko** [comment]
Hey, while you are not far away, I really believe this commit will change everything! :)

**Comment by mrcheko** [comment]
Hey, scrawl, didn't you check shadows after moving to Ogre namespace?

**Comment by ghost** [comment]
The namespace did not change anything.

**Pull request closed without merging**
