### PR TITLE
Jumping and misc physics fixes

### PR DESCRIPTION
**Pull request by kcat**

### CODE REVIEW

**Comment by zinnschlag** [comment]
That crashes for me:

openmw: /usr/local/include/OGRE/OgreVector3.h:193: Ogre::Vector3 Ogre::Vector3::operator/(Ogre::Real) const: Assertion `fScalar != 0.0' failed.
Aborted

**Comment by zinnschlag** [comment]
Not crashing anymore. But doesn't work too well for me. In the default starter cave, in the default starter position, there is a tunnel in front of you that leads downwards. If I go down this tunnel, the movement is stuttering very badly, while I had no problems there before.

**Comment by kcat** [comment]
Does it do that in first person and third person? I don't see the issue you're describing exactly, but I do remember seeing something that seems similar down near the door to the Ald Sotha Shrine (to the actual shrine with the statue). But it only happened in first-person while in werewolf form. Third person werewolf was fine, as well as first-person and third-person non-werewolf, and I never saw it happen anywhere else.

Currently rebuilding with latest master merged in to double-check, but I don't really know what can be going on. Maybe floating point precision issue? What's your framerate like when it happens?

**Comment by zinnschlag** [comment]
High FPS, no drops. Both 1st and 3rd person affected. Did some more testing. Happens throughout multiple interiors, but have not been able to reproduce it in an exterior so far.

**Comment by kcat** [comment]
This helped for me by the door I had issues with. Does it work for you, now?

**Comment by zinnschlag** [comment]
Marginally better in some places, but still game breaking.

**Comment by kcat** [comment]
What's your actual FPS? I'm finding it odd that a higher FPS seems to be the main cause for this issue since a higher FPS means less per-frame movement, which should then require less physics iterations rather than more.

I can only imagine the problem with the smaller time steps is it causing issues with the floating point math. How well does it work if you disable collision (tcl in the console)?

**Comment by zinnschlag** [comment]
I think we are on to something here. I did a limited test and it seems there is indeed a correlation between this problem and the framerate. Up to 60 or so there doesn't seem to be a problem at all. But when reaching about 90-100 the stuttering gets very bad.

No stuttering at all with collisions disabled.

**Comment by kcat** [comment]
Okay. Then I think what I need to do is basically replicate how Bullet itself does physics for dynamic objects. Essentially you only do physics at 60fps, and then predict and interpolate when in-between two physics "frames".

This can make things a little tricky for interaction between physics and logic though, since physics will, for a short time, be predicting based on "old" data. A prediction can be invalidated on the next frame when it makes another (possibly different) prediction to interpolate with. This is a case where having a fixed timestep for logic updates would be really useful, as the physics update could sync with the logic update so that any predicted physics won't "poison" the logic.

For simplicity's sake, I could also just avoid trying to interpolate physics for now and just do the fixed timestep. That would be the quickest and most efficient solution. A fixed timestep would be useful for other reasons as well, and it should be possible to implement it even when using Ogre's rendering loop (like we do), so if you want, I could try that.

**Comment by zinnschlag** [comment]
Quick and efficient sounds good. Since we are still planning to get out at least an 1.0 beta this year, we are somewhat running out of time and a we should avoid more elaborate solutions for now, unless they are absolutely needed.

**Comment by kcat** [comment]
Doesn't look like I'll be able to get a fixed timestep anytime soon. I got it to work, but performance dropped noticeably... I guess there's some code that doesn't like being locked at a constant 60 updates per second, so that will either need to be cleaned up, or moved away from the logic processing.

So instead, I just did what everything else does when it wants to limit updates. The NPC/player physics won't update more than 60 times a second, but will scale to less like it normally does. This can all be cleaned up with a proper fixed timestep, but that will require more performance measuring and code refactoring which honestly I don't think is needed right now (definitely something to do eventually, but it's not needed to get this physics work done).

**Pull request merged**
