### PR TITLE
Issue #221, NPC Dialogue Window Enhancements

### PR DESCRIPTION
**Pull request by artorius**
The only thing that I have been unable to do, is get the border right in the top. Someone else may need to try it, but everything else is in line with vanilla morrowind:
1. resizable window
2. moveable window
3. dialogue window is lower on the screen
4. window is shorter
5. transparent window

### CODE REVIEW

**Comment by artorius** [comment]
I noticed that some dialogue topics were longer than the topic list window.  However, the type of widget used to display the list of topics does not contain any word wrapping features.  To work around this, I made the topic list box a little wider to accommodate most long topics that I see.  If this pull request is accepted, I'll upload the new changes after that with the wider topic list window.

**Comment by zinnschlag** [comment]
Widening the topic list pane isn't really fixing the problem, since new plugins can always add longer topics (and even Morrowind.esm files in other languages can have longer topics. I am not entirely sure what MW does here, but the correct solution would be to make the division between the topic list and the main text panel movable (horizontally) or add a horizontal scroll bar to the topic list (when needed). Or both.
We can make this into a separate issue that is addressed later or you could try to improve the GUI further now.

**Comment by ghost** [comment]
I can try to add a scrollbar to topic list.

> The only thing that I have been unable to do, is get the border right in the top
> Can you explain what you mean with that?

**Comment by artorius** [comment]
Ok, then do you want to take what I have and then scrawl could add the horizontal scroll bar to the topic list?

**Comment by ghost** [comment]
I've checked your branch but the dialog window doesn't look like a window (there's no title bar). Have you pushed your latest work?

**Comment by ghost** [comment]
nevermind, I'll start from scratch. A large portion of your changes is incorrect.

**Comment by artorius** [comment]
Yeah, that's the part I can't figure out.  The NPC's name shows up there, but I can't figure out how to get the graphics to show up on either side of the name.  I would like to continue working on it, but I wanted to push this since the vast majority of the window looks closer to original morrowind now.

**Comment by artorius** [comment]
What's incorrect about what I did?

**Comment by ghost** [comment]
You changed a lot of unnecessary stuff (and some of them might cause problems at other places), while the needed changes was only a few lines. Just let me handle it.

**Comment by artorius** [comment]
fine, you could have just told me what not to change, and I would have worked on it.  You have bigger things to work on, I just wanted to lend a hand.

**Comment by ghost** [comment]
I appreciate your work of course (which also allowed me to do it faster now) but the needed changes were so minimal (see my pull request) that it was a 2 minutes thing to do them myself in a more proper way.

**Comment by zinnschlag** [comment]
fixed with another pull request

**Pull request closed without merging**
