### PR TITLE
Bug #900 fix for Ai wander

### PR DESCRIPTION
**Pull request by cc9cii**
Only tested with windows x64.  AiCombat will probably need a different algorithm to allow multiple enemies in combat range.  AiTravel may be similar to AiWander but probably need to cater for change of cell situation.

### CODE REVIEW

**Comment by cc9cii** [comment]
Please note that I'm about to submit an alternative solution, which is a little cleaner but doesn't mimic the vanilla behaviour as well as this one.  Only _one_ of the two alternative should be used.

**Comment by zinnschlag** [comment]
Let's wait for that than. We can keep this pull request open, so we can easily compare the two methods.

btw. this line:

>  ESM::Position updatedPos = actor.getRefData().getPosition();

looks odd. You are getting the position and then throw it away without using it.

**Comment by cc9cii** [comment]
Oops, good pickup - copy/paste error from an earlier edit.

EDIT: The alternative solution of modifying MovementSolver::move() isn't really working out very well.  Trying to move enough distance without keeping states over multiple frames makes the animation look strange.  Getting that done may take some time.  In the mean time I'll commit the fix for above error plus a couple of rather embarrassing typos.

**Comment by zinnschlag** [comment]
So your opinion is that we should drop the alternative solution and merge this one instead?

**Comment by cc9cii** [comment]
Yes please.

**Pull request merged**
