### PR TITLE
Guiconvience

### PR DESCRIPTION
**Pull request by sergey-shambir**
Minor fixes in GUI behavior

### CODE REVIEW

**Comment by zinnschlag** [comment]
The plan was to store window state in save files instead.

**Comment by sergey-shambir** [comment]
last commit reverted

**Comment by sergey-shambir** [comment]
Are there some issues in updated commit?

**Comment by zinnschlag** [comment]
No. Just with github. Somehow something went wrong with the pull request update and the resulting notification. I will review the pull request today. Sorry for the delay.

**Comment by zinnschlag** [comment]
Oops. Accidentally merged before it was ready. git and I do not agree with each other today.

Two problems:
1. When opening the class menu, the first item in the class list is selected, but the okay button is still disabled (I did not test the race menu, but I presume it is the same there).

2..BALANCE_CHANGE_INITIAL_PAUSE and BALANCE_CHANGE_INTERVAL are not okay. We use all-uppercase names exclusively for macros.

**Pull request merged**
