### PR TITLE
Multiple esm esp

### PR DESCRIPTION
**Pull request by mark76**
This is the current state of the branch for multiple plugin support, offering the following features:
- Load multiple master/plugin files, as defined in the config file/selected in the launcher. The code will now verify that all dependencies are fulfilled independent of the launcher.
- Add, overwrite and remove records by plugins.
- Add, modify and delete references that have been defined by parent plugins. This includes moving references across cell boundaries.
- Implement multiple terrain palettes, one palette per plugin.
- Some hotfixes for more advanced data merging problems that will be addressed later.

Since I won't be able to work on it for the forseeable future due to Real Life complications (as already told on the forum), it should enter the main branch now; the code seems to be sufficiently stable in doing the above points. (I should still be able to do minor requests, it's just new stuff that I don't have the energy to do right now.)

### CODE REVIEW

**Comment by zinnschlag** [comment]
I am sorry, but  do not agree with the data structure changes. Using a map is the wrong way to go. We do not need refnum access anywhere, but during cell load. Forcing a much less efficient data structure on the rest of OpenMW does not make sense (list might also not be optimal, but there was still room for improvements by trying out a deque instead).

**Comment by zinnschlag** [comment]
Merged into next instead.

**Comment by ghost** [comment]
The merge of this branch seems to have caused a performance regression (from about 70 to 20 fps in beshara). @mark76 Do you any idea about this?

**Comment by mark76** [comment]
Just tested it myself. When I launch the game with just Morrowind.esm 
loaded, I get around 60 fps in Beshara. Loading with Tribunal.esm 
enabled does a slight performance hit. Loading with Bloodmoon.esm 
enabled drops fps to 10 fps - did you enable Bloodmoon as well, or does 
it happen with only Morrowind enabled as well?

If Bloodmoon is the culprit, I would guess it is due to Bloodmoon.esm 
causing about 20 "distant" cells on Solstheim going active on boot. 
Probably a side effect of Bloodmoon introducing some custom global 
scripts, and the script engine preloading these cells as well. I have 
not looked into what is running per frame, but that's my best guess for now.

In this case, we would have to rework some background stuff that was 
simply not required with only Morrowind.esm being used.

**Comment by zinnschlag** [comment]
> If Bloodmoon is the culprit, I would guess it is due to Bloodmoon.esm causing about 20 "distant" cells on Solstheim going active on boot. Probably a side effect of Bloodmoon introducing some custom global scripts, and the script engine preloading these cells as well. I have not looked into what is running per frame, but that's my best guess for now.

That does not make any sense. There might be a delay when these cells are accessed for the first time. But beyond that, nothing time consuming happens in inactive cells. And these cells you have mentioned are definitely not going active. They are loaded. That is all.

**Comment by ghost** [comment]
The bottleneck seems to be in MWWorld::getPtr. I did a callgrind run with and without bloodmoon. Running with bloodmoon causes about 40% of time being spent in MWWorld::getPtr. After removing bloodmoon and running again, MWWorld::getPtr did not even appear anymore (close to 0%, I guess).

**Comment by zinnschlag** [comment]
Interesting. Do you have any more profiling data? World::getPtr is a rather complex function.

**Comment by ghost** [comment]
I have uploaded the callgrind output (7mb): http://scrawl.bplaced.net/temp/callgrind.out.26372
You can view it for example with KCachegrind.

**Comment by zinnschlag** [comment]
Very strange. I was able to improve the performance by increasing the ID cache size a bit. Seems the addons have more badly written scripts. I am not sure if that is the entire problem though.

The cache size is set in the constructor of MWWorld::Cells (cells.cpp); currently 20.

**Comment by mark76** [comment]
Well, it did't make much sense to me either, so I did some more testing 
as well. Bloodmoon introduces a start script called "BMStartUpScript", 
which basically consists of many, many lines (>50) of the type 
"RefID->disable". Whenever there is no active cell containing an 
instance of "RefID", I am under the impression that the enmgine tries to 
make one (which is why I am getting about 17 lines saying "loading cell 
'Solstheim, Chamber of Song'" and similar).

I have debugged the following bits: "Solstheim, Chamber of Song" 
contains the activators "Act_BM_steam_01" to "_06". These references are 
persistent. Now, when the start stcipt tries to mess with these 
references, I get lots of lines "loading cell 'containing this 
reference'". Many of the other cells claimed to be loaded on boot (or 
not?) seem to be related to the Raven Rock quest line, or the Werewolf 
attack at Fort Frostmoth, i.e. regions where many things are 
dis/enabled. Why using a start script instead of attaching scripts to 
the individual activators (as used e.g. by the Great House stronghold 
quest lines) is beyond my understanding.

As I do not have any experience with the script engine, this is all I 
can add now. For convenience, I have attached the BM start script which 
might be responsible to this message.

Am 09.02.2013 23:20, schrieb Marc Zinnschlag:

> Very strange. I was able to improve the performance by increasing the ID
> cache size a bit. Seems the addons have more badly written scripts. I am
> not sure if that is the entire problem though.
> 
> The cache size is set in the constructor of MWWorld::Cells (cells.cpp);
> currently 20.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/zinnschlag/openmw/pull/549#issuecomment-13339913..
> 
> Begin BMStartUpScript

StartScript wereCheckScript
StartScript bloodmoonScript

;to fix Tribunal stuff
if ( GetJournalIndex TR_DBAttack < 30 )
    StartScript dbFixScript
endif

;for Colony disables
if ( GetJournalIndex CO_11 < 60 )
    if ( ColonyState < 20 )
        if ( GratianGuard == 0 )
            "Gratian Caerellius_guar"->Disable
        endif
        if ( AferGuard == 0 )
            "Afer Flaccus_guard"->Disable
        endif
        if ( GarnasGuard == 0 )
            "Garnas Uvalen_guard"->Disable
        endif
    endif
endif

if ( GetJournalIndex BM_Smugglers < 10 )
    "Gaea Artoria"->Disable
    "Saenus Lusius"->Disable
endif

if ( GetJournalIndex BM_Bearhunt1 < 10 )
    "rolf long-tooth"->Disable
    "sattir the bold"->Disable
    "grerid axe-wife"->Disable
endif

;for BM_Smugglers
if ( GetJournalIndex BM_Smugglers < 10 )
    "mus roscius"->Disable
    "sorian"->Disable
    "mol gro-shat"->Disable
    "mazorn gro-gar"->Disable
    "gualtierus spurius"->Disable
endif

;for BM_Trees
if ( GetJournalIndex BM_Trees < 100 )
    Act_BM_Tree_01->Disable
    Act_BM_Tree_02->Disable
    Act_BM_Tree_03->Disable
endif

;for BM_WildHunt
if ( GetJournalIndex BM_WildHunt < 85 )
    bm_hircine_huntaspect->Disable
    bm_hircine_straspect->Disable
    bm_hircine_spdaspect->Disable
    bm_hircine2->Disable
endif

if ( GetJournalIndex BM_WildHunt < 100 )
    bm_ex_iceberg_collapsed->Disable
endif

;for BM_Stones

if ( GetJournalIndex BM_Stones < 10 )
    Act_BM_Wind_parts->Disable
    Act_BM_Earth_parts->Disable
    Act_BM_Water_parts->Disable
    Act_BM_Beast_parts->Disable
    Act_BM_Sun_parts->Disable
    Act_BM_Tree_parts->Disable
endif

;for BM_Earth

Act_BM_steam_01->Disable
Act_BM_steam_02->Disable
Act_BM_steam_03->Disable
Act_BM_steam_04->Disable
Act_BM_steam_05->Disable
Act_BM_steam_06->Disable

;for BM_Trial
if ( GetJournalIndex BM_Trial < 70 )
    BM_wolf_caenlorn1->Disable
    BM_wolf_caenlorn2->Disable  
    BM_wolf_caenlorn3->Disable
endif

;for BM_FrostGiant2
if ( GetJournalIndex BM_FrostGiant2 < 10 )
    bm_ex_karstaag_dooropen->Disable
endif

StopScript BMStartUpScript

End BMStartUpScript

**Comment by zinnschlag** [comment]
Yeah, that is pretty much what I have figured out so far. We had the same problem with Morrowind.esm. Very shoddy scripting. A while back I introduced an ID caching mechanism, that mostly got rid of the performance drop in Morrowind.esm. I am still waiting on feedback from people regarding my proposed fix/workaround.

**Pull request closed without merging**
