### PR TITLE
Issue912

### PR DESCRIPTION
**Pull request by sirherrbatka**
I hope everything is fine now.

### CODE REVIEW

**Comment by zinnschlag** [comment]
Looks good, but we are still missing the non-string-ID type UniversalID types (argumentless and index-based). The former we definitely need, the later would be nice to have for the sake of completeness (and that would us also allow to add an option to put the type icon into the subview titlebar).

Merge incoming ...

**Comment by sirherrbatka** [comment]
I have no idea how those should look :(

**Comment by zinnschlag** [comment]
Well, there was a paragraph in the issue descriptions that handles most of the non-argument types (record tables vs individual records). I don't know what to do about these either yet. We need to figure that out. Same really for the rest of the types.

**Comment by sirherrbatka** [comment]
We could use the same icon for table as for record, but with some kind of distinctive feature (like border, or background).

Let's discusse this on the forum.

**Pull request merged**
