### PR TITLE
Bug #437 better fix and Bug #430 "Teleporting and using loading doors linking within the same cell reloads the cell"

### PR DESCRIPTION
**Pull request by emoose**
Better fix for #437, only pauses RenderingManager now and still updates mOcclusionQuery
Also fixed #430 for interiors, not sure where/how to test exteriors though..

### CODE REVIEW

**Comment by zinnschlag** [comment]
Nope. Water and sky are still moving.

For future reference, please do not mix multiple features in the same branch. Also, please have a look at the developer documentation at our wiki, in particular the Policies and Standards page (which mentions among others the branching issue).

**Comment by emoose** [comment]
That's weird, they both pause for me. Are you sure you're applying the changes properly? I've tested by opening console while in Vivec and Beshara and in both places the sky/water paused.

Sorry I must have missed that page. After spending hours reading up the dev environment page and trying to build on windows/ubuntu/debian (eventually working with dualboot debian) I was kinda annoyed with the wiki lol. I'll read up on  it now.

**Comment by zinnschlag** [comment]
Strange. Sky seems to be paused now indeed. Do different weather types matter? Not sure. Water is definitely still moving.

**Comment by ghost** [comment]
Well it only worked for shader based water, not the fallback one. I've solved it, will make a pull request in a sec.

**Comment by zinnschlag** [comment]
Already merged

**Pull request closed without merging**
