### PR TITLE
Refactor wm

### PR DESCRIPTION
**Pull request by f3rno**
Hey Zini, I think I'm just about finished with refactoring the window manager. Take a look at it and let me know what you think. I basically just moved all of the character creation code into a new class, so there really isn't anything new.

As for the regression you mentioned in that forum post, it doesn't seem to be an issue after refactoring (I haven't tested the original window manager for that bug though)

Sorry for taking so long; I was technically done with this 2 days ago, but life got in the way of things.

EDIT: The initial pull request was pointing at the wrong branch; I fixed it this time around =]

### CODE REVIEW

**Comment by zinnschlag** [comment]
From a first look it seems okay. I probably won't be able to do any OpenMW work today, but will test tomorrow. If you happen to have some spare time before that, could you also have a look at the naming conventions (see wiki)? The original code ignores these completely (to be fair, I think it was written before we had any formal naming conventions). Please only change the new class. With more work on the WindowManager going on at the same time, changing the naming scheme would probably be to disruptive.
This is not a requirement for the task though. If you don't get the naming scheme fixed in time, I will merge the branch as it is.

**Comment by f3rno** [comment]
Okay, I'll take a look at it. Once I make the new commit though, what do I do with this pull request? Do I close it and open a new one to include the 4th commit?

**Comment by zinnschlag** [comment]
Just add a comment. I should get a notification.

**Comment by f3rno** [comment]
Done; I also cleaned up window_manager.hpp a teeny bit more (it had redundant private:/public: sections, so I combined them). charactercreation.cpp should be up to the wikis standards now. Also, I couldn't reproduce the regression mentioned on the forums, can you confirm it's gone in this branch?

And the commit appears to have been added automatically to this pull request.

**Pull request merged**
