### PR TITLE
Enchanting mechanics

### PR DESCRIPTION
**Pull request by pakanek**
This is better formula for cost of enchantment with precision of 1pt but that is probably caused by rounding in vanilla. Calculation of multiple effects enchantment doesn't work yet. There are other problems in Enchanting class and enchanting GUI window. I will work on this further.

### CODE REVIEW

**Comment by zinnschlag** [comment]
Please review our naming conventions again (see wiki) regarding enums. Also, if you are defining enums, you should also make use of them (at least in one spot you are comparing against an integer instead of the enum.

**Comment by pakanek** [comment]
Sorry, missed enum name. However I revised only method calculating enchantment cost. There are still many places which use magical constants - I will also adress that. It's spread across whole enchanting class and on some places of enchanting window. For now I am pushing just better formula.

**Comment by zinnschlag** [comment]
Okay. Let's keep this pull request open. You can add to the same branch and once you are done, add a comment to the pull request. That will bring it up in my feed and we can have a merge.

**Comment by pakanek** [comment]
Note, nextCastStyle method must be rewritten, so I will replace magical constants while doing it.

**Comment by pakanek** [comment]
This is probably all for now. Enchant and cast costs in enchanting seems to reflect vanilla. You can merge.

**Comment by Glorf** [comment]
Please, check bugtracker before you code something. I was working to get proper values there for whole day. Anyway, great work, but your values are still wrong. Take a look on my commit https://github.com/Glorf/openmw/commit/5d6c2b44f2c3388565dc40f53253dd4db28d3ce8 (tested, values equal to vanillia), and fix it.

**Comment by pakanek** [comment]
Sorry, I started yesterday. Which values do you have in mind?

**Comment by pakanek** [comment]
Oh, I've just realized what you mean.

**Comment by Glorf** [comment]
1. getCastCost is float so you will have a value with comma. There is workaround to it in my code
2. workaround for something that is probably morrowind bug (documented it in enchanting dialog, just take a look)
3. my old enchanting code was checking for effect->mData.mFlags (enchanting.cpp, line 164). It was wrong, change it as in my commit.
4. ensure you've tested everything, It's strange that you haven't seen these long float numbers in cast cost value :D

**Comment by Glorf** [comment]
One more thing, ensure that your tabulator is equal to 4 spaces (I've found only two in some parts in your code eg. in getCastCost)

**Comment by zinnschlag** [comment]
> One more thing, ensure that your tabulator is equal to 4 spaces (I've found only two in some parts in your code eg. in getCastCost)

This could be misunderstood. Do not use tabulators. At all. Instead indent by 4 spaces per level.

btw. the enum naming style still doesn't match entirely (CastingStyle_ instead of CS_ please).

**Comment by pakanek** [comment]
1. Display of floating value should be correct now.
2. mEnchanter is not meant to point to the player if he is not selfenchanting. That I judge from use of boolean mSelfEnchanting. If you use service provider for enchanting, it will point to service provider.
3. Yes, it was necessary only for retrieval of base cost so I removed it.
4. Maybe there were some commas but I have pretty narrow focus, so I've didn't seen them.

For your formula it's same as mine, but it divides (skill - 10) by 100 in addition to my formula. My works fine - I tested it with vanilla. Note that it is not possible to set enchant skill over 100 with SetEnchant in console.

For tabs ... seems like default in Eclipse :( I've removed them with expand cmd. Frustrating.

**Comment by pakanek** [comment]
Add 3. I mean that effect was necessary for that ... I know what was wrong with these flags.

**Comment by Glorf** [comment]
2) Unfortunately, it works this way in Morrowind. Just set your enchant to eg. 200 and then check cast cost of enchanter's service. It changed! There are some things like that in Morrowind engine, nobody expect this behaviour, but it happens.

It's not possible to setenchant>100... in openmw, now, but in Morrowind there is no such limit, so it could be changed one day, just "be prepared".

**Comment by pakanek** [comment]
I still do not follow you - what value should change? Nothing changed with enchant skill set to 200 nor 20000 in vanilla. Above enchant skill 109 casting cost (amount of charge lost with each use) is fixed to 1. 100 cap for enchant should be removed since it is easy to get it to 110 with constant enchantments on items.

**Comment by Glorf** [comment]
I mean that vanillia doesn't use enchanter's enchant level to calculate anything. It always use player's enchant level. So we can simply use player as enchanter everything.

**Comment by pakanek** [comment]
Isn't it used to get correct price from vendor?

**Comment by Glorf** [comment]
Nevermind, your code is good, I'm just very tired, I was talking about something that already was good implemented in your code. I haven't tested it, but it seems to be ready to merge.

**Comment by pakanek** [comment]
Prices differs for different service providers, so you need pointer to them. You can always get player pointer anywhere in source.

**Pull request merged**
