### PR TITLE
File system improvement

### PR DESCRIPTION
**Pull request by ananace**
Doesn't fail to find files on windows any more when dealing with the wrong type of slashes

### CODE REVIEW

**Comment by zinnschlag** [comment]
Does not work here:

Music Error: OGRE EXCEPTION(6:FileNotFoundException): Cannot locate resource Music/Explore/mx_explore_5.mp3 in resource group General or any other group. in ResourceGroupManager::openResource at /home/marc/Tools/ogre_src_v1-8-0RC1/OgreMain/src/OgreResourceGroupManager.cpp (line 756)

And tons more of these.

**Comment by ananace** [comment]
Noticed that the directory iterator is only sorted by default on windows, should work now.

**Comment by zinnschlag** [comment]
Still fails (NIFLoader: Warn:File not found). Note that this happens on the Redemption esm file, not Morrowind. I assume the problem here is that files are not in a bsa, but somewhere on the file system and somehow your changes are interfering with that.

**Comment by ananace** [comment]
When you say that it happens on Redemption, does that mean it works on normal Morrowind?
Haven't been able to replicate it yet, but I'm setting up a Linux build to see if that helps.

**Comment by zinnschlag** [comment]
It works on normal MW. But I assume that is because normal MW fetches its resources files from the BSAs while Redemption gets them from the filing system. I currently don't have a method to verify this theory. If you have your MW discs or an BSA extractor tool at hand, you could try to put the MW resources into the data directory and remove the bsa temporarily.

**Comment by ananace** [comment]
I found a problem, if no .bsa file exists then it never adds any data paths. I'll whip up a fix for this and see if that helps

**Comment by ananace** [comment]
With these changes I was able to run it from an extracted location, see if it works now.

**Comment by zinnschlag** [comment]
Nope.  Different error message though (NIFLoader: Warn:File meshes\TOEa\fl\jd_bushflower03.nif not found), ending with a segfault.

**Comment by ananace** [comment]
I assume the mesh in question really exists but can't be found by OpenMW...
To be honest I'm not quite sure how to go about fixing this as I don't know how to recreate the circumstances

**Comment by zinnschlag** [comment]
The file does exist and it is found without your changes. I assume a similar failure can be provoked on Linux by having any random combination of / and \ in the mesh file name inside an ESM record when the file is found in the filing system and not in a bsa.

**Comment by ananace** [comment]
Try now, that's the last thing I can think of at the moment.

**Comment by zinnschlag** [comment]
No change. btw. the segfault is in the physics system. Seems that missing meshes aren't handled properly. But that is a different issue.

**Comment by zinnschlag** [comment]
Narrowed it down. My theory was wrong. Nothing to do with / and . This is a case problem. The case of the requested file does not match the case of the filename on disc. I see the case handling in the bsa archive code, but it isn't working properly.
btw. I noticed a couple of new tabs (instead of spaces). I guess they are yours. Please avoid them.

**Comment by ananace** [comment]
See if this fixes the case problem.
Also, my editor is complaining about the mixed tabs/spaces in the file and wants me to replace them with all spaces, I think the tabs are from somewhere else.

**Comment by zinnschlag** [comment]
Somewhat better. But now I am missing tons of textures that were there before. Example: 

21:10:51: Error loading texture textures\Tx_Stars_Mage.tga. Texture layer will be blank. Loading the texture failed with the following exception: OGRE EXCEPTION(7:InternalErrorException): Error decoding image in FreeImageCodec::decode at /home/marc/Tools/ogre_src_v1-8-0RC1/OgreMain/src

Interestingly this seems only to affect textures of type tga. At least for some resources types MW can find files with a different extension than requested. I don't know if that is the case here.

**Comment by ananace** [comment]
That's strange, are you sure it's a problem with finding the file in question and not due to FreeImage failing to load a .tga?
On that note my clean morrowind install only has a .dds version of that texture, is the .tga version perhaps from the construction kit install?

**Comment by zinnschlag** [comment]
The tga is a custom texture.  And the error does not happen, without your changes.

**Comment by ananace** [comment]
Tell me if the debug output finds any not-matching files, I think I have an idea what is going on.

**Comment by zinnschlag** [comment]
Getting stranger and stranger. Here is the output: https://gist.github.com/2260835
Seems those files are found after all, but with your changes they still don't show up in game, while without your changes they are present.

**Comment by zinnschlag** [comment]
And here is the OGRE log from the same session: https://gist.github.com/2260843

**Comment by ananace** [comment]
How about a crazy theory, what if without my changes it fails to find the .tga versions of the textures and instead uses the .dds?

**Comment by ananace** [comment]
Try this one and see what happens, I think it might just be crazy enough to work.

**Comment by zinnschlag** [comment]
Your theory is not so crazy. And the textures are rendered now. Still doesn't look right, but it is hard to tell. There are still plenty of NIF features not implemented yet in OpenMW, which cause tons of rendering errors. I think we can stop here. If you clean up your branch (remove the debug output), it can be merged into master.

**Comment by ananace** [comment]
I'll just remove the tga check while I'm at it.

**Comment by zinnschlag** [comment]
That brought the missing texture problem back, unfortunately. But I am willing to believe now that this is actually a tga/freeimage problem. We will investigate that another time. Pushing now ...

**Pull request merged**
