### PR TITLE
Record saving next

### PR DESCRIPTION
**Pull request by greye**
Original esm are copied almost perfectly (except junk after null-terminator in fixed length strings and INGR fix).

### CODE REVIEW

**Comment by zinnschlag** [comment]
Need a bit more time to review this pull request. Merge could be delayed by a day or two.

**Comment by zinnschlag** [comment]
Okay, done with the review. Here are the problems I see:
- We do not want a common base class for record classes. This is currently of use nowhere else (neither in OpenMW not in the editor), adds at least 8-12 bytes per record and is inconsistent with the esm/esm_store components. From a design perspective I can see the point of a common base class, but if that is going to happen (post 1.0) it needs to be thought through properly and not hastily tacked on, just for the convenience of not having to implement per-record types containers in the ESMTool. The current Record class has already several problems. Not all record types have a string ID, so mId makes Record a fat base class (bad). And I can't see the sense behind mFlags at all. I am sorry, but I think Record has to go.
- Names starting with an underscore and an uppercase letter are reserved name in C++ (e.g. _ESM_RECORD_H). As an ordinary user we are not allowed to use them. I am aware that these are used in some other places in our code base and it is unlikely that they will ever give us any trouble, but let's try to make new code formally correct anyway.
- The function name getASCII is misleading, because the encoding we are dealing with is not ASCII. Maybe call it getLegacyEncoding instead?

**Comment by greye** [comment]
Well, okay in general. I only ask you next time to review code before advising to use it.

As as a counterproposal I may remove actual mId, mFlags members (adding them only when needed) and leave only interface. Why? It allows to cleanup esmstore (reclists at least) greately.

**Comment by zinnschlag** [comment]
I do not see how that would help to get a better reclist implementation. Note that the esm store is in for a partial rewrite anyway (probably several iterations). Any benefit that would apply to the current implementation might be irrelevant for a future esm store.

**Comment by greye** [comment]
It will allow to merge 4 templates into one (basic, case-sensitive, and 2 self-id-containing).

**Comment by zinnschlag** [comment]
I do not see how you could do that. These lists work differently, so you can't just merge them all into one.

**Comment by greye** [comment]
I think it deserves a separate thread for discussion, but: 1) case-insensitive search in any case, but storing case-sensitive keys as separate template for only record (not even pure class) and searching trough it sequentially (yes, linearity is exactly what we expect from binary tree with 2k elements) - I think it should be solved by storing case-sensitive keys always and using case-insensitive search on map. 2) storing id (and I think having different templates for case-senstitive and case-insensitive ids in records also somehow awful) can be mimicked with set/getId interface that does nothing where it shouldn't to be.

**Comment by zinnschlag** [comment]
> and I think having different templates for case-senstitive and case-insensitive ids in records also somehow awful.

I do not agree with this statement. These are using different key types with different lookup-mechanism and therefore justify separate implementations. I agree that having these differences in the first place is bad, but that is just how MW rolls.

Anyway, we are going off topic. Improving the record containers is orthogonal to the topic of a common base class for records. You could easily do one without the other (not that I see any sense in doing either at this point).

**Pull request closed without merging**
