### PR TITLE
Usersettings

### PR DESCRIPTION
**Pull request by joelgraff**
User Settings code for OpenCS

### CODE REVIEW

**Comment by zinnschlag** [comment]
Unfortunately this is somewhat inconsistent with the existing namespace and directory structure for OpenCS. And it looks like there may also be some problems with the integration into the UI. I will need a bit more time to review this pull request more thoroughly (probably finishing sometimes tomorrow).

**Comment by joelgraff** [comment]
No worries.  Namespace and file structure are easily fixed.  I don't doubt
there's a number of problems - I just hope there's nothing serious that I
can't fix in, say, a week or so...

**Comment by zinnschlag** [comment]
For some reason github refuses to properly deal with my comments (I guess they are too long). I will PM them to you on the forum.

**Comment by joelgraff** [comment]
Ok, I think this covers everything you outlined in your comments.  Let me know.

Thanks,

Joel

**Comment by zinnschlag** [comment]
Looks okay. Merge incoming ...

btw. I noticed those test settings are back in again. Can you please take them out?

**Pull request merged**
