### PR TITLE
Added new game button

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by zinnschlag** [comment]
I see 3 problems here:
1. You are killing the --new-game switch. We will most likely still need it, once we allow starting OpenMW from within the CS.
2. The code for handling the player record is not correct. As I read it, you are copying the player record back and forth between dynamic and static storage. That won't work, because you lose the original player record. You need to store it somewhere else.
3. The code for MWWorld::Cells::clear is unnecessarily complex and also adds a copy of the magic number 40. Instead of assigning a new vector to mIdCache you can just use std::fill.

**Comment by ghost** [comment]
> As I read it, you are copying the player record back and forth between dynamic and static storage.

No, that's not what it does.

On startup, the record is moved from static to dynamic (movePlayerRecord).
On each new game, clearDynamic is called which fetches a copy of the player record, then wipes the dynamic storage, and then re-inserts it into the dynamic storage.

**Comment by zinnschlag** [comment]
Yes. But where is it fetching this copy from? The ESM store. And since there is no static player record (which is absolutely correct), it is fetched from the dynamic storage and that means it has been modified (potentially). It is not the original record anymore.

**Comment by ghost** [comment]
Done.

**Pull request merged**
