### PR TITLE
Unshield CD Installer

### PR DESCRIPTION
**Pull request by wheybags**
What it says on the tin.
I'm no QT expert, so the gui is not very flashy, but someone (I think pvdk expressed interest at some point) can pretty it up if they want.

### CODE REVIEW

**Comment by zinnschlag** [comment]
There are a couple of issues with this pull request:
- Please review the naming guidelines on the wiki (in particular the part about file names and enums)
- Free static functions are outdated. Please use anonymous namespaces instead.

And could you please explain what the ini fix part is about?

**Comment by wheybags** [comment]
The enum stuff is copy pasted from unshield's main.cpp, I just used it because it worked, what would you like me to change about it, just the names?
Had a brain fart re: filenames, been a while since I contributed, thought underscores were the convention.
The fix ini part is mainly related to bloodmoon.
The bloodmoon installer has to add a bunch of entries to the ini file, but it patches the file instead of overwriting it.
The patches are contained in setup.inx, and I just pull the data out of there and put it into the ini I extracted earlier with Morrowind.

**Comment by wheybags** [comment]
Ok, that should fix it.

**Comment by wheybags** [comment]
Forgot about that

**Comment by psi29a** [comment]
Why are we including unshield? Shouldn't we be using this as an library since the package is already shipped on multiple platforms. I know the Debian/Fedora/Arch folks are going to complain about duplicated code, unless of course there is something new being done, in which case that should go upstream right?

**Comment by zinnschlag** [comment]
Good point.

**Comment by wheybags** [comment]
Unshield doesn't build on windows, so we'd have to write our own build system for it anyway.
Why not just use the system we already have?

**Comment by zinnschlag** [comment]
Do we need this feature on Windows? The user can just install MW there, right? And that also takes care of everything else, since OpenMW can auto-detect a properly installed MW. As I understand it, this feature is primarily intended for Linux and OS X. Hmm. OS X. I have no idea about the situation there.

**Comment by wheybags** [comment]
That is a good point.
If people want, I could remove unshield sources, and disable it for windows.
re: OSX, it uses autotools, so I think it'd be fine.

**Comment by zinnschlag** [comment]
Okay, let's try that.

**Comment by psi29a** [comment]
This should give us enough time to push the problem upstream for unshield to be fixed for windows. While it isn't a requirement, it 'would be nice to have.' Otherwise, great work. :)

**Comment by wheybags** [comment]
ugh, I thought cherry-pick wouldn't mess up history ;_;
I'll fix, sec

**Comment by wheybags** [comment]
Ok, That should do it

**Comment by zinnschlag** [comment]
Does not build:

CMake Error at CMakeLists.txt:525 (find_package):
  Could not find module FindLIBUNSHIELD.cmake or a configuration file for
  package LIBUNSHIELD.

Forgot to add a cmake file?

**Comment by wheybags** [comment]
I had FindLibUnshield.cmake, not FindLIBUNSHIELD.cmake
Worked fine on my machine

**Comment by wheybags** [comment]
Ok, the travis build hung on apt-get update before it ever got to anything influenced by me :S

**Comment by zinnschlag** [comment]
And now I am getting a build error:

/home/marc/OpenMW/openmw/apps/launcher/unshieldthread.cpp: In member function ‘void UnshieldThread::extract_cab(const boost::filesystem3::path&, const boost::filesystem3::path&, bool)’:
/home/marc/OpenMW/openmw/apps/launcher/unshieldthread.cpp:328:59: error: ‘unshield_open_force_version’ was not declared in this scope

**Comment by wheybags** [comment]
I don't get that error :S
I don't know why you are, the unshield header is included in unshieldthread.hpp, which is included in that file.
Is that function not in the unshield header you have installed?

**Comment by zinnschlag** [comment]
Nope. Not present. libunshield 0.6.2

**Comment by wheybags** [comment]
That should fix it.

**Comment by wheybags** [comment]
Travis seems to be broken :S
apt updates are stalling

**Comment by psi29a** [comment]
Sometimes a 'retry' is necessary, I've had apt-get updates fail as well.

**Pull request merged**
