### PR TITLE
Improved journal opening/closing sound playback

### PR DESCRIPTION
**Pull request by rohit-n**
Moved playback sounds to journalwindow.cpp, and play opening sound only if player has the journal.

### CODE REVIEW

**Comment by ghost** [comment]
This change is wrong. It will make the sound play when opening/closing the main menu while the journal is opened.

**Comment by ghost** [comment]
Now it's missing the sound when closing it using the hotkey.

**Comment by rohit-n** [comment]
What do you mean by hotkey? I can hear the sound when clicking the "Close" button and when pressing J.

**Comment by ghost** [comment]
Yeah nevermind, it's good. I didn't look at whole code.
Your indentation is wrong though, it needs to be 4 spaces.

**Pull request merged**
