### PR TITLE
Weather

### PR DESCRIPTION
**Pull request by pakanek**
Removal of some unnecessary string copying, type of weather type changed from string to enumeration. WeatherResult added as member variable since it has been de/allocated in each frame and it has ~25 floats+... inside. Weather probability calculation simplified and done with INTs instead of floats.

### CODE REVIEW

**Comment by pakanek** [comment]
There seems to be sigsegv, so wait with eventual merge.

**Comment by zinnschlag** [comment]
Could we please reverse the string to enum change? At some point we will have to move away from hardcoded weather types and instead have weather type records. That implies identifying weather types by a string.

**Comment by pakanek** [comment]
You can push weather names to vector/map and still retain speed of integers. Instead of 'switch' there would be some vector lookup. Since CPU usually waits for IO, it is better to avoid unnecessary data movements inside rendering of the frame. Strings are mostly needed during initialization. Even if you move to general weather settings, you won't "see" strings in code, they will be hidden behind some variable anyway.

But yes, if you won't change your mind - I will move it back to string.

Sigsegv isn't related directly to this pull request, it happens if I try to force instant weather change inside WeatherManager::setWeather() (to address Bug 417 - quick weather change after coc...) and coc (Balmora->Dagoth Ur->Balmora).

**Comment by zinnschlag** [comment]
I am pretty sure that speed is completely irrelevant here. OpenMW being bottlenecked by looking up weather strings would be more than a bit weird (I would need to see very solid profiling data before I am willing to believe that).

Anyway, as mentioned before weather will eventually get record status, which means it will go into the ESMStore. Integer/enums would work for now, but there is no way to do that once the de-hardcoding is completed since there simply won't be any integer/fixed weather values anymore.
Since we already had an interface that will (mostly) work with future enhancements, moving to a different one now would be a step back (even if it adds a small bit of performance).

**Comment by pakanek** [comment]
Profiling is about bottlenecks. Passing array, when you need just one value, is simply wrong. You don't need name of weather setting during rendering. Moving from fixed values to arbitrary number of weather settings is just switch from enum to INT, while enum is internally integer already. You simply store names of weather settings as you read them from settings/ESM_files and push them into vector/map ... then index of weather setting name inside that vector/map is your integer identifying it (value represented by Weather::Type enum for now). I don't see your problem here.

I don't want to spend much time arguing about this. If you don't want it, just tell me, I will remove String->Enum change.

**Comment by zinnschlag** [comment]
It is obvious that we won't come to an agreement here. So yes, please revert the change.

**Pull request merged**
