### PR TITLE
Compare string

### PR DESCRIPTION
**Pull request by trombonecot**
Found some (I don't know if all) comparstring and tolower functions and move them to components.

### CODE REVIEW

**Comment by zinnschlag** [comment]
There is a large number of merge conflicts. It should be able to have a look at it this weekend, but if you have the time to resolve them (by merging master into your branch) before that, be my guest.

**Comment by trombonecot** [comment]
I'll try to solve this out between today and tomorrow.

**Comment by trombonecot** [comment]
I have solved the conflicts I think. (Not a GIT expert...)

**Comment by zinnschlag** [comment]
Sorry, that doesn't even compile:

/home/marc/OpenMW/openmw/apps/openmw/mwscript/containerextensions.cpp: In member function ‘virtual void MWScript::Container::OpEquip<R>::execute(Interpreter::Runtime&)’:
/home/marc/OpenMW/openmw/apps/openmw/mwscript/containerextensions.cpp:168:60: error: there are no arguments to ‘toLower’ that depend on a template parameter, so a declaration of ‘toLower’ must be available [-fpermissive]

And tons more of that.

Also there is no components/esm_store/reclists.hpp anymore.

And it seems we have 3 toLower-like functions in components/misc/stringops.hpp now. Comparison is also redundant. I think we can get rid of the free functions toLower and stringCompareNoCase altogether. The implementation in Misc::StringUtils is pretty good (expect that it should be a namespace instead of a class, since it doesn't contain anything but static functions).

**Comment by trombonecot** [comment]
Oops, sorry. Between merges maybe something went wrong. Ill look into it.

**Comment by trombonecot** [comment]
changed, compiled and working. I've deleted the funciontons and used the ones you told me.

**Pull request merged**
