### PR TITLE
fix unclothed npcs for a few frames upon entering a cell

### PR DESCRIPTION
**Pull request by ghost**
Fix for issue 399 ("Inventory changes are not visible immediately"): http://bugs.openmw.org/issues/399

There were two reasons for this problem:
- Upon creating the NpcAnimation in MWClass::Npc::insertObjectRendering, the InventoryStore was not filled yet
- in NpcAnimation::update, there was a threshold of 0.2 seconds before any changes to inventory would appear

I have only removed the threshold, which fixes the problem.

### CODE REVIEW

**Comment by zinnschlag** [comment]
Did you check the performance impact on more heavily populated cells?

**Comment by ghost** [comment]
I did not notice any. But as always, its hard to say anything without profiling. However, it first checks if the inventory changed at all, so it should be ok.

**Comment by ghost** [comment]
Of course it would be best to have a listener called whenever inventory changes.

**Comment by zinnschlag** [comment]
Not keen on removing a performance optimisation, without knowing for sure that it won't cause problems. And the delayed equipping is not exactly a serious problem. We can have a go at it later (maybe even post 1.0). Once we improve cell changing speed by pre-loading cells before they are entered (important post 1.0 feature), it will go away anyway. Not merging.

**Comment by ghost** [comment]
> Once we improve cell changing speed by pre-loading cells before they are entered (important post 1.0 feature), it will go away anyway

Not if it is the first cell that is loaded, i.e. after starting up and loading the first save game.

> And the delayed equipping is not exactly a serious problem.

I ran into this problem when rendering the character preview; I update this preview whenever an item is equipped or unequipped. But the preview is always one item "behind", because the equipment change is not visible yet.

Would it be ok to add a "InventoryStore::setListener(InventoryStore::Listener\* listener)" method, and call "mListener->equipmentChanged() " in InventoryStore::equip ? Which would be implemented in NpcAnimation and would change a flag to update all parts in the next update.

**Comment by zinnschlag** [comment]
> Not if it is the first cell that is loaded, i.e. after starting up and loading the first save game.

That entirely depends on how the loading is implemented. Too early to make any predictions.

> Would it be ok to add a "InventoryStore::setListener(InventoryStore::Listener\* listener)" method, and call "mListener->equipmentChanged() " in InventoryStore::equip ? Which would be implemented in NpcAnimation and would change a flag to update all parts in the next update.

Let's not complicate things. You can make the delay configurable by adding a parameter to the NpcAnimation constructor. When used in a cell, the current value is used and when you use the preview, you just construct it with a value of 0.

**Pull request closed without merging**
