### PR TITLE
License

### PR DESCRIPTION
**Pull request by dougmencken**
You need to include license header in each copyrightable file.
See also: http://www.gnu.org/licenses/gpl-howto.html

### CODE REVIEW

**Comment by wheybags** [comment]
Honestly, I don't think it's really that important.

**Comment by dougmencken** [comment]
It is very important, because otherwise these files are not under GPLv3.

**Comment by wheybags** [comment]
This is just pedantry really in my opinion.

**Comment by zinnschlag** [comment]
> It is very important, because otherwise these files are not under GPLv3.

Have you any evidence for this statement? I know the FSF encourages this practice, but that in itself does not necessarily mean that the GPL license does not "work" without the boilerplate text. In fact most references I can find say it is redundant.

**Comment by ghost** [comment]
I can only see downsides to this. Also, you've mistakingly added the GPL notice to extern/_/_ which is incorrect, as they are under MIT.

**Comment by AMDmi3** [comment]
Explicit license note is always a good thing, especially if certain files are under different licenses.

**Comment by zinnschlag** [comment]
> especially if certain files are under different licenses.

Not really. The files in extern are not part of OpenMW. These are separate projects, of which we carry around a copy for technical reasons. This could be documented more clearly though (for example in the readme file).

**Comment by dougmencken** [comment]
Oops, I really forgot to check files for if-they-are-already-licensed after executing script with cat. Sorry.
These patches need to be re-written. I'm closing this request.
But how about the contents of license header? Is it okay or shall be modified somehow?

**Comment by zinnschlag** [comment]
I still haven't seen a reason why we should have them at all.

**Comment by dougmencken** [comment]
http://softwarefreedom.org/resources/2012/ManagingCopyrightInformation.html talks about file-level notices.

So the answer would be: It helps to avoid ambuiguity.
Imagine I get a program that contains no copyright or license information at all.
The only thing I see is a copy of, say GPL version 2.
Is this program licensed as GPL version two only? Or is it "any later version"?
Who are the copyright holder(s) and how might I contact them with questions?

**Comment by zinnschlag** [comment]
This all can be addressed in a centralized copyright notice. I still see no convincing argument for per-file boilerplate code.

**Pull request closed without merging**
