### PR TITLE
Container scripts

### PR DESCRIPTION
**Pull request by wheybags**
To address issues from the last pull request:

Setting the cell field of the ptrs:
They are never accessed apart from pointer comparison when removing, I can change this if needs be, but any other solution would be messy (maybe adding a second cell pointer called ContainerCell? ).

Moving an object from one cell to another:
I'm not entirely sure what you mean?
How would you do this, because I suspect it would actually work.

Deleted objects in containers:
The objects in the containers are iterated through using a ContainerStoreIterator, which I believe will skip over disabled items.

### CODE REVIEW

**Comment by zinnschlag** [comment]
> Setting the cell field of the ptrs:
> They are never accessed apart from pointer comparison when removing, I can change this if needs be, but any other solution would be messy (maybe adding a second cell pointer called ContainerCell? ).

What you are currently doing in this branch is breaking stuff. The function isInCell must return false, if the object is in a container. However we could implement that by inverting the logic of that function. Don't check if the cell pointer is not null and instead check if the container pointer is null.

> Moving an object from one cell to another:
> I'm not entirely sure what you mean?
> How would you do this, because I suspect it would actually work.

We do not actually move objects between cells. We use a copy and delete idiom. Is this properly handled (i.e. are scripts of objects in deleted containers removed and scripts of objects in the copied container added)? I think not. 
I guess the removal part should work. But what about the copying part? Or inserting a new (non-empty) container into a cell in general?

btw. could you rename realAdd to addImp please (more consistent with the rest of the code base).

**Comment by wheybags** [comment]
How can I insert a new non empty container?
I'll go try fix that, but I'm not sure how to test it :P.

**Comment by zinnschlag** [comment]
Move a container across a cell boundary.

**Comment by wheybags** [comment]
I believe those new commits address the issues you raised.

**Comment by zinnschlag** [comment]
Nope. Sorry. Please revert this change. It is not correct. Enabling and disabling does not affect scripts.

**Comment by wheybags** [comment]
lol wat
Ok, I  presumed it would, as it seems an overpoweringly sensible thing to
do :P.

**Comment by wheybags** [comment]
Ok, That should fix it.

**Pull request merged**
