### PR TITLE
Fixed commented code, added application icon to opencs

### PR DESCRIPTION
**Pull request by joelgraff**
Forgot to uncomment code in CSVDoc::Operation::setBarColor() in previous commit

Added application icon (openmw.ico) to opencs.  Also added /apps/opencs/resources/images tree; resources.qrc to /resources; openmw.ico to /images.

Don't know how to duplicate the /images/openmw.ico structure on github... :)  

Apologies if I'm just making a mess of things - could probably use a few protocol pointers. :)

### CODE REVIEW

**Comment by zinnschlag** [comment]
The actual icon is indeed missing. You can add it like any other file (git add). But can we have the resources directory (including the resources file) please in a subdirectory of files? files/opencs maybe?

**Comment by joelgraff** [comment]
Whatever you like.  I noticed the same structure under omwlauncher and just copied it.  You may want to reorganize that as well for consistency's sake.  Will try to get the opencs files moved and the resources.qrc XML updated asap.

**Comment by joelgraff** [comment]
Ok, this should take care of the directory structure for opencs resources.  ATM, resources.qrc, openmw.ico and openmw.png live in files/opencs.  opencs cmakelists.txt updated to point to the right place.

Startup dialog feature is maybe 50% complete...

**Comment by zinnschlag** [comment]
And here we have again the problem of a pull request, that mixes up various stuff (icon, bug-fix, startup). The infamous "Here is some useful stuff" branch. Please don't do that. Only causes problems for everybody. For example, even if wanted to I can't merge the bug fixes and the icon now, because that would also include the startup (see below).

Okay, back on topic:

There are a few problems:
1. You picked the wrong icon, I think. We have a custom one, somewhere in the icon thread.
2. We already have a startup dialogue (just ugly as hell and with only partial functionality). What you should do is enhance/fix it, not adding another one. Also, the way you are integrating it, is a bit more complicated than it needs to be (see the existing code). In particular there is no need for anything modal. And we definitely do not want to force this window to stay on top.

> //Dialog acts as a main window, here.  Should probably start the main window
> //as a view without a document, then display this startup dialog over it.

Definitely not!
1. I need a working startup dialogue for development and testing. That means I can not merge in your startup dialogue until it has at least the same amount of functionality as the current placeholder startup.

btw. I see you are using this-> for accessing member functions. We normally don't do that.

**Comment by joelgraff** [comment]
Yeah - the thought occurred to me after the fact about mixing fixes in a pull request.  Sorry about that.  Makes obvious sense.

opencs icon - is that plugin.png?  That's the only image file in the source that looks like it might be meant for the editor...

Regarding the startup dialog code - I'm afraid I've missed it.  Qt's still new to me, so forgive me if I missed something obvious...  Could you point me in the right direction?

So far as "this->" goes, I admit, it's an old crutch - I usually used it for Intellisense's sake...  I'll certainly avoid it in the future.

**Comment by zinnschlag** [comment]
> opencs icon - is that plugin.png? That's the only image file in the source that looks like it might be meant for the editor...

Not in the repository yet. There is a thread in the editor development forum, where we discussed icons. I think it is called "Icons" or something.

> Regarding the startup dialog code - I'm afraid I've missed it. Qt's still new to me, so forgive me if I missed something obvious... Could you point me in the right direction?

apps/opencs/view/doc/startup

**Comment by joelgraff** [comment]
With regards to the opencs icon - if it's not in the repo yet, may we leave the openmw icon in it's place as a placeholder with a note to swap it out once it makes it in?  Or just wait?

As for the startup dialog, I now see the problem - when I cloned the openmw repo, I cloned master.  After poking around I see, of course, "startup" is in next.  At this point, I see myself deleting my local copy and cloning "next" instead.

Being entirely new to git, before I go and do that, if you have any thoughts or comments, I'd appreciate them....

**Comment by zinnschlag** [comment]
> With regards to the opencs icon - if it's not in the repo yet, may we leave the openmw icon in it's place as a placeholder with a note to swap it out once it makes it in? Or just wait?

Just use the icon from the thread? Assuming the resolution is acceptable. If not, ask the guy who made it to provide a suitable resolution.

> As for the startup dialog, I now see the problem - when I cloned the openmw repo, I cloned master. After poking around I see, of course, "startup" is in next. At this point, I see myself deleting my local copy and cloning "next" instead.
> 
> Being entirely new to git, before I go and do that, if you have any thoughts or comments, I'd appreciate them....

You do not clone branches. You clone repositories. No need to delete anything. Just fetch from upstream and then checkout a new branch based on my next branch.

**Comment by joelgraff** [comment]
Ok, closed this req. since it wasn't going anywhere.  Having trouble getting my local repo to reflect changes in master and next (merge issues), but for the time, I think I'm ok.

Looking at start, it appears that you want to have the the class signals tied to slots in editor?

The end result, as I see it, is a floating dialog that may be used to create new / open existing views at any time (spawning entirely new windows).  Right?

As for adding recent files, as I've researched, I see it's not much more than saving previously opened paths to QSettings, then recalling them.  My plan was to simply add those to a listview in the start dialog...

Also, opening new files - what are the valid extensions for the open dialog filter? .esm/.esx?  Could stub in that code easily enough, I suspect.

**Pull request closed without merging**
