### PR TITLE
No more "using namespace" in MWGui!

### PR DESCRIPTION
**Pull request by thespacepanda**
MWGui Cleanup is done, as long as you approve of everything

### CODE REVIEW

**Comment by ghost** [comment]
This will not merge cleanly. I suggest you merge master and redo the race.cpp/.hpp part.

**Comment by thespacepanda** [comment]
Forgive me, I'm still new to github. Is this directed to me or to Zini?

**Comment by ghost** [comment]
It's directed to you :)

**Comment by thespacepanda** [comment]
How exactly do I merge with master and what is wrong with the race.cpp file? I just did git push origin master.

**Comment by ghost** [comment]
There have been changes to the race.cpp and race.hpp files and your changes are conflicting with them. You need to merge your changes with the latest master branch from Zini and resolve the conflicts.

See the github help: https://help.github.com/articles/fork-a-repo

**Comment by thespacepanda** [comment]
Oh okay, thank you so much scrawl. I apologize for always asking newbie questions haha

**Comment by thespacepanda** [comment]
I believe that fixed it. I did fetch from upstream earlier but I didn't merge it.

**Pull request merged**
