### PR TITLE
Bufix #778: The journal can be opened at the start of a new game

### PR DESCRIPTION
**Pull request by Glorf**

### CODE REVIEW

**Comment by zinnschlag** [comment]
Doesn't merge cleanly. I guess scrawl's new game changes got in the way.

**Comment by Glorf** [comment]
Yeah, you're right. But what to do with that? I'll try to revert commit, merge changes, and replace it with another commit (all in this branch). It'll work?

**Comment by ghost** [comment]
Looks too complicated also.
Why don't you just check mAllowed & GW_Magic in getJournalAllowed? That way the extra member variable and separate OpEnableMagicMenu instruction aren't needed.

>  But what to do with that? I'll try to revert commit, merge changes, and replace it with another commit (all in this branch)

Using git rebase is better.

**Comment by Glorf** [comment]
I just haven't thought about that.

**Comment by Glorf** [comment]
Done

**Pull request merged**
