### PR TITLE
Bsatool

### PR DESCRIPTION
**Pull request by PotatoesMaster**
This move bsatool from components/bsa/tests to apps directory.
It now uses boost command line options parser.

Building this tool is disabled by default in CMakeLists.txt, to not bother people compiling it when they do not need it.

### CODE REVIEW

**Comment by zinnschlag** [comment]
What do we need this tool for? There are fully functional tools for extracting bsas out there and we don't need to that anyway.

**Comment by ghost** [comment]
I haven't tried this yet but if it works then it would be very useful.

> There are fully functional tools for extracting bsas out there

Any linux native programs? Haven't found any. And a simple command line program is (to me) much more useful than a WINE-wrapped, may-work-or-may-just-fail version of a program.

> and we don't need to that anyway.

I have needed it many times for inspecting textures or NIFs inside the BSA files.

**Comment by zinnschlag** [comment]
> I have needed it many times for inspecting textures or NIFs inside the BSA files

Doesn't MW come with all these in extracted form anyway? At least my copy did.

**Comment by ghost** [comment]
I'm using the CD version installed via WINE. It has a textures and meshes folder which contain almost nothing.

**Comment by kcat** [comment]
There's also the issue of BSAs provided by mods. There's a few times I wished to have something to extract, repack, and inspect a BSA's contents, but all I have is a Windows program I need to run in Wine (which itself was difficult to track down; most BSA tools I found wouldn't work in Wine because of .NET issues).

Going forward, I think we should be encouraging the use of BSAs (if not 7z or zip) to cut down on loose files, and for that we'll need a tool to make them. Maybe also a companion GUI tool, or integration into OpenCS.

**Comment by zinnschlag** [comment]
> Going forward, I think we should be encouraging the use of BSAs (if not 7z or zip) to cut down on loose files, and for that we'll need a tool to make them. Maybe also a companion GUI tool, or integration into OpenCS.

There is no "maybe" about that. If we want to get a handle on the resources managing we need to put them into some kind of archives. Having this handled in OpenCS is a must, which makes additional tools redundant; both GUI and command line. I am not sure if you are aware of that, but I am designing the OpenCS in a way, that it will eventually also be usable without the GUI, via the command line and from scripts (for batch processing and other kinds of automated changes). Once this works (another post 1.0 feature) we should be able to retire all other command line tools.

However we are not there yet and so it seems having a bsa tool for now is reasonable. Merge incoming ...

**Pull request merged**
