### PR TITLE
added script command to show arbitrary book

### PR DESCRIPTION
**Pull request by blunted2night**

### CODE REVIEW

**Comment by zinnschlag** [comment]
There is no such script instruction in MW and we can not add new ones at this time.

**Comment by blunted2night** [comment]
I added to support debugging, is there a better way to approach this?

**Comment by zinnschlag** [comment]
Just add the book to your inventory with AddItem and then open it manually. Or, if you want to test the same books repeatedly you can use AddItem in the startup script (see ./openmw --help and then --script-run).

**Comment by blunted2night** [comment]
sounds good, thanks

**Pull request closed without merging**
