### PR TITLE
Build fixes

### PR DESCRIPTION
**Pull request by AMDmi3**

### CODE REVIEW

**Comment by zinnschlag** [comment]
Sorry, rejected. The new OGRE version is mandatory. The whole 1.7. line contained a critical bug, that stopped certain parts of OpenMW from working properly.

**Comment by AMDmi3** [comment]
Ok. But 3aa923b is still useful.

**Comment by zinnschlag** [comment]
Merging via cherry-pick ...

**Comment by AMDmi3** [comment]
Thx!

**Pull request closed without merging**
