### PR TITLE
Physicsaedra3

### PR DESCRIPTION
**Pull request by jhooks1**
Finished, needs testing/review.

### CODE REVIEW

**Comment by ghost** [comment]
- I got stuck sometimes on almost flat terrain. I could get out by going a step backwards and then it was fine. 
- In beshara, in the third person view, the screen flickers every second. Only happens if the camera distance has been adjusted due to an obstacle in the view. So it must be a failure of the raycast used for that, but only every second?.

**Comment by zinnschlag** [comment]
btw. this has already been merged into next. I am leaving the pull request open to allow the discussion to continue, but won't merge.

**Comment by jhooks1** [comment]
I posted a slight change (back to the way things were before), I hope that will fix the first issue.

As far as the second issue goes, I can't replicate the issue.  Seems to behave the same way as .17 in third person.  The player now has its own rigid body that gets added into the dynamics world, maybe that could be affecting something.  

EDIT:  Does the screen flicker only when collision is on?  Also only happens in third person right?

**Comment by ghost** [comment]
I can still reproduce the flickering. Happens regardless of collision on or off. Yes only third person.

**Comment by ghost** [comment]
Can record a video if that helps.

**Comment by ghost** [comment]
I caught it on screenshot:

http://scrawl.bplaced.net/temp/g/1.png
http://scrawl.bplaced.net/temp/g/2.png
http://scrawl.bplaced.net/temp/g/3.png

I did not change the camera angle between these 3 frames.

**Comment by jhooks1** [comment]
A video would help.  Are you running the physicsaedra3 branch, or the next branch?  I haven't even tried next.

**Comment by ghost** [comment]
next branch. I couldn't capture it on video, apparently not all frames were captured.

**Comment by jhooks1** [comment]
Also the third person camera does seem to act strange when moving forward, but the exact same thing is happening to me in .17.  I can't see a difference between third person in my physicsaedra3 branch and .17.  A video would really help me see how to bring the error to the surface.

**Comment by ghost** [comment]
Video: http://scrawl.bplaced.net/temp/test.ogg

**Comment by ghost** [comment]
Also, this seems to affect all raycasts. The item tooltips are flickering as well now (and they use a raycast)

**Comment by jhooks1** [comment]
Watched the video, this does not happen to me at all in physicsaedra3.  Are you sure that it is the code from the physicsaedra3 branch that is causing this?  Has anything changed lately with the third person code that would cause this?  My physicsaedra3 branch had master merged into it 2 weeks or so ago, and I never saw this problem.

**Comment by ghost** [comment]
physicsaedra3 has this bug, master has not.

**Comment by ghost** [comment]
I will do a bisect to check which commit introduced it.

**Comment by ghost** [comment]
23777033fdcf94fc83479af7fdc71c1e0718a8dd is the first bad commit
commit 23777033fdcf94fc83479af7fdc71c1e0718a8dd
Author: Jason Hooks jhooks1@mix.wvu.edu
Date:   Wed Sep 5 17:44:11 2012 -0400

```
Starting to implement new PhysicActor
```

**Comment by ghost** [comment]
Commenting out these 2 lines fixes it:

```
    mEngine->addRigidBody(mBody, false);  //Add rigid body to dynamics world, but do not add to object map
        mEngine->dynamicsWorld->removeRigidBody(mBody);
```

So it looks like the player's collision shape interferes with the raycasts.

**Comment by jhooks1** [comment]
Not surprising, I figured that could be the problem.  What I don't understand is why I still have not seen this problem myself.  Maybe disabling the player collision shape from being involved in raycasts could be a possible fix.

**Pull request merged**
