### PR TITLE
Do not allow magic/combat stance unless magic/inventory window are accessible

### PR DESCRIPTION
**Pull request by PotatoesMaster**
https://bugs.openmw.org/issues/839

### CODE REVIEW

**Comment by kcat** [comment]
This may not be correct. When you're in werewolf form, you don't have either the magic or inventory windows available (only stats and map), but you can still do hand-to-hand combat.

Perhaps combat stance could be tied to having the inventory menu itself, rather than just the inventory window? The magic stance should be fine with being tied to having the magic window accessible, but we'll still need to allow combat with no inventory window.

Or perhaps start with mControlSwitch["playerfighting"] and mControlSwitch["playermagic"] to false in a new game, and toggle them on with the inventory/magic windows (and leaving them on even if the windows get disabled again).

**Comment by PotatoesMaster** [comment]
Another solution: operate on `WindowManager::mShown` to force hiding magic and inventory windows in werewolf form. This way `WindowManager::mAllowed` is left untouched and does not prevent fighting.
This could be made by editing `WindowManager::toggleVisible()` and adding a new method (`WindowManager::toggleWereWolf()`?).

P.S.: in vanilla, weapon and magic boxes are displayed on HUD for werewolf (the weapon box shows a claw icon and the magic one is empty). These icons are displayed if the inventory and magic windows are available (information stored in `mAllowed`).

**Comment by kcat** [comment]
I don't really understand the GUI code, but what you say makes sense. I don't think you need a `WindowManager::toggleWerewolf()` method, though, just check if the player is a werewolf before allowing them to be toggled visible.

**Comment by PotatoesMaster** [comment]
We could do that, but all references to the outside world from WindowManager code come from arguments passed to its methods (values for the health/fatigue/magicka bars, player position for the map).
Is it okay to introduce a call like `MWWorld::get():getPlayer()` here? Zini?
There is some other actions to do when transforming into werewolf (changing FOV, set the weapon icon). Maybe `toggleWereWolf()` belongs to an other place in code (as `MWWorld::Player`), and could call some new methods in `WindowManager`, namely `toggleForceHidden(GuiWindow)` and `setClawsIcon(boolean)` ?

**Comment by zinnschlag** [comment]
> We could do that, but all references to the outside world from WindowManager code come from arguments passed to its methods (values for the health/fatigue/magicka bars, player position for the map).

That is a relict from an older design; mostly.

> Is it okay to introduce a call like MWWorld::get():getPlayer() here?

Sure.

**Comment by kcat** [comment]
> Maybe toggleWereWolf() belongs to an other place in code (as MWWorld::Player)

We should probably add a method like that in MWWorld or MWWorld::Class, since any NPC can be turned into a werewolf. It can easily check if the actor being turned is the player and alert the WM appropriately.

Also, for consistency I'd recommend using "Werewolf" instead of "WereWolf" if any new functions need to be made.

**Comment by zinnschlag** [comment]
That is also a good idea and yes, it should be Werewolf.

**Comment by PotatoesMaster** [comment]
Thanks for the clarification, I was scratching my head wondering where to put that. :)

I've made a new branch for werewolf stuff ([there](https://github.com/PotatoesMaster/openmw/tree/werewolf)). It's not ready yet: the werewolf state is sticky for the player. I have to investigate.

**Comment by zinnschlag** [comment]
Alight. What about this pull request? Seems like it can be merged for now?

**Comment by PotatoesMaster** [comment]
Yep.

**Pull request merged**
