### PR TITLE
Bugfix #691: Auto equipping ignores equipment conditions

### PR DESCRIPTION
**Pull request by Glorf**
1) Bugfix 691
2) Small azura's star fix

### CODE REVIEW

**Comment by zinnschlag** [comment]
That doesn't look like the way to go. Maybe we could use a function to determine if an item can be equipped by a character regarding to race, but since you are checking the item the argument order should be switched (if you are passing in a NPC Ptr at all and not just a race) and the name of such a function would be canBeEquipped (since we are operating on the item and not on the actor).
Also, unequipping an item as a side effect of a function named canEquip is highly undesirable. I think two-handed weapons need to be handled separately.
And finally, what is the loop at the beginning of the canEquip function for? I don't see where you would need the container iterator.

**Comment by Glorf** [comment]
Yes, it will fit much more to the mwclass as canBeEquipped.

Two-handed weapons are unequiped where it shouldn't, but I've found that it's the best way, even if a bit hacky. Maybe use of enumerated variable {canEquip,cannotEquip,isTwoHanded}, or int (0,1,2) as return, and unequip after that is a good idea? I just want to keep all item-recognition inside canBeEquipped.

That loop is just part of code that I forgot to cut-off, sorry.

**Comment by Glorf** [comment]
what I mean:
virtual int canBeEquipped(const MWWorld::Ptr &npc, const MWWorld::Ptr &item) const;
///< Return 0 if player cannot equip item. 1 if can equip. 2 if it's twohanded weapon. 3 if twohanded weapon conflicts with that.

**Comment by Glorf** [comment]
Done, I think it is clear enough now.

**Comment by Glorf** [comment]
There are some new problems. I'll fix it and re-pull

**Pull request closed without merging**
