### PR TITLE
SDL input

### PR DESCRIPTION
**Pull request by ghost**
Tested on all platforms with SDL2 rc snapshot ( http://www.libsdl.org/tmp/download-2.0.php )
New features:
Hardware mouse cursors - http://bugs.openmw.org/issues/263
Allow mouse outside of window while paused - http://bugs.openmw.org/issues/449
openmw.png used as window icon
Fixed alt-tab, multimedia keys etc on linux

### CODE REVIEW

**Comment by zinnschlag** [comment]
I would rather not work with a RC snapshot. Can we wait until there is actually a release?

**Comment by ghost** [comment]
For what reason? Until this is in package repositories (which could take a long time), users will have to manually download and compile it anyway.
Regarding stability, I've been testing this the whole week and it's pretty solid.
Also keep in mind the longer we wait, the more merge conflicts we'll have again. It took me a while to update the 2 months old branch to master.

**Comment by zinnschlag** [comment]
I'll have another look at it tomorrow.

**Comment by ghost** [comment]
I also want to add that Valve is using SDL2 for their games. Also several
ports from flibitijibibo and Edward Rudd use the SDL2 library. There is no
reason to decline this pull request for stability reasons imho.

**Comment by nikolaykasyanov** [comment]
Also SDL2 would finally allow me to ship 64-bit build for OS X, because Ogre cannot into proper using of Cocoa framework and Cocoa is a "must" for 64-bit GUI apps on OS X. And SDL2 does it right.

**Comment by zinnschlag** [comment]
So far no luck with getting OpenMW build with SDL. The download page specifies the SDL version as 2.0.0 (stable). Is that different from what you compiled with and might that causing problems? Or do I have to continue looking on my side?

**Comment by ghost** [comment]
This is the exact file I downloaded: http://www.libsdl.org/tmp/release/SDL2-2.0.0.tar.gz
I then used cmake . && make && make install.
What error are you getting?

**Comment by nikolaykasyanov** [comment]
@scrawl don't forget to merge my last commit into this branch please

**Comment by zinnschlag** [comment]
/home/marc/OpenMW/openmw/extern/oics/ICSPrerequisites.h:42:28: fatal error: SDL2/SDL_input.h: No such file or directory

**Comment by ghost** [comment]
Pull again, that one I fixed a while ago.

**Comment by ghost** [comment]
Actually it was fixed before I made this pull request, so you may have the wrong branch. The correct one is sdl_input2. I've deleted the old branch now.

**Comment by zinnschlag** [comment]
I believe that was that branch I had from the beginning. But pulling again got me past that error. Still building. Have only one core available for OpenMW (running some heavy calculations in the background for something entirely different), so that might take a bit longer.

**Comment by zinnschlag** [comment]
Okay. Builds. And runs. But now I am getting spammed with:

Unhandled SDL event of type 771

in the console.

**Comment by zinnschlag** [comment]
That would be SDL_TEXTINPUT, I believe, if my dec to hex converting skills don't fail me (took me a bloody eternity to find the event list in the SDL source).

**Comment by ghost** [comment]
Yeah, those aren't properly handled yet. Text input also needs to be enabled/disabled depending on whether a text input widget currently has focus. I'll do this soon.

**Comment by zinnschlag** [comment]
All right. Merging. btw. I noticed another problem. When you start OpenMW in windowed mode and the mouse pointer is not over the window, OpenMW does not automatically acquire the mouse. At least this is unexpected behaviour, even if it is not necessarily wrong.

**Comment by ghost** [comment]
This is now fixed in the latest pull request.

**Pull request merged**
