### PR TITLE
NPC/creature persistence flag

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by zinnschlag** [comment]
Can we do that without adding a mostly useless flag parameter to every single load function? Maybe store the current flags in the ESMReader and get it from there? Also, I think you forgot to initialise the persistence flag in the creature record.

**Comment by ghost** [comment]
Good idea. Updated.

**Comment by zinnschlag** [comment]
It seems we are missing the matching save code. Not sure how easy that would be.

**Comment by ghost** [comment]
The record header is explicitely set in ESMWriter::startRecord. That's how ESMTool does it (nothing else does saving yet)

**Comment by zinnschlag** [comment]
This will basically end up in the same mess we had with loading. But I don't see a way around it either.

**Pull request merged**
