### PR TITLE
Dialogue escape sequences

### PR DESCRIPTION
**Pull request by wheybags**
Currently only works for %PCName and %Name, I have yet to find a comprehensive list of escape sequences.
To test, talk to Laire in Beshara.

### CODE REVIEW

**Comment by zinnschlag** [comment]
Escape sequence handling is supposed to be implemented as a unified feature, probably integrating both dialogue escape sequences and message box escape sequences. Also, the syntax is a lot more complex (we really need a full analysis of it, before the implementation can start) and placing the code in the dialogue GUI class won't cut it. Sorry, rejected.

**Comment by wheybags** [comment]
I could try and do that?

**Comment by zinnschlag** [comment]
If you want. There is various documentation available about these escape sequences. I think even Morowind Scripting for Dummies has something on it. The UESP wiki is also a resource that might be worth looking into. Make sure that you fully understand the syntax of these escape sequences before you start implementing them.

**Comment by wheybags** [comment]
Ok, I'll have a look into it.

**Comment by wheybags** [comment]
Hey, I had a look into escape sequences, and put all I found on http://www.uesp.net/wiki/Morrowind:Text_Defines.
I don't think I missed anything.
Some people on irc told me to ask you about it before I started implementing it, because supposedly dialogue is fiddly because of the journal?

**Comment by zinnschlag** [comment]
Nice work.

The journal GUI is broken, it seems. Haven't found the time to investigate it yet (and probably won't get to it before Christmas, since I will be away for a couple of days from Saturday on). That doesn't matter though. The code should be written independently from the journal GUI anyway, since it will also be used by the message box. Probably best done as a single free function in a new translation unit. You should be able to test almost anything from the message box.

I think you missed one case though.
^NPC.x
where NPC is the ID of an NPC and x is one of Name, Race, Class, Faction and Rank.

btw. can we have this list on the OpenMW wiki too? For now it doesn't matter, but once start to extend the escape sequences we will need a copy anyway.

**Comment by wheybags** [comment]
I'm probably being stupid here, but how can I actually use that NPC.x sequence?
The ids have spaces in them, and I walked around until i found an npc with no second name, but it still didn't seem to work?
EDIT: Added a picture to clarify:
skeetul

**Comment by zinnschlag** [comment]
Odd. Either the UESP wiki is mistaking or I am reading it wrong. See for yourself: http://www.uesp.net/wiki/Tes3Mod:MessageBox

**Comment by Thoronador** [comment]
I could not get any of those `^NPC.x` stuff to work after several tries either. What's more, I did not find any ^NPC.x stuff in Morrowind.esm, Tribunal.esm or Bloodmoon.esm, so I believe that this is indeed a mistake on UESP wiki's side and this particular type of special strings might not exist at all.

**Comment by zinnschlag** [comment]
Okay then. I guess you can start with the implementation, if you want. If there are any more questions, you should get them to me within the next few hours, because after that I will be offline for a couple of days.

**Pull request closed without merging**
