### PR TITLE
Fixed Boost errors for version 1.46

### PR DESCRIPTION
**Pull request by pvdk**
Hey Zini. 

I made a quick fix for the build errors with Boost 1.46. Boost uses filesystem::path as a return type for extension() and filename() instead of string_type in the new filesystem v3.
Bug reported here: http://openmw.com/forum/viewtopic.php?f=14&t=457&p=4302

You might want to do it differently, I don't know what version of Boost we want to support or if this builds with Boost < 1.46.

Regards,
Pieter.

### CODE REVIEW

**Comment by ghost** [comment]
Hi,

You might have sent this email to the wrong person.

I'm not Zini, I'm chewit.

On 8 May 2011 20:29, pvdk <
reply@reply.github.com>wrote:

> Hey Zini.
> 
> I made a quick fix for the build errors with Boost 1.46. Boost uses
> filesystem::path as a return type for extension() and filename() instead of
> string_type in the new filesystem v3.
> Bug reported here: http://openmw.com/forum/viewtopic.php?f=14&t=457&p=4302
> 
> You might want to do it differently, I don't know what version of Boost we
> want to support or if this builds with Boost < 1.46.
> 
> Regards,
> Pieter.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/zinnschlag/openmw/pull/20

## 

Blog: www.edhewitt.co.uk
Follow Me: @edhewitt http://www.twitter.com/edhewitt

**Comment by pvdk** [comment]
Haha not my fault, git automagically reports pull requests to you too.
Don't know why, maybe because you did some pull requests too in the past?

**Comment by zinnschlag** [comment]
Doesn't work with boost 1.40 (the version with the last Ubuntu LTS version). No string function.

**Comment by pvdk** [comment]
Hmm I was afraid it wouldn't. What to do? Arch also uses 1.46.

**Comment by pvdk** [comment]
Ok while Chris over at the forum proposed to add our own string function, I decided to do it differently. It's a bit ugly but I believe it works. I tried to #define BOOST_FILESYSTEM_VERSION to 2 but that doesn't work.
So the code checks for v2 being used or BOOST_FILESYSTEM_VERSION not being defined (means < 1.46).

**Pull request closed without merging**
