### PR TITLE
Feature #535: Console object selection improvements

### PR DESCRIPTION
**Pull request by Glorf**
console max distance is object distance *50, it's just random value that I've added to ensure that we can select objects that are far away.

### CODE REVIEW

**Comment by zinnschlag** [comment]
There is quite a bit of code repetition in there. Maybe it would be a good idea to generalise and factor out the bodies of both if clauses in ToolTips::onFrame into a new private helper function?

**Comment by Glorf** [comment]
Of course, I've cleaned my code.
New function is not neccesary here at all.

**Comment by Glorf** [comment]
Also, about next tasks. Is it good moment to implement athletics and acrobatics skills? I could try it.

EDIT: ok, i see that we're stuck there.

**Comment by zinnschlag** [comment]
I am getting error messages when mousing over static objects after selecting static objects in the console:

> Error in framelistener: unknown class key:

**Comment by Glorf** [comment]
Ok, one moment, I'll check it.
What object are you selecting? In Beshara everything was working...

EDIT: Ok, got it, fix soon...

**Comment by Glorf** [comment]
Done

**Pull request merged**
