### PR TITLE
Store player data in ESMStore

### PR DESCRIPTION
**Pull request by greye**
For review mostly.

### CODE REVIEW

**Comment by zinnschlag** [comment]
Seem this pull request contains the commit from 431, so I will comment on both in this one:
1. We are not changing existing ESM records. Every. No matter if dynamic or static. Again, this will help us greatly with multithreading implementations, but there are also other matters to consider. By making records unchangeable we allow other parts of OpenMW to temporarily cache data from records without having to worry about changes.
   Since changing the records is an operation we explicitly want to forbid, the interface of the ESM store should not allow them.
   Then there is the situation with the player record. A simply way to address this problem would be to silently allow overwriting of this particular record. Normally calling create for an existing record would be an error, calling it for the player would simply overwrite the old record (just assigning the new player to the old player struct should do the job). This is a bit hack-ish (you would also need to write special case code to keep the ID "player" instead of creating a new one), but we knew that it would come to that. The player record needs more special case treatment anyway.
2. You still have player NPC record related functions in the Player class. I suggest to just get rid of these. After all the purpose of the player class is only to provide those parts of the player that go beyond a normal NPC.
3. The functions for modifying the player are bloating the World interface unnecessarily. I suggest to remove them completely. Together with 1. you can easily make a local copy of the player record, make the desired changes and than "re-create" it.

**Comment by greye** [comment]
1. Then non-const non-inserters should go away, ok
2. What functions exactly? set/getName/Gener - yes, birthsign - no, I believe; class/race - maybe, but I think it is handy to fetch them this way instead of searching references.

**Comment by zinnschlag** [comment]
1. All of them, I would say. To keep the interface small and also for the sake of consistency We don't have them for the other NPCs and even for the player we mostly skip these functions anyway. AFAIK they are only used during character creation. Everything else goes directly via the records.

**Comment by greye** [comment]
Something like that, but I'm interested what to do with birthsign and stats window.

**Comment by zinnschlag** [comment]
Looks good (except for the broken second line in the create function's doxygen comments). Not sure what your problem with birthsigns and the stats window is. They are treated like everything else.

**Comment by greye** [comment]
Problem is that player birthsign id is stored nowhere, so I had to create local copy in MechanicsManager and now I'm in doubt how to better introduce it to StatsWindow (previously it fetched sign from Player, for now it is just disabled).

**Comment by zinnschlag** [comment]
I just noticed. The NPC record does not have a birthsign field. I wasn't aware of that. Thank you Bethesda for even more inconsistencies. :( Sorry, should have looked that up first. So birthsign goes back into Player then.

**Pull request merged**
