### PR TITLE
Enchanting with npc, and it's menu.

### PR DESCRIPTION
**Pull request by Glorf**
I've fixed my code from last pull.
Pricing is still not done, and we also don't have self-creation of enchanted items (only with npc help).
I'll work on it, but I want to pull this part as soon as possible, because it's big amount of code that will be hard to pull if not pulled soon.

I haven't added any experience gain, because player don't have any experience from items created with NPC's. I'll add it with self-creating and charging of items.

### CODE REVIEW

**Comment by Glorf** [comment]
I forgot, items stacks are working good. I was unable to test gems stacks, but they also should work good.

**Comment by Glorf** [comment]
Arrr, we also don't have the value of enchanted item... one more morrowind formula to discover...

**Comment by zinnschlag** [comment]
Your ApplyEnchantment functions are broken. You are creating a ManualRef locally and then return a Ptr to it. That's undefined behaviour. Either you need to insert the created object into the container within the ApplyEnchantment function or you could make the function return just return the ID of the enchanted item record.

**Comment by Glorf** [comment]
Fixed

**Comment by Glorf** [comment]
After the fix item stacks don't work properly again. I'll fix it later, but not in this pull.

**Pull request merged**
