### PR TITLE
Modified the cache path to work on windows

### PR DESCRIPTION
**Pull request by ananace**

### CODE REVIEW

**Comment by zinnschlag** [comment]
Having the application name hardcoded in the platform specific path code defeats the purpose of passing it in to FixedPath. And the new Linux path makes no sense (the original was correct).

**Comment by zinnschlag** [comment]
Actually, not sure about the original Linux path. We want the .cache directory in OpenMW's user directory.

**Comment by zinnschlag** [comment]
And correcting myself again :( The original path was correct. It's apparently common to have cache files in ~/.cache/appname on Linux. Didn't know that.

**Comment by ananace** [comment]
Would this be more suitable then?

**Comment by zinnschlag** [comment]
No. Now we have platform specific code in fixedpath.hpp. I think the fixed path handling needs a partial rewrite. The problems seems to be that the application name is added in fixedpath.hpp instead of the platform specific files. Maybe add an application name parameter to the get*Path functions of the platform specific files and create the full path there?

**Comment by ananace** [comment]
How about this then?

**Pull request merged**
