### PR TITLE
fix for https://bugs.openmw.org/issues/573

### PR DESCRIPTION
**Pull request by lazydev2**

### CODE REVIEW

**Comment by zinnschlag** [comment]
Mostly okay, but please do not change the record structs from to classes. Also, why is esmcommon.hpp included in loadapp.hpp? And finally, if you add a const to the save function of a record struct, then please add a const to the save function of all record structs.

**Comment by lazydev2** [comment]
0) Is there any way to quote a message?

1) Why struct is better? Structs with methods looks at least strange...
2) loadapp.hpp - just forgot to remove it. I will do it today
3) How can I found all the record structs? Looks like they are in different files and all have different names

**Comment by zinnschlag** [comment]
> Is there any way to quote a message?

Copy and paste and then prefix it with >

> 1) Why struct is better? Structs with methods looks at least strange...

There is nothing strange about structs with methods. We use structs here, because the record structs are plain, un-encapsulated collections of values (with some helper functions attached to them).

> 3) How can I found all the record structs? Looks like they are in different files and all have different names

components/esm/load*.hpp

**Comment by lazydev2** [comment]
done

**Pull request merged**
