### PR TITLE
more aicombat pathfinding fixes

### PR DESCRIPTION
**Pull request by cc9cii**
Zini, would you mind cherry picking a6f201c and 1105f6e please.

These are optional, required for MSVC 64bit only: 8b492a3, beac817 and 97ebb7f

### CODE REVIEW

**Comment by zinnschlag** [comment]
That does not merge cleanly. Sorry, but we are at the limit what cherry picking can do. This feature is meant for exceptional situations, not as a regular way of dealing with merges.

**Comment by cc9cii** [comment]
Yes, sorry, my inexperience with git is showing.  What would you suggest, should I back out certain things so that the changes can be merged cleanly?  By the way, taking all of my changes might be ok?  I don't think they do any harm (other than perhaps that last change with /bigobj which I need to fix lest ACE gets affected by that change)

**Comment by zinnschlag** [comment]
I suggest to addd that /bigobj fix and then merge in master (resolve any resulting conflicts). And in the future, work with separate branches, when you are targeting separate branches.

**Comment by cc9cii** [comment]
Ok, will do.  But first I'll fix the screenshot crash.

**Pull request closed without merging**
