### PR TITLE
NIF file cache

### PR DESCRIPTION
**Pull request by blunted2night**
This patch adds a cache for loaded and parsed NIF files so that repeated requests for the same NIF file during loading sequences (currently engine startup, and cellChange) don't perform excessive work.

### CODE REVIEW

**Comment by zinnschlag** [comment]
Not overly keen on the non-multithreading part. It is very likely that loading will become multithreaded in OpenMW and it definitely will in the editor (not entirely sure about loading of OGRE resources though). If that turns into something that will be addressed later, we should at least make it more clear, that we have a problem now by writing the non-multithreaded comment as a doxygen comment (e.g. with an \attention tag).

But the real problem here is this code:

>  Nif::NIFFile::lock_cache (); // lock NIFFile cache for initializiation...
> 
> ... some stuff
> 
> Nif::NIFFile::unlock_cache (); // let go now that we are good 2 go...

This lock/unlock pattern is pretty much a no-go in C++. Consider what happens when some stuff throws an exception.

As a workaround you can either (quick and dirty) add a try catch clause or (properly) add something like boost::thread::lock_guard.

btw. there have been some changes to the files you are touching here. You probably should merge in master again after you are finished with fixing this branch.

**Comment by blunted2night** [comment]
My comment about multi-threading being tricky was incorrect. After writing
it, I spent some time making sure that the code would be safe if a lock was
held in the indicated spots. I left out multi-threading for now because I
didn't know what library was being used, and it wasn't important right now.
If the library is boost::threads though, I will go ahead and add the bits
to make it thread safe.

**Comment by blunted2night** [comment]
I screwed up tabs/spaces. I am going to recreate the patch set and post later...

**Comment by zinnschlag** [comment]
> About your comment to use a lock_guard, I generally agree with that approach and regularly use it, but I have to
> ask myself, could the system continue to operate if one of these section exited via exception.

There is no continuing after an exception during startup. That doesn't excuse us from cleaning up properly though.

For the cell change, exceptions happen and OpenMW does continue after them. Currently these exceptions are caught lower down the execution path, so they wouldn't reach the part of the code you are changed. The emphasis is on "currently" here.

> Would you prefer fixes to patches to be made as separate commits, or to have the history reworked to put the fix into the commit that introduced it?

Honestly, I don't care. Do what you are most comfortable with.

> If a reworked patch is desired, and there is an existing pull request, should I close the existing pull request and create a new one, or just reference the new version of the history from the existing pull request?

Make a new one please.

**Comment by blunted2night** [comment]
> There is no continuing after an exception during startup. That doesn't excuse us from cleaning up properly though.

It doesn't prevent things from getting cleaned up, just affects when they get cleaned up. "Unlocking" the cache will free any NIF files that have no other references immediately. No matter what the cache lock depth is, when globals get their destructors called, the memory is going to be released.

**Pull request closed without merging**
