### PR TITLE
Rotate, RotateWorld script instructions, and local rotations layer.

### PR DESCRIPTION
**Pull request by Glorf**
Finished, working exactly the same as in morrowind.
Had to add local rotations layer, but it's the most clean way to get it working.

### CODE REVIEW

**Comment by zinnschlag** [comment]
That is exactly the solution we tried to avoid. I can not claim to understand the situation fully, because I have only a vague understand on how MW handles rotation (always avoided the Rotate instructions and rotations around more than one axis per object, because the whole system looked flaky to me), but didn't we come to the conclusion that this is not necessary?

**Comment by Glorf** [comment]
Yes, but without that:
1) We will get competely another getangle value than in morrowind.
2) I'm not sure if it is possible when using euler angles at all (we would have to translate it some way), and we cannot use quaternions.

I've done a lot of tests on morrowind, and, unfortunately, it seems to handle localrotations exactly this way.
I've tested lots of solutions, and this seems to be the best one. Unfortunately.

**Comment by Glorf** [comment]
I also don't understand the situation fully, it's a week ago when I've seen rotation system the first time :smile:

**Comment by zinnschlag** [comment]
Then let's no do anything rash until we know for sure. This isn't exactly a feature that we need very urgently and adding local rotation axis blows up the size of the reference data structures considerably (note that we potentially have a very large number of them). I would rather see a proper solution than a quick one.

**Comment by Glorf** [comment]
As I said, morrowind seems to use this solution. There is one point that really need it: getangle script function. It adds local rotation to the world rotation the simplest way: it adds local X to world X, and so on. The question is if we could change this function's behaviour, or it has to return exactly the same values as in morrowind? If it has to, I don't see any other way. Otherwise, it could be probably possible.

**Comment by Glorf** [comment]
anyway, I have an idea... Would probably work. Closing

**Comment by zinnschlag** [comment]
Okay. I suggest to keep this branch around, in case the alternative solution does not work out.

**Comment by Glorf** [comment]
Sure.

**Pull request closed without merging**
