### PR TITLE
Record status delegate

### PR DESCRIPTION
**Pull request by joelgraff**

### CODE REVIEW

**Comment by zinnschlag** [comment]
Needs a bit more work:
- The table for referencable records still shows numbers
- I think the status text should start with an uppercase letter.
- The large amount of space between the icon and the left cell border looks odd.
- I don't see the actual user setting to make use of this new feature.

I also think that the icons don't work out well. But that is a topic for the icon thread.

**Comment by joelgraff** [comment]
I'll take a look at the unfinished items...  

I think I may have a solution for your icon problem, but I want to make sure I understand the meaning of the record status values.

If I read it correctly, an object which is "base" is a default asset from the original game / expansion pack (or perhaps even a plugin that is being modded?).  An object which is "modified" is a base object that has been changed in some form or another.  Finally an "added" object is an entirely new creation - not built upon any existing object in the database...

**Comment by zinnschlag** [comment]
That is not correct. We have a sequence of content files. All but the last are folded into base. The last one is the file we are editing.

BaseOnly (no icon): The record exists somewhere in base, but has not been touched in any way by the edited file.
Modified (modified icon): The record exists somewhere in base and has been changed by the edited file.
ModifiedOnly (add icon): The record does not exist in base. It was added in the edited file.
Deleted (delete icon): The record exists somewhere in base, but has been deleted by the edited file.

**Comment by joelgraff** [comment]
Ok, that makes sense.  What I'm looking at, though is how the status
defines the record.  That is, if you had two identical records, but with
each with a unique status, are they then unique records?  Or is this a
trivial case?  I can't think of a good reason why you'd want duplicate
records with different status to persist in the model...

**Comment by zinnschlag** [comment]
I am not sure what you mean by duplicated records. Each record has a unique ID. Therefore there can't be duplicates.

**Comment by joelgraff** [comment]
Ok, here's what I'm thinking...  I've designed a fair number of databases,
and the record status column looks like visual clutter that I typically
handle in a variety of different ways.  IMO, it should be removed from the
table completely and represented some other way (esp. since it's
read-only).  I say this for several reasons:
1.  It would probably completely eliminate your icon issue.
2.  A column which repeats the same value over and over is a clue that it
   may not be appropriate for representation in the table. (Not always true,
   but usually worth looking into).
3.  The "record status" is really more of a categorical value than it is a
   data value.  That is, a record may represent a "base global" or a "modified
   game setting" or an "added weapon".  That's more meta-data than anything
   and doesn't quite belong in the table proper, IMO.
4.  The column sucks up lots of tabular real estate to display one of four
   fixed values.

Anyway, I've encountered this sort of situation before and almost every
time it's worked out better to not represent the data directly in a column
in the table.  Two approaches I've used that might work here include:
1.  Nest a subview within the table view.  That is, the table would
   initially provide only a list of the record status values - it would only
   have four records.  Click on a status value and the subview expands to
   display all records which have that value as their status.  Very similar to
   a tree view, except it's implemented as a nested table in the main table.
2.  Create checkable filters - one for each record status value.  This can
   be checkable menu items in the main View window's menu or perhaps
   checkboxes or radiobuttons at the right of the main view's menu bar.  Users
   may select one status (or more with check boxes) and the table would
   automatically filter all records that match that status.  It may be
   beneficial to have these filters hot-keyed.
3.  Leave the record status column in the table.  However, minimize the
   width, eliminate the option to display the status as text (or reduce the
   text to a representative letter - B, M, A, D) and rework the icons so they
   aren't so distracting.  I would recommend getting rid of the border and
   leaving them as simple dark shapes on a transparent background.

All of these options would require no modifications to the model, and #3
would require the least modification to the view.  Personally, I would
personally favor #2.  FWIW, I've implemented #1 and #2 in web db's and
Access db's and found the resulting layout to be preferable to leaving the
data directly in the table.

Just my two cents, anyway...

**Comment by zinnschlag** [comment]
I am sorry to shoot your suggestions down. But non of them make any sense from the perspective of a content developer. Have you actually used the CS? In the original the record column was missing (a star was displayed instead besides the name both for added, modified and modified only and I think we had the word "DELETED" after the name of deleted records). This has caused a huge amount of grief among content developers already.

The record status is vital and we need to make it visible as clearly as possible. This is not a theoretical problem. We had an issue with it in the Redemption project just last week. Brought the whole project to a halt for several days while the mess was sorted out, that resulted from the record state not being available in the CS.

We could have the status as icon only, but I prefer not to. This is a question of consistency. We will display icons in other columns too and we definitely need the text version there as an option. People who need more horizontal space can set it to icon only mode (which should result in a very narrow column) or (if they really do not need the record state) simply filter the column out (we will have both column and row filters eventually).

**Comment by joelgraff** [comment]
Whatever works for you.  Like I say, it was my database intuition kicking
in, there.  And no, I've never really used the CS.  The last time I did any
serious 3D engine modding was...  Doom. :)

Anyway, I would still recommend eliminating the icon borders and making the
shapes dark.  I still think they were just too much of a visual
distraction...  Maybe I'll post to the icon thread if I can get around to
reading it, first...

I'll try to get the other items taken care of soon.

**Comment by joelgraff** [comment]
Ok, looks like I've got it.  Still have some work on the user preferences
code (cleanup / organization).  Hopefully will have something to you during
/ after the weekend.  Fixed some big layout issues - was a good exercise.

**Comment by joelgraff** [comment]
Hmmm.. When I spoke with pvdk a couple weeks ago, he mentioned that the way
the settings are loaded right now is not correct - overlaying the
user-specific config files on the default config files...  That's what I do
with OpenCS - the default config file is loaded first, then the user file
on top of that - anything in the user file that isn't in the default is
appended to the map containing the settings, and any settings values that
are different at the user level will overwrite their defaults.

I designed the user preferences to have the default values hard-coded at
the page (stacked widget) level of the dialog so there was no dependency on
a default file, but the current loading scheme seems like a good idea to me
- why wouldn't you want to start with the defaults and then apply the
  user-level changes / addditions on top?  In terms of my work, it's just an
  extra level of security / flexibility...

In any case, do we want this behavior when loading settings?

**Comment by zinnschlag** [comment]
Having the default settings in a file instead of embed them in the code seems sensible.

**Comment by joelgraff** [comment]
Sorry to confuse the issue.  When I say "hardcode", it basically amounts to
specifying the default value for the widgets in the user preferences dialog
- which is just good GUI coding practice, IMO.  Any valid value loaded from
  file will always overwrite, so it's totally transparent to the current
  system.  It just makes for an added failsafe because if no valid value is
  loaded, the widget's hard-coded default will be used instead.

Pvdk suggested that loading the default config file and then applying
changes / additions in the user-level config file was not desirable
behavior (which is exactly how the system works right now).  I don't see
what's wrong with it - seems like a perfectly good idea to me.  I wanted to
check with you to make sure that was the desired behavior...

**Comment by zinnschlag** [comment]
I don't see what is wrong with it either. Makes sense to me.

**Comment by joelgraff** [comment]
This should be all of the needed changes.

**Comment by Glorf** [comment]
Thanks for improving my code!

**Comment by zinnschlag** [comment]
Does not build:

make[2]: **\* No rule to make target `/home/marc/OpenMW/openmw/files/opencs/base.png', needed by`apps/opencs/qrc_resources.cxx'. Stop.

Are we missing a file here?

**Comment by joelgraff** [comment]
Uh-oh.  Yeah, must have forgotten to add it.  Thought git would do that for
me.

**Comment by joelgraff** [comment]
Ok.  Have at it.

**Comment by zinnschlag** [comment]
And now we have:

/home/marc/OpenMW/openmw/apps/opencs/view/settings/usersettingsdialog.cpp:15:26: fatal error: samplepage.hpp: No such file or directory

Another missing file? Please remember to always do a git status before doing a commit.

**Comment by joelgraff** [comment]
Crap.

I deleted SamplePage as a last step and pushed the commit, but never
recompiled.  Forgot about an include.  It wasn't a problem with git on that
one...

**Comment by joelgraff** [comment]
Once more...  Sample page refs are gone, QDebug refs are gone, git status is clear, everything compiles on my end, and I caught another couple bugs in the window size pref code.

It will compile.  Dammit.

**Comment by zinnschlag** [comment]
Doesn't work. I get a message box with "Could not open file for reading". And then I get segfault: https://gist.github.com/zinnschlag/5836240

**Comment by joelgraff** [comment]
Well...  At least it compiled. :)

I slightly changed the file loading code and forgot to retest for a no-file condition.  Moved a bracket one line down and that fixed it.  I also tested for no files.  If none of the three files exists, it gives three message boxes, one for each file.  The app continues to run, and opening user prefs will cause those dialogs to pop up again.  However, once user prefs is closed, the .config/opencs.cfg file is saved, leaving only two that are missing.

How do you want to handle this condition?  The local level (/etc/openmw/opencs.cfg) requires root access, so I don't think I can write that if it's missing.  The global would be easy enough, I suppose.

**Comment by zinnschlag** [comment]
This is now my 3rd attempt at writing this comment. It seems the situation is a bit more problematic and a lot more confusing than I anticipated.

I do not see any global settings file in the pull request or in the existing code base. I assumed the intention was to have one copied to the local directory during the build process or to be installed to a global location during the installation process. If that is not the case, than we simply can not have a global settings file, because as you already mentioned, we can not write to these locations (that is true not only for global, but also local in certain configurations).

If the user file is missing, that is definitely not an error situation and should not show a message box.

If only one of the local and global files is missing, that is not an error situation and should not show a message box (you only need one of these and the local one must be preferred over the global one, if present).

If both the local and the global file are missing, this indicates a broken install or build. It is up to you how to handle it (show an error and abort, show an error and continue, show no error and continue silently). I do not see any of these approaches being clearly superior to the others.

btw. we have a file named files/opencs/raster/.directory and files/opencs/scalable/top-level/.directory in the pull request. What are these for?

btw (2). I am not entirely sure if we are clear on the terminology. You used it wrong at least once, but that may be just an oversight (happened to me all the time, but I am mostly catching it during proof-reading nowadays). But to be sure I am stating it again (with Linux as example):

user: ~/.config/openmw/
local: the location of the executable
global: something /etc/openmw/ or /usr/share/game/openmw/ -ish

**Comment by joelgraff** [comment]
Ok, I had global / local confused.  Something I'm not well familiar with
being new to linux...

I have absolutely no idea what the two directories are in the pull
request.  I didn't notice them when I did the commit.  I'm going to guess
they were a part of sirherrbatka's file structure when I merged his
icon-svg branch. Either that or I muddled something and had no idea I did
it.  I will delete them from my repo.  I can update the pull request with
them deleted, if you like.

So far as the settings files go...  I sort of feel like an error if both
global and local are missing with a  "don't remind me again" checkbox would
be appropriate.  Of course, that's another setting to store. :)

If it's worth doing damage control, we may not be able to replace a missing
global file, but we should be able to fix a local file, right?  That is, if
global's present, copy global to local.  If it's not, auto-generate a
default user file and copy it to local (don't copy the existing user file,
if it exists).

Personally, I don't see the need for three levels of settings.  I would
think a user / local arrangement would be sufficient.  But again, I'm new
to linux.  My view probably isn't worth the electronic medium it's printed
on... :)

Anyway, is there anything you want me to add to the pull request?  For the
time being, I can rewrite the UserSettings loader to error only if both
global and user files are missing - just to be on the safe side and provide
a hint to the user that there's possibility a corruption of the install has
occurred.

**Comment by zinnschlag** [comment]
> I have absolutely no idea what the two directories are in the pull request. I didn't notice them when I did the commit. I'm going to guess they were a part of sirherrbatka's file structure when I merged his icon-svg branch. Either that or I muddled something and had no idea I did it. I will delete them from my repo. I can update the pull request with them deleted, if you like.

Yes, please. Delete them. But no need for a new pull reuqest. We can do that here.

> If it's worth doing damage control, we may not be able to replace a missing global file, but we should be able to fix a local file, right?

No. To make that absolutely clear: We can not under any circumstances write to local, because the local location is not guaranteed to be writable.

> Personally, I don't see the need for three levels of settings. I would think a user / local arrangement would be sufficient.

That isn't possible, because when OpenMW is installed on Linux you can't have any other files in local. The binary will be in a directory that is for binaries only. Local is for running OpenMW uninstalled only.

> Anyway, is there anything you want me to add to the pull request?

I think everything I listed here needs to be taken into consideration, before we can merge.

**Comment by zinnschlag** [comment]
Oops. I think I explained that badly. Local is not actually the location of the binary, but the current work directory when running the binary. In practise that is sufficiently similar, that we don't have to worry about the difference. I just wanted to mention that for the sake of completeness and correctness.

**Comment by joelgraff** [comment]
K.  Local / User make a lot of sense - thanks for the explanation.  I will
rewrite the error condition for missing global and local (combined), but
otherwise, fail silently.  No other changes need be made to comply with the
restrictions you've outlined that I can determine.  Do I need to add a
local version of opencs.cfg to the pull request?

Otherwise, are there any other issues that need fixing (beyond what we've
immedtiately discussed?)

**Comment by zinnschlag** [comment]
> Do I need to add a local version of opencs.cfg to the pull request?

I think you can use the same file for local and global. Just make sure that it is both copied during build (local) and installed during install (global).

> Otherwise, are there any other issues that need fixing (beyond what we've immedtiately discussed?)

Not that I am aware of, but I still have to test the whole thing.

**Comment by joelgraff** [comment]
Ok, after a quick perusal of the openMW project makefile, I see that most
settings files are named something else (like "openmw.cfg.install" or
"settings-default.cfg").  Do I want the source version of the default
opencs.cfg named similarly?  Otherwise, I think I can follow the project
makefile to figure out how to get that done.

So far as testing goes, do you have any checklists or a process to follow?
I try to think of everything, but there's always stuff I miss - always
looking for ways to improve my game...

**Comment by zinnschlag** [comment]
I hope with makefile you actually mean the cmake file. Naming of the original file (which should be located somewhere in files/) does not matter. As for testing, fire it up and see if it crashes.

**Comment by joelgraff** [comment]
Yes, I was referring to the OpenMW project-level CMakeLists.txt.  :)

**Comment by joelgraff** [comment]
Ok, take a look.  Modified CMakeLists.txt (OpenMW project level) and modified error dialog to pop up only when both global and local settings files are missing.  I imagine there's an aesthetic issue or two, but that should cover the things we've discussed.

**Comment by zinnschlag** [comment]
I'll merge that for now. There are however a few adjustments I would like to see. The user settings categories look wrong. There is no point having a top level category "Window Size", since all this ever contains would be the window size (a whole category for a single setting). Maybe rename it too Window? Also, Editor is not good. That's like "Stuff". The least useful category ever. Maybe "Display Format" or something like this?
I'll have a few unrelated comments to make, but I will PM you these (on the forum).

**Comment by joelgraff** [comment]
I knew about Window Size and just forgot to change it... sorry.  I had
thought to rename it "Window" just as you suggest.  So far as "Editor"
goes, the only item in there relates to table (or views)... Maybe "Tables /
Views" or "Table / View Layout"?  Kinda hard to meaningfully name
categories when we haven't got a lot of settings to work with...

**Comment by zinnschlag** [comment]
It won't be used for tables only, so that would not be correct.

**Comment by joelgraff** [comment]
"Display Format" it is, then.

**Pull request merged**
