### PR TITLE
Ogre 1.9 compatibility changes

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by zinnschlag** [comment]
Let's not do that. We need to move to 1.9 before OpenMW 1.0, so there is no reason to keep support for 1.8. But equally there is no urgent reason to go to 1.9 just yet. We can wait until they have a release (hopefully). This kind of #ifdef-ing should be avoided, unless it is unavoidable.

**Comment by ghost** [comment]
The ifdefs are unavoidable, unless we want to drop backwards-compatibility, and I see no reason to do that, since both Ogre 1.8 and 1.9 work just fine with OpenMW and sticking to either one will impose limitations on packagers.
Besides, I don't see the real issue here, we're just talking about a couple of lines?
Trying out OpenMW with Ogre 1.9 at this point benefits both parties - Ogre developers can get useful feedback from us and we can see if new features are working well. I'm currently using it since I'm making a couple of patches to the 1.9 branch here and there. Why should I go through the trouble of constantly keeping the OpenMW changes in my stash if they don't hurt anyone?

**Comment by kcat** [comment]
I'm not sure I see the issue either. It seems that scrawl has been working on a GL state tracker for Ogre, something we've been waiting for to improve performance (I'm currently building Ogre 1.9 so I'm not sure how much of an improvement it currently provides, but that it's being worked on is enough to get my attention). The ifdefs being added here are rather unobtrusive and they're unlikely to change, because they're a result of Ogre's SharedPtr's switching to use atomics instead of mutexs (which is also a positive thing for performance).

**Comment by zinnschlag** [comment]
We want to drop backward compatibility. Never releasing memory, OpenMW eating up all RAM, remember?

And I think it is a really bad idea with something like OGRE to have one part of the team using one version and another part of the team another version. That's just asking for more hard to track down problems.

**Comment by ghost** [comment]
Even if we do want to drop backward compatibility, I do not see that as an argument to not provide forward compatibility at this point.

> And I think it is a really bad idea with something like OGRE to have one part of the team using one version and another part of the team another version. That's just asking for more hard to track down problems.

That is questionable. Be that as it may, it's one thing to recommend developers to stick to a specific version, but deliberately making it a pain for people who decide to be "adventurous" is just unnecessary, imo.

**Comment by zinnschlag** [comment]
Fine then. I do not agree, but I also don't feel strongly enough about my position here to insist on it. Will merge.

**Pull request closed without merging**
