### PR TITLE
Launcher model

### PR DESCRIPTION
**Pull request by pvdk**
Here you go!

You might want to check out the situation with launcher.cfg in the CMake files. I don't know if they should be copied now since the launcher only uses the user location now.

### CODE REVIEW

**Comment by zinnschlag** [comment]
Segfaults when clicking on the data files tab: https://gist.github.com/3979025

**Comment by pvdk** [comment]
Okay nevermind, I'm able to reproduce this bug when I use an invalid row number in DataFilesModel::flags

EsmFile *file = mFiles.at(index.row());

Is the culprit, no idea why you get an invalid index.row as index is checked for validity.

**Comment by pvdk** [comment]
Commit 433773e  should fix the segfault issue you were having, please test

**Comment by zinnschlag** [comment]
No change. Exactly the same crash.

**Pull request merged**
