### PR TITLE
Import archives

### PR DESCRIPTION
**Pull request by PotatoesMaster**
http://bugs.openmw.org/issues/543

### CODE REVIEW

**Comment by zinnschlag** [comment]
Some problems: We don't want to use these settings in OpenMW yet, because we have no way for the user to run the importer, except from the command line. That would probably exceed the abilities of many users and lead to unnecessary noise in the support forum. Also, can we handle this within the fallback system? Not entirely sure, if that is feasible, but it would definitely be preferable, since this setting is just a fallback. After OpenMW 1.0 most newer content files will ignore it.

**Comment by PotatoesMaster** [comment]
We load at least the "Morrowind.bsa" file when the list of archives to load is empty (the test is done at startup), in the very same manner we load "Morrowind.esm" when no master file is given. This won't prevent people to run OpenMW, unless they want to play without any archive (with files from "Morrowind.bsa" extracted in their "Data files" directory, for example).

As you stated, at some time in the future newer content may render this archive unneeded. But I think importing "Morrowind.bsa" by default makes sense: people who import the other archives from the ini file are going to play the vanilla game and mods. No need to run the importer when vanilla data are not present.

> Also, can we handle this within the fallback system?

I do not think so. We have no way to decide if we should use this fallback value at runtime. IMHO it is better done by the importer, as importing archives is optional (a command line argument must be passed to the importer).

My propositions:
- maybe we should check the emptiness of archive list only if the first master file is "Morrowind.esm". It is contestable, because this will still prevent running the game with no archive.
- alternatively, we could remove that behaviour (defaulting to Morrowind.bsa at runtime) when managing archives with the launcher will be possible, or when the importer will be run by the launcher.

**Comment by zinnschlag** [comment]
> I do not think so. We have no way to decide if we should use this fallback value at runtime. IMHO it is better done by the importer, as importing archives is optional (a command line argument must be passed to the importer).

I do not know what you mean by this. Fallback means just a lightly different syntax for the command line option and a different way of storing the data in OpenMW.

Also, importing the archive list must not be optional. That has no purpose and will only cause confusion.

> maybe we should check the emptiness of archive list only if the first master file is "Morrowind.esm". It is contestable, because this will still prevent running the game with no archive.

I see little point in doing that. It would allow to run other esm files with OpenMW 1.0 without having Morrowind.bsa, but we should be able to do that no later than with OpenMW 1.1 anyway, once the first batch of esx extensions are available.

btw. I am planning to drop the Morrowind.esm hack (choosing this file, if no content files are given) at some point. It doesn't serve any purpose, once we have the importer fully integrated.

> alternatively, we could remove that behaviour (defaulting to Morrowind.bsa at runtime) when managing archives with the launcher will be possible,

Archives will never be managed by the launcher.

**Comment by PotatoesMaster** [comment]
> I do not know what you mean by this. Fallback means just a lightly different syntax for the command line option and a different way of storing the data in OpenMW.

So far, I understand fallback as values used by the game that could later be replaced by OpenMW mods. According to this, I cannot see the value "Morrowind.bsa" as a fallback one. It is one archive name among others.

> Also, importing the archive list must not be optional. That has no purpose and will only cause confusion.

I did it the same way as it was done for esp/esm. We can invert these options (turn them on by default), or remove them completely and import all values that can be.

> I see little point in doing that.

I agree.

> Archives will never be managed by the launcher.

Okay.

My vote go to keep defaulting to Morrowind.bsa when the archive list is empty, and remove this with the Morrowind.esm hack when the importer is fully integrated.

**Comment by zinnschlag** [comment]
> So far, I understand fallback as values used by the game that could later be replaced by OpenMW mods. According to this, I cannot see the value "Morrowind.bsa" as a fallback one. It is one archive name among others.

I am not talking about Morrowind.bsa, but about the list of bsa files in general. If OpenMW sees a content stack, where every file specifies its own bsa file(s), then it won't use the fallback bsa settings at all. If that is not the case, OpenMW will use the bsa settings plus any bsa files specified by the content stack.

> I did it the same way as it was done for esp/esm. We can invert these options (turn them on by default), or remove them completely and import all values that can be.

These are two different cases. If you need to import fallback settings from the ini file, then you need all of them, because otherwise OpenMW will not work. The ESX file list on the other hand does not need to match the one in the ini file and if you ever find that you have to re-import the ini settings, you may not want to overwrite your ESX file list.

Now there could be the situation where someone does not want to overwrite his bsa settings either, because he is actively modifying them all the time. But we would also need an UI element in the launcher for this and since we are pretty much declaring this whole approach for obsolete with OpenMW 1.1, I do not see this being used to a notable amount.
Actually, I expect that the bsa list will be Morrowind.bsa/Tribunal.bsa/Bloodmoon.bsa on pretty much all installations and (almost) never be changed.

> My vote go to keep defaulting to Morrowind.bsa when the archive list is empty, and remove this with the Morrowind.esm hack when the importer is fully integrated.

That is not consistent with what MW does. To repeat that again: We can not use any fallback values in OpenMW yet. At some point we will get multiple ESX support. There are some problems with the branch and I don't know if it will happen sooner or later. If it happens sooner, you proposed solution (including changing OpenMW now) will mess things up big time.

After having thought about it a bit more, I came to the conclusion, that the importer should prefix the list with Morrowind.bsa anyway. This gets us the same result as MW, but we can keep the hack out of OpenMW entirely.

**Comment by PotatoesMaster** [comment]
I must say I did not take all of that into account. 

To sum up, modifying the importer is enough for now and changes to OpenMW will happen later.

**Comment by zinnschlag** [comment]
> To sum up, modifying the importer is enough for now and changes to OpenMW will happen later.

Correct.

**Pull request closed without merging**
