### PR TITLE
Shadersystem

### PR DESCRIPTION
**Pull request by ghost**
http://bugs.openmw.org/issues/248
http://bugs.openmw.org/issues/315
http://bugs.openmw.org/issues/300

Lots of core functionality has been outsourced in a submodule.

### CODE REVIEW

**Comment by zinnschlag** [comment]
Absolutely not keen on having submodules again. They have caused us a lot of trouble already. Is there any good reason to not simply have the code from the submodule as a part of the OpenMW repository?

**Comment by ghost** [comment]
> Is there any good reason to not simply have the code from the submodule as a part of the OpenMW repository?

Yes, because I am using this code in another game / repo as well.

I'm probably the only one who edits this code, so there's not much trouble for anyone.

Besides, I have read that recent versions of git update the submodule automatically on master branches on the first pull, so there's no extra difficulty for users that want to compile.

**Comment by zinnschlag** [comment]
Okay then. But if a have an angry developer mob coming up to me I will redirect them straight to you.

Anyway, there are several problems with the code:
1. It segfaults on startup. Here is the backtrace: https://gist.github.com/3151994
2. I get tons of warning when building. That must be fixed. Here is the log: https://gist.github.com/3151997
3. You are using file globbing in a cmake script. Please don't. That causes nothing but trouble.

**Comment by ghost** [comment]
> 1. It segfaults on startup. Here is the backtrace: https://gist.github.com/3151994

Looks like a version mismatch of ogre libs / plugins. Do you really use 1.8RC1, since that's what the source filenames in the backtrace say?

> 1. I get tons of warning when building.

Was planning to exchange mcpp with glcpp (from mesa) anyway. Hopefully that will get rid of the warnings.

> 1. You are using file globbing in a cmake script. Please don't. That causes nothing but trouble.

I would agree for source files, but for resources it's just insane to add every new file to the cmake scripts. I don't see a reason not to use globbing there.

**Comment by ghost** [comment]
Regarding the crash, could you paste the output of

locate RenderSystem_GL
locate libOgreMain

**Comment by zinnschlag** [comment]
Cutting out everything from my OGRE build directories, I get this:

/usr/local/lib/OGRE/RenderSystem_GL.so
/usr/local/lib/OGRE/RenderSystem_GL.so.1.8.0

/usr/local/lib/libOgreMain-1.4.9.so
/usr/local/lib/libOgreMain.so
/usr/local/lib/libOgreMain.so.1.7.0
/usr/local/lib/libOgreMain.so.1.7.1
/usr/local/lib/libOgreMain.so.1.8.0

**Comment by zinnschlag** [comment]
> Looks like a version mismatch of ogre libs / plugins. Do you really use 1.8RC1, since that's what the source filenames in the backtrace say?

Yes, I am using 1.8RC1. Did not get around to install 1.8 yet.

> I would agree for source files, but for resources it's just insane to add every new file to the cmake scripts. I don't see a reason not to use globbing there.

If you glob and then add another file, the build process will not run correctly, because cmake doesn't know that there is another file. Make a macro that takes a list of files, if adding files individually is too much work.

**Comment by ghost** [comment]
> If you glob and then add another file, the build process will not run correctly, because cmake doesn't know that there is another file. Make a macro that takes a list of files, if adding files individually is too much work.

I have not experienced that issue. And a list of files is still wasted effort, if there are no files at all that you want to exclude. If this really does become a problem, we should consider to skip the whole "copy files to build directory" hack and instead tell openmw the path to the files/ directory.

EDIT: Deleting CmakeCache after adding a file will fix the problem at all times, which is definitely less effort than maintaining a list of files to copy.

**Comment by ghost** [comment]
> Did not get around to install 1.8 yet.

Ok, then please do so. If that doesn't fix the issue, it must be some other weird library configuration issue, definitely not something in our codebase.

**Comment by zinnschlag** [comment]
> EDIT: Deleting CmakeCache after adding a file will fix the problem at all times, which is definitely less effort than maintaining a list of files to copy. 

Not if every single developer has to repeated it.

> Ok, then please do so. If that doesn't fix the issue, it must be some other weird library configuration issue, definitely not something in our codebase.

Okay. Maybe tomorrow. Don't have the CPU power to spare right now for building OGRE (and lots of stuff that depends on it).

**Comment by ghost** [comment]
> Not if every single developer has to repeated it.

Ok, that sucks. Really stupid behaviour of Cmake, then.

In that case I would rather put all the resources in a zip file, and load it with ogre.

**Comment by ghost** [comment]
Using a zipfile will mean no commit diffs. I think there is no good solution to the problem then, except for this:

> If this really does become a problem, we should consider to skip the whole "copy files to build directory" hack and instead tell openmw the path to the files/ directory.

Another reason why this hack is problematic, is because files that are already deleted in files/ will stay in build/resources forever, unless you delete them manually.

What do you think?

**Comment by zinnschlag** [comment]
That is not very version control system friendly. Sorry, but there is no proper way around listing every single file. If you don't want to manually make a list, do a ls instead and then a copy and paste.

**Comment by ghost** [comment]
I assume you referred to the zipfile solution, what about this suggestion  https://github.com/zinnschlag/openmw/pull/258#issuecomment-7137825 ?

**Comment by zinnschlag** [comment]
Sounds unclean. The OpenMW build would depend on the source directory. For people who want to build OpenMW manually (instead of using a prebuild package), OpenMW would fail if they (for whatever reason) decide to wipe the source directory.

**Comment by ghost** [comment]
Ok, then. I've made a macro which takes the file list in an ls-style manner, which is semi-acceptable i guess.

**Comment by zinnschlag** [comment]
Still crashes after updating OGRE. Exactly in the same spot it seems.

**Comment by ghost** [comment]
No clue then. Still convinced that it has to be a problem specific to your setup. Does it run if you change [General] shader mode to "cg" ?

**Comment by zinnschlag** [comment]
Yeah, that fixes it. Before I set it to cg the line looks like this:

shader mode =

is that correct?

**Comment by ghost** [comment]
Yes, that's correct. That line means to use glsl or hlsl, depending on the rendersystem (DirectX or OpenGL). Starting with "shader mode = " works here.

**Comment by ghost** [comment]
If you run OgreSampleBrowser and choose the "Shader system" sample, does that work? That sample has a "language" drop-down box that you can set to GLSL (I believe it's already the default, though)

**Comment by zinnschlag** [comment]
The shader system sample works for me with language set to GLSL.

**Comment by ghost** [comment]
Hm, then unless there is something interesting in Ogre.log from OpenMW when running with glsl, i'm out of ideas. Could you paste it, just in case?

**Comment by zinnschlag** [comment]
https://gist.github.com/3155923

**Comment by ghost** [comment]
There are a lot of already deleted resources in your build/resources. Any difference if you wipe that folder completely and re-run cmake?

**Comment by zinnschlag** [comment]
Absolutely no difference. Anything else would have been strange anyway.

**Comment by zinnschlag** [comment]
This isn't getting us anywhere. How many people have tested your code so far? Only you and me? In this case we should try to get a larger sample size. Two is not enough. Maybe ask our developers on the forum to try it?

**Comment by ghost** [comment]
I had 3 testers on the IRC and it looks like you're pretty much alone with the crash.

**Comment by zinnschlag** [comment]
Not sure how to proceed from here. Let me ponder about it for a couple more days.

**Comment by zinnschlag** [comment]
I reopened the pull request so that it stays easily accessible and doesn't get lost in the spam of github activity.

**Comment by ghost** [comment]
The crash was a 32-bit specific ogre bug, I added a workaround for it.

**Comment by ghost** [comment]
Please merge again, fixed a cmake issue with older boost version.

**Pull request merged**
