### PR TITLE
Editor dialog

### PR DESCRIPTION
**Pull request by sirherrbatka**
changelog is long because contains changes from the preview branch

### CODE REVIEW

**Comment by zinnschlag** [comment]
I see a few issue here. In info records response has to use the large multi-line field. And the cell field is for whatever reasons flagged as non-editable, which is definitely wrong. Same for teleport cell in references.

We should also consider moving the button bar to the bottom. At some point someone might add a regular main window toolbar. This would result in two toolbars on top each other, which would look cluttered in my opinion. On the other hand there is plenty of room at the bottom of the subview, especially since we don't have a status bar.

Finally we should make the minimum width of the subview configurable. We can't do that right now, because we don't have working user settings yet. But it wouldn't hurt to add a \todo comment, so we don't forget about it.

**Comment by sirherrbatka** [comment]
> I see a few issue here. In info records response has to use the large
> multi-line field.
> Ok, i missed it.
> 
> And the cell field is for whatever reasons flagged as
> non-editable, which is definitely wrong. Same for teleport cell in
> references.
> Hmmmm, i'm following the settings from the table itself. Cell is also not 
> editable there. Should i use different strategy, or it is table in fault?
> 
> We should also consider moving the button bar to the bottom. At some point
> someone might add a regular main window toolbar. This would result in two
> toolbars on top each other, which would look cluttered in my opinion. On
> the other hand there is plenty of room at the bottom of the subview,
> especially since we don't have a status bar.
> I'm not huge fan of bottom tollbars, but if you really think it is needed i 
> can easily change it.
> 
> Finally we should make the minimum width of the subview configurable. We
> can't do that right now, because we don't have working user settings yet.
> But it wouldn't hurt to add a \todo comment, so we don't forget about it.
> Fair enough.

**Comment by zinnschlag** [comment]
There is a bug in TeleportCellColumn. Just removing the function isUserEditable should fix it (because the default implementation is re-using the return value of isEditable). I assume it is the same in the other case.

**Comment by sirherrbatka** [comment]
Right. Done.

**Comment by zinnschlag** [comment]
The change to dialoguesubview.cpp (line 356) looks wrong. Surely that would break a lot of things.

**Comment by sirherrbatka** [comment]
sorry, i have no idea why i did this. I feel slightly ashamed.

**Comment by zinnschlag** [comment]
That actually does not build, if I merge into master:

> /home/marc/OpenMW/openmw/apps/opencs/view/world/dialoguesubview.cpp: In member function ‘void CSVWorld::EditWidget::remake(int)’:
> /home/marc/OpenMW/openmw/apps/opencs/view/world/dialoguesubview.cpp:356:44: error: no matching function for call to ‘CSMWorld::IdTable::flags(<unresolved overloaded function type>)’
> /home/marc/OpenMW/openmw/apps/opencs/view/world/dialoguesubview.cpp:356:44: note: candidate is:
> /home/marc/OpenMW/openmw/apps/opencs/view/world/../../model/world/idtable.hpp:66:35: note: virtual Qt::ItemFlags CSMWorld::IdTable::flags(const QModelIndex&) const
> /home/marc/OpenMW/openmw/apps/opencs/view/world/../../model/world/idtable.hpp:66:35: note:   no known conversion for argument 1 from ‘<unresolved overloaded function type>’ to ‘const QModelIndex&’

**Comment by sirherrbatka** [comment]
Wii build now. Sorry for extra problems, somehow i always get overexcited 
during merge time…

**Comment by zinnschlag** [comment]
Lol!

Merging ...

**Pull request merged**
