### PR TITLE
Bug fix

### PR DESCRIPTION
**Pull request by sirherrbatka**
Fixed that bug, and reduced number of signals.

### CODE REVIEW

**Comment by zinnschlag** [comment]
Getting tons of merge conflicts here.

**Comment by sirherrbatka** [comment]
hm, that's odd. It was created from your master branch. Let me take a look 
into this.

**Comment by ghost** [comment]
Won't it get messy if we're using two repos? I thought we moved to OpenMW/OpenMW...

**Comment by sirherrbatka** [comment]
I forgot to update the fork. That's all.

**Comment by zinnschlag** [comment]
The last commit looks seriously wrong. Sending a pull request against the wrong repository is not such a big deal. Merging from the wrong repository definitely is.

**Comment by sirherrbatka** [comment]
so we are pushing changes to the openmw/master not to the zini/master?

**Comment by ghost** [comment]
Yes reference this: https://forum.openmw.org/viewtopic.php?f=6&t=2106

**Comment by sirherrbatka** [comment]
Well, fuck.

**Pull request closed without merging**
