### PR TITLE
fix

### PR DESCRIPTION
**Pull request by sirherrbatka**
tivial fix

### CODE REVIEW

**Comment by zinnschlag** [comment]
Wouldn't that break in situations where only a specific type or even a sub-set of referenceable types can be used?

**Comment by sirherrbatka** [comment]
Yes, but do we have situations like this anywhere?

PS
Where do we actually drop refencables?

**Comment by zinnschlag** [comment]
Initial content of containers for example.

**Comment by zinnschlag** [comment]
In the current implementation a drop target for referenceables would be the referenceable ID column in the reference table.

**Comment by sirherrbatka** [comment]
Right, give me some time and i will make proper fix.

**Comment by zinnschlag** [comment]
Okay. I just noticed that you are still using toStdString for string conversion. Please stop that. It breaks things.

**Comment by sirherrbatka** [comment]
uh, i thought that fromStdString is a problem, but not toStdString.

**Comment by zinnschlag** [comment]
Doesn't matter. They are both doing the same thing, just in the opposite direction.

**Comment by zinnschlag** [comment]
Fix for the existing encoding problems is in preview branch now.

**Comment by sirherrbatka** [comment]
thanks

**Pull request closed without merging**
