### PR TITLE
Trader Gold Reset Delay

### PR DESCRIPTION
**Pull request by ghost**
Implemented trader gold reset delay.

http://bugs.openmw.org/issues/953

Note:
Traders gold pool is still in inventory.

### CODE REVIEW

**Comment by zinnschlag** [comment]
Two problems.
1. You initialise the time with the current timestamp. Since the ensureCustomData function can be called in various situations, this is effectively a semi-random value. It would be better to initialise the time to 0.
2. In checkTradeTime you are calling mPtr.getESM::NPC(). That will fail, if the vendor is a creature. It is also redundant. From what I see you only use the LiveCelRef to get the default gold. But you are storing that already in the CreatureStats, so there is no need at all to access the record.

**Comment by ghost** [comment]
1) I now initialize time to 0
2) No longer does checkTradeTime exclude creatures.

mGoldPool was suggested by scrawl to fix the inventory issues of merchants. 

EDIT: Until we figure out the inventory issues:

addOrRemoveGold(-store.count(MWWorld::ContainerStore::sGoldId), mPtr);
addOrRemoveGold(+sellerStats.getGoldPool(), mPtr);

This looks like it will remove all of the gold from the store.

I will make note as I attempt to solve the inventory issue for another pull later today,

EDIT: Should there be a console command to set the gold pool of an NPC?

**Comment by zinnschlag** [comment]
What is the "inventory issue"? As far as I can tell everything is working as intended now. Using mGoldPool for the total amount of available gold is a good idea anyway, because after OpenMW 1.0 we will probably add the ability to modify the max gold.
There is no script instruction for modifying the max gold in vanilla MW.

btw. testing now ...

**Comment by zinnschlag** [comment]
Actually, I do see a problem. You are applying the gold update to all actors. But it should be applied only to vendors.

**Comment by ghost** [comment]
Ok so when you kill a merchant you will get access to his gold pool. 

mGoldPool was suppose to be the variable that kept track of how much gold the merchant had

While the merchant inventory store is only supposed to be the gold the merchant actually has equipped.

**Comment by zinnschlag** [comment]
Sounds overly complicated to me. Anyway, the gold the merchant has in his inventory should be for the most part the gold the merchant has. Unless we also count gold, that is stored in a chest owned by the merchant (not entirely sure if MW does that). In this case we can not use a separate variable to track the amount of gold he has, because that would not adjust accordingly when the content of such a chest is modified.

**Comment by ghost** [comment]
Did you read this post? https://forum.openmw.org/viewtopic.php?f=6&t=2100&p=23372#p23358

**Comment by zinnschlag** [comment]
Just noticed it. I guess we should continue the discussion there. Having to separate discussion threads for the same topic is confusing.

**Pull request merged**
