### PR TITLE
Feature #468: Editor: Window Size

### PR DESCRIPTION
**Pull request by Glorf**
Please, write if you have any suggestions, because it's my first Qt task here.

### CODE REVIEW

**Comment by zinnschlag** [comment]
Why are you loading the settings every time the getSettingValue function is called? That sounds very inefficient. The settings should be loaded only once on startup.

**Comment by Glorf** [comment]
Should be good now.

**Comment by Glorf** [comment]
I've realised that settings won't be properly set and shown in the settings window in the same session when they were changed (because they are loaded on startup). I think the best resolution is to show a dialog and tell user that he has to restart editor to use new settings. What about that?

**Comment by zinnschlag** [comment]
Silently changing to a different singleton implementation, eh? Sneaky. Got me puzzled for a bit. Anyway, I'll merge that, but I think we need a few more improvements.
- The layout seems slightly off. I am not entirely sure, if I remember correctly, but shouldn't you use a GroupBox?
- It seems the changes in the settings window only come in effect after a restart. Something is still wrong there.

**Comment by zinnschlag** [comment]
Nope. No restart required. That is wrong. Settings need to come into effect immediately. In this case this means for new windows (existing ones should not be touched).

**Comment by zinnschlag** [comment]
Actually, "Window Size" as a top level category also does not look right. What else do you want to put in there? We can't have a category with only one option in it. Maybe change it to Window?

**Pull request merged**
