### PR TITLE
add proper compiler switches for clang

### PR DESCRIPTION
**Pull request by RicoTilgner**
This adds GCC-like switches for warnings/C++11 when compilig with Clang.
I disabled the overloaded virtual warnings as the Ogre headers have quite a lot of them.

With the new settings there are quite a few warnings, mostly (harmless) struct/class mismatches in the nif-files but also at least one real bug that I saw skimming through them. I'll make another pull request after fixing these.

### CODE REVIEW

**Comment by RicoTilgner** [comment]
Fixes for the warnings are in the second commit.
The one in alchemy.cpp was a real bug, the warning message would have had some random string in it instead of what was intended. ;-)

**Comment by kcat** [comment]
The casts in videoplayer.cpp were actually needed to silence GCC. It seems to treat AV_NOPTS_VALUE as an unsigned 64-bit value, while the pts/dts fields are signed 64-bit values, which causes 'comparison between signed and unsigned' warnings.

**Comment by RicoTilgner** [comment]
ok, that's strange... AV_NOPTS_VALUE is a signed value here, just like the pts/dts... I'll have a look at why that is on Friday.

**Comment by kcat** [comment]
Possibly because it's defined as 0x8000000000000000 (with one or two L's depending on the target), and GCC treats stuff like that as an unsigned value. Same thing happens if you compared a signed char with 0x80-0xFF.

Saying that, I would probably consider this a GCC bug since I think the hex value is supposed to be interpreted as an int (or long with l, or long long with ll), and only take it as unsigned if it has a u. Though I can't say I know C/C++ well enough to say for sure. FFmpeg even makes sure to use the glibc-provided INT64_C wrapper to define the value, which is distinct from UINT64_C.

**Comment by zinnschlag** [comment]
We decided to not go with C++11 for the time being.

**Pull request closed without merging**
